import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'fr' | 'en' | 'ln' | 'kg' | 'lua' | 'sw';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  formatCurrency: (amount: number, currency?: 'CDF' | 'USD') => string;
}

const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.transport': 'Transport',
    'nav.delivery': 'Livraison',
    'nav.marketplace': 'Marketplace',
    'nav.profile': 'Profil',
    'nav.history': 'Historique',
    'nav.payment': 'Paiement',
    'nav.notifications': 'Notifications',
    'nav.settings': 'Paramètres',
    'nav.wallet': 'Portefeuille',
    'nav.earnings': 'Gains',
    'nav.challenges': 'Défis',
    'nav.support': 'Support',
    
    // Header & Navigation
    'header.services': 'Services',
    'header.advantages': 'Avantages',
    'header.contact': 'Contact',
    'header.client': 'Client',
    'header.driver': 'Chauffeur',
    'header.admin': 'Admin',
    'header.download_app': 'Télécharger l\'App',
    'header.menu': 'Menu',
    
    // Hero Section
    'hero.innovation_excellence': 'Innovation & Excellence',
    'hero.kwenda_taxi': 'Kwenda Taxi',
    'hero.tagline': 'Transport intelligent pour Kinshasa. Moto-taxi, taxi voiture, livraison et marketplace - tout en une seule application adaptée à la RDC.',
    'hero.location': 'Kinshasa, Congo RDC',
    'hero.available_24_7': 'Disponible 24h/24',
    'hero.start_now': 'Commencer maintenant',
    'hero.view_demo': 'Voir la démo',
    'hero.transport_types': 'Types Transport',
    'hero.customer_service': 'Service Client',
    'hero.kwenda_pay': 'KwendaPay',
    'hero.made_in_rdc': '🇨🇩 Made in RDC',
    'hero.alt_text': 'Kwenda Taxi - Transport intelligent à Kinshasa',
    
    // Services Section
    'services.title': 'Nos Services',
    'services.subtitle': 'Une gamme complète de services de transport adaptés à tous vos besoins en République Démocratique du Congo.',
    'services.vtc_standard': 'VTC Standard',
    'services.vtc_standard_desc': 'Véhicules confortables et écologiques pour vos déplacements quotidiens.',
    'services.vtc_standard_price': 'À partir de 3000 CDF',
    'services.vtc_standard_feat1': 'Véhicules récents',
    'services.vtc_standard_feat2': 'Climatisation',
    'services.vtc_standard_feat3': 'Chauffeur professionnel',
    'services.vtc_luxe': 'VTC Luxe',
    'services.vtc_luxe_desc': 'Limousines et véhicules haut de gamme pour vos événements spéciaux.',
    'services.vtc_luxe_price': 'À partir de 8000 CDF',
    'services.vtc_luxe_feat1': 'Véhicules de luxe',
    'services.vtc_luxe_feat2': 'Service premium',
    'services.vtc_luxe_feat3': 'Conciergerie',
    'services.shared_rides': 'Trajets Partagés',
    'services.shared_rides_desc': 'Économisez en partageant votre trajet avec d\'autres passagers.',
    'services.shared_rides_price': 'À partir de 1500 CDF',
    'services.shared_rides_feat1': 'Tarifs réduits',
    'services.shared_rides_feat2': 'Écologique',
    'services.shared_rides_feat3': 'Réservation flexible',
    'services.moto_delivery': 'Livraison Moto',
    'services.moto_delivery_desc': 'Service de livraison rapide en moto pour vos colis et documents.',
    'services.moto_delivery_price': 'À partir de 5000 CDF',
    'services.moto_delivery_feat1': 'Livraison express',
    'services.moto_delivery_feat2': 'Suivi en temps réel',
    'services.moto_delivery_feat3': 'Sécurisé',
    'services.utility_vehicles': 'Véhicules Utilitaires',
    'services.utility_vehicles_desc': 'Transport de marchandises et déménagements avec nos utilitaires.',
    'services.utility_vehicles_price': 'À partir de 15000 CDF',
    'services.utility_vehicles_feat1': 'Véhicules spacieux',
    'services.utility_vehicles_feat2': 'Aide au chargement',
    'services.utility_vehicles_feat3': 'Assurance',
    'services.advance_booking': 'Réservation Avancée',
    'services.advance_booking_desc': 'Planifiez vos trajets à l\'avance pour vos rendez-vous importants.',
    'services.advance_booking_price': 'Sans supplément',
    'services.advance_booking_feat1': 'Garantie horaire',
    'services.advance_booking_feat2': 'Confirmation SMS',
    'services.advance_booking_feat3': 'Priorité',
    'services.popular': '⭐ Populaire',
    'services.book_now': 'Réserver maintenant',
    'services.cta_title': 'Prêt à transformer votre expérience de transport ?',
    'services.cta_subtitle': 'Rejoignez des milliers d\'utilisateurs qui font confiance à Kwenda pour leurs déplacements quotidiens.',
    'services.download_app': 'Télécharger l\'App',
    'services.become_driver_partner': 'Devenir Chauffeur Partenaire',
    
    // Features Section
    'features.title_prefix': 'Pourquoi choisir',
    'features.title_brand': 'Kwenda Taxi',
    'features.subtitle': 'Une expérience de transport révolutionnaire adaptée aux besoins du marché congolais.',
    'features.eco_fleet': 'Flotte Écologique',
    'features.eco_fleet_desc': '1000 véhicules de luxe respectueux de l\'environnement pour un transport propre et confortable.',
    'features.smart_geolocation': 'Géolocalisation Intelligente',
    'features.smart_geolocation_desc': 'Système de géolocalisation en temps réel pour une arrivée rapide et un suivi précis de votre trajet.',
    'features.certified_drivers': 'Chauffeurs Certifiés',
    'features.certified_drivers_desc': 'Conducteurs professionnels formés et vérifiés pour votre sécurité et votre confort.',
    'features.flexible_payments': 'Paiements Flexibles',
    'features.flexible_payments_desc': 'Mobile Money, cartes bancaires, espèces - tous les moyens de paiement acceptés.',
    'features.shared_rides': 'Trajets Partagés',
    'features.shared_rides_desc': 'Options de covoiturage et trajets groupés pour économiser et réduire l\'impact environnemental.',
    'features.maximum_security': 'Sécurité Maximale',
    'features.maximum_security_desc': 'Assurance complète, suivi GPS, système de notation pour votre tranquillité d\'esprit.',
    'features.stats_vehicles': 'Véhicules Disponibles',
    'features.stats_support': 'Support Client',
    'features.stats_eco': 'Véhicules Écologiques',
    'features.stats_cities': 'Kinshasa & Lubumbashi',
    'features.alt_eco_car': 'Véhicules éco',
    'features.alt_mobile_app': 'Application mobile',
    'features.alt_professional_drivers': 'Chauffeurs professionnels',
    
    // Footer
    'footer.services_vtc_standard': 'VTC Standard',
    'footer.services_vtc_luxe': 'VTC Luxe',
    'footer.services_shared_rides': 'Trajets Partagés',
    'footer.services_moto_delivery': 'Livraison Moto',
    'footer.services_utility': 'Véhicules Utilitaires',
    'footer.company_mission': 'Notre mission',
    'footer.company_team': 'Équipe',
    'footer.company_press': 'Presse',
    'footer.company_partnerships': 'Partenariats',
    'footer.company_careers': 'Carrières',
    'footer.support_contact': 'Contact',
    'footer.support_help': 'Centre d\'aide',
    'footer.support_faq': 'FAQ',
    'footer.support_privacy': 'Politique de confidentialité',
    'footer.support_terms': 'Conditions d\'utilisation',
    'footer.app_download_title': 'Téléchargez l\'App Kwenda Taxi',
    'footer.app_download_subtitle': 'Disponible bientôt sur iOS et Android',
    'footer.notify_ios': 'Me notifier iOS',
    'footer.notify_android': 'Me notifier Android',
    'footer.copyright': '© 2025 Kwenda Taxi. Tous droits réservés.',
    'footer.social_facebook': 'Facebook',
    'footer.social_twitter': 'Twitter',
    'footer.social_instagram': 'Instagram',
    'footer.social_linkedin': 'LinkedIn',
    
    // Delivery Interface
    'delivery.title': 'Service de Livraison',
    'delivery.subtitle': 'Choisissez votre type de livraison',
    'delivery.flash': 'Livraison Flash',
    'delivery.flash_desc': 'Livraison ultra-rapide en moto (30-60 min)',
    'delivery.flash_vehicle': 'Moto',
    'delivery.flash_price': '5000 CDF + 500/km',
    'delivery.flash_feat1': 'Livraison express',
    'delivery.flash_feat2': 'Idéal pour les documents',
    'delivery.flash_feat3': 'Suivi en temps réel',
    'delivery.flex': 'Livraison Flex',
    'delivery.flex_desc': 'Livraison standard économique (2-4h)',
    'delivery.flex_vehicle': 'Voiture',
    'delivery.flex_price': '3000 CDF + 300/km',
    'delivery.flex_feat1': 'Prix abordable',
    'delivery.flex_feat2': 'Colis moyens',
    'delivery.flex_feat3': 'Fiable',
    'delivery.maxicharge': 'MaxiCharge',
    'delivery.maxicharge_desc': 'Livraison de gros colis par camion (4-8h)',
    'delivery.maxicharge_vehicle': 'Camion',
    'delivery.maxicharge_price': '8000 CDF + 800/km',
    'delivery.maxicharge_feat1': 'Gros volumes',
    'delivery.maxicharge_feat2': 'Aide au chargement',
    'delivery.maxicharge_feat3': 'Assurance incluse',
    'delivery.step_service': 'Service',
    'delivery.step_addresses': 'Adresses',
    'delivery.step_confirmation': 'Confirmation',
    'delivery.pickup_location': 'Lieu de ramassage',
    'delivery.pickup_placeholder': 'Rechercher l\'adresse de ramassage...',
    'delivery.delivery_location': 'Lieu de livraison',
    'delivery.delivery_placeholder': 'Rechercher l\'adresse de livraison...',
    'delivery.package_description': 'Description du colis',
    'delivery.package_placeholder': 'Décrivez votre colis...',
    'delivery.recipient_name': 'Nom du destinataire',
    'delivery.recipient_phone': 'Téléphone du destinataire',
    'delivery.special_instructions': 'Instructions spéciales',
    'delivery.instructions_placeholder': 'Instructions pour le chauffeur...',
    'delivery.next': 'Suivant',
    'delivery.previous': 'Précédent',
    'delivery.confirm_order': 'Confirmer la commande',
    'delivery.cancel': 'Annuler',
    'delivery.step': 'Étape',
    'delivery.of': 'sur',
    'delivery.loading': 'Chargement...',
    'delivery.search_locations': 'Rechercher des lieux...',
    'delivery.use_current_location': 'Utiliser ma position actuelle',
    'delivery.estimated_price': 'Prix estimé',
    'delivery.total_distance': 'Distance totale',
    'delivery.estimated_time': 'Temps estimé',
    'delivery.order_summary': 'Résumé de la commande',
    'delivery.selected_service': 'Service sélectionné',
    'delivery.contact_details': 'Coordonnées',
    'delivery.order_details': 'Détails de la commande',
    
    // Location Search
    'location.search_placeholder': 'Rechercher un lieu...',
    'location.current_location': 'Position actuelle',
    'location.no_results': 'Aucun résultat trouvé',
    'location.searching': 'Recherche en cours...',
    'location.select_location': 'Sélectionner ce lieu',
    'location.approximate': 'Position approximative',
    'location.unavailable': 'Localisation indisponible',
    'location.gps_unavailable': 'GPS indisponible',
    
    // Auth
    'auth.login': 'Se connecter',
    'auth.register': 'S\'inscrire',
    'auth.logout': 'Se déconnecter',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.phone': 'Téléphone',
    'auth.forgot_password': 'Mot de passe oublié',
    'auth.reset_password': 'Réinitialiser',
    'auth.verify_phone': 'Vérifier le téléphone',
    
    // Transport Congo RDC
    'transport.book': 'Réserver',
    'transport.pickup': 'Point de départ',
    'transport.destination': 'Destination',
    'transport.vehicle': 'Véhicule',
    'transport.price': 'Prix',
    'transport.time': 'Temps estimé',
    'transport.taxi_bus': 'Taxi-bus',
    'transport.moto_taxi': 'Moto-taxi',
    'transport.taxi_voiture': 'Taxi voiture',
    'transport.bus_transco': 'Bus Transco',
    'transport.status.pending': 'En attente',
    'transport.status.confirmed': 'Confirmé',
    'transport.status.en_route': 'En route',
    'transport.status.arrived': 'Arrivé',
    'transport.status.completed': 'Terminé',
    'transport.status.cancelled': 'Annulé',
    'transport.driver_arriving': 'Chauffeur en approche',
    'transport.eta': 'Arrivée estimée',
    
    // Package types
    'package.small': 'Petit',
    'package.small_desc': 'Documents, smartphone, bijoux',
    'package.small_weight': 'Jusqu\'à 2kg',
    'package.medium': 'Moyen',
    'package.medium_desc': 'Vêtements, livres, électronique',
    'package.medium_weight': '2-10kg',
    'package.large': 'Grand',
    'package.large_desc': 'Électroménager, meubles',
    'package.large_weight': '10-50kg',
    'package.extra_large': 'Très grand',
    'package.extra_large_desc': 'Réfrigérateur, matelas',
    'package.extra_large_weight': 'Plus de 50kg',
    
    // Marketplace
    'marketplace.title': 'Marketplace',
    'marketplace.browse': 'Explorer',
    'marketplace.chat': 'Chat',
    'marketplace.admin': 'Admin',
    'marketplace.products': 'Produits',
    'marketplace.categories': 'Catégories',
    'marketplace.cart': 'Panier',
    'marketplace.favorites': 'Favoris',
    'marketplace.orders': 'Commandes',
    'marketplace.sell': 'Vendre',
    'marketplace.buy': 'Acheter',
    'marketplace.add_to_cart': 'Ajouter au panier',
    'marketplace.checkout': 'Commander',
    'marketplace.price': 'Prix',
    'marketplace.description': 'Description',
    'marketplace.seller': 'Vendeur',
    'marketplace.rating': 'Note',
    'marketplace.reviews': 'Avis',
    'marketplace.stock': 'Stock',
    'marketplace.category': 'Catégorie',
    'marketplace.noConversations': 'Aucune conversation',
    'marketplace.startChatting': 'Commencez à discuter avec les vendeurs pour voir vos conversations ici.',
    'marketplace.all_trends': 'Toutes les tendances',
    'marketplace.trending_products': 'Produits tendances',
    'marketplace.back_to_trends': 'Retour aux tendances',
    'marketplace.back_to_marketplace': 'Retour au marketplace',
    
    // Driver
    'driver.dashboard': 'Tableau de bord',
    'driver.earnings': 'Gains',
    'driver.trips': 'Courses',
    'driver.status': 'Statut',
    'driver.online': 'En ligne',
    'driver.offline': 'Hors ligne',
    'driver.available': 'Disponible',
    'driver.busy': 'Occupé',
    'driver.accept_trip': 'Accepter la course',
    'driver.decline_trip': 'Refuser la course',
    'driver.start_trip': 'Commencer la course',
    'driver.complete_trip': 'Terminer la course',
    'driver.vehicle_info': 'Infos véhicule',
    'driver.license': 'Permis',
    'driver.rating': 'Note',
    'driver.total_trips': 'Total courses',
    'driver.vehicle': 'Véhicule',
    'driver.vehicleType': 'Type de véhicule',
    'driver.vehicleModel': 'Modèle',
    'driver.vehiclePlate': 'Plaque',
    'driver.licenseNumber': 'Permis',
    'driver.insuranceNumber': 'Assurance',
    
    // Wallet
    'wallet.balance': 'Solde',
    'wallet.topup': 'Recharger',
    'wallet.withdraw': 'Retirer',
    'wallet.history': 'Historique',
    'wallet.transaction': 'Transaction',
    'wallet.amount': 'Montant',
    'wallet.fee': 'Frais',
    'wallet.total': 'Total',
    'wallet.pending': 'En attente',
    'wallet.completed': 'Terminé',
    'wallet.failed': 'Échoué',
    
    // Notifications
    'notification.new_trip': 'Nouvelle course disponible',
    'notification.trip_accepted': 'Course acceptée',
    'notification.driver_arrived': 'Chauffeur arrivé',
    'notification.trip_started': 'Course commencée',
    'notification.trip_completed': 'Course terminée',
    'notification.payment_received': 'Paiement reçu',
    'notification.promotion': 'Promotion spéciale',
    'notification.system': 'Notification système',
    
    // Villes principales
    'city.kinshasa': 'Kinshasa',
    'city.lubumbashi': 'Lubumbashi', 
    'city.kolwezi': 'Kolwezi',
    'city.abidjan': 'Abidjan',
    
    // Demo Page
    'demo.title': 'Découvrez Kwenda Taxi',
    'demo.subtitle': 'en Action',
    'demo.description': 'Explorez toutes les fonctionnalités de notre application à travers des démonstrations interactives de nos services principaux.',
    'demo.interactive_demo': '🎬 Démo Interactive Kwenda',
    'demo.launch_demo': 'Lancer la Démo',
    'demo.view_live': 'Voir en Live',
    'demo.choose_demo': 'Choisissez une Démonstration',
    'demo.mobile_view': 'Vue Mobile',
    'demo.tablet_view': 'Vue Tablette', 
    'demo.desktop_view': 'Vue Bureau',
    'demo.with_sound': 'Avec Son',
    'demo.without_sound': 'Sans Son',
    'demo.start': 'Démarrer',
    'demo.stop': 'Arrêter',
    'demo.restart': 'Recommencer',
    'demo.demo_steps': 'Étapes de la Démonstration',
    'demo.transport_demo': 'Réserver un Transport VTC',
    'demo.delivery_demo': 'Commander une Livraison Express',
    'demo.marketplace_demo': 'Acheter sur la Marketplace',
    'demo.why_kwenda': 'Pourquoi Kwenda Taxi ?',
    'demo.congo_adapted': 'Une application pensée pour répondre aux besoins spécifiques du Congo RDC',
    'demo.intuitive_interface': 'Interface Intuitive',
    'demo.intuitive_desc': 'Design simple et adapté à tous les niveaux',
    'demo.precise_geolocation': 'Géolocalisation Précise',
    'demo.precise_desc': 'Navigation optimisée pour les villes congolaises',
    'demo.service_247': 'Service 24/7',
    'demo.service_247_desc': 'Disponible jour et nuit dans les 3 villes',
    'demo.guaranteed_quality': 'Qualité Garantie',
    'demo.guaranteed_desc': 'Chauffeurs vérifiés et services de qualité',
    'demo.get_started': 'Commencer Maintenant',
    'demo.learn_more': 'En Savoir Plus',
    
    // Partner Program
    'partner.title': 'Rejoignez l\'Écosystème',
    'partner.subtitle': 'Kwenda Taxi',
    'partner.description': 'Transformez votre passion du transport en une source de revenus stable. Rejoignez plus de 800 partenaires dans les 3 plus grandes villes du Congo.',
    'partner.program_badge': '🤝 Programme Partenaire Kwenda',
    'partner.become_partner': 'Devenir Partenaire',
    'partner.view_opportunities': 'Voir les Opportunités',
    'partner.choose_path': 'Choisissez Votre Voie',
    'partner.path_description': 'Plusieurs opportunités s\'offrent à vous selon vos moyens et objectifs',
    'partner.driver_partner': 'Chauffeur Partenaire',
    'partner.driver_desc': 'Rejoignez notre réseau de chauffeurs professionnels',
    'partner.driver_earnings': '150 000 - 400 000 CDF/mois',
    'partner.fleet_owner': 'Propriétaire de Flotte',
    'partner.fleet_desc': 'Louez vos véhicules et générez des revenus passifs',
    'partner.fleet_earnings': '50 000 - 150 000 CDF/véhicule/mois',
    'partner.express_delivery': 'Livreur Express',
    'partner.express_desc': 'Effectuez des livraisons rapides en moto',
    'partner.express_earnings': '80 000 - 250 000 CDF/mois',
    'partner.marketplace_merchant': 'Marchand Marketplace',
    'partner.merchant_desc': 'Vendez vos produits dans toute la RDC',
    'partner.merchant_earnings': 'Commission de 8% seulement',
    'partner.requirements': 'Prérequis',
    'partner.benefits': 'Avantages',
    'partner.apply_now': 'Postuler Maintenant',
    'partner.city_opportunities': 'Opportunités par Ville',
    'partner.attractive_income': 'Des revenus attractifs dans les 3 principales villes du Congo',
    'partner.active_partners': 'partenaires actifs',
    'partner.why_kwenda': 'Pourquoi Kwenda Taxi ?',
    'partner.supported_family': 'Plus qu\'un simple travail, rejoignez une famille de partenaires soutenus et valorisés',
    'partner.attractive_revenue': 'Revenus Attractifs',
    'partner.attractive_revenue_desc': 'Gagnez plus que la concurrence avec nos tarifs avantageux',
    'partner.complete_protection': 'Protection Complète',
    'partner.protection_desc': 'Assurance, support juridique et protection sociale',
    'partner.free_training': 'Formation Gratuite',
    'partner.training_desc': 'Programmes de formation continue et certification',
    'partner.total_flexibility': 'Flexibilité Totale',
    'partner.flexibility_desc': 'Travaillez quand vous voulez, où vous voulez',
    'partner.guaranteed_growth': 'Croissance Garantie',
    'partner.growth_desc': 'Opportunités d\'évolution et de promotion interne',
    'partner.recognition': 'Reconnaissance',
    'partner.recognition_desc': 'Système de récompenses et programme de fidélité',
    'partner.ready_to_start': 'Prêt à Commencer ?',
    'partner.join_today': 'Rejoignez-nous dès aujourd\'hui et commencez à générer des revenus dès la semaine prochaine',
    'partner.register_now': 'S\'inscrire Maintenant',
    'partner.contact_us': 'Nous Contacter',
    
    // Coverage Map
    'coverage.title': 'Carte de Couverture',
    'coverage.subtitle': 'Congo RDC',
    'coverage.description': 'Découvrez la disponibilité de nos services dans chaque zone de Kinshasa, Lubumbashi et Kolwezi avec des informations en temps réel.',
    'coverage.coverage_badge': '🗺️ Couverture Kwenda Taxi',
    'coverage.view_availability': 'Voir Disponibilité',
    'coverage.wait_time': 'Temps d\'Attente',
    'coverage.select_city': 'Sélectionnez Votre Ville',
    'coverage.detailed_coverage': 'Consultez la couverture détaillée par zone dans chaque ville',
    'coverage.available_vehicles': 'Véhicules Disponibles',
    'coverage.active_drivers': 'Chauffeurs Actifs',
    'coverage.global_coverage': 'Couverture Globale',
    'coverage.available_services': 'Services Disponibles',
    'coverage.zone_coverage': 'Couverture par Zone',
    'coverage.vehicles_count': 'véhicules',
    'coverage.average_time': 'Temps moyen',
    'coverage.status_legend': 'Légende des Statuts',
    'coverage.excellent_status': 'Excellent',
    'coverage.excellent_desc': '< 10 min d\'attente',
    'coverage.good_status': 'Bon',
    'coverage.good_desc': '10-15 min d\'attente',
    'coverage.average_status': 'Moyen',
    'coverage.average_desc': '15-20 min d\'attente',
    'coverage.limited_status': 'Limité',
    'coverage.limited_desc': '> 20 min d\'attente',
    'coverage.not_covered': 'Votre Zone n\'est Pas Encore Couverte ?',
    'coverage.expanding': 'Nous étendons constamment notre couverture. Laissez-nous vos coordonnées pour être notifié dès que nous arrivons dans votre quartier !',
    'coverage.request_extension': 'Demander une Extension',
    'coverage.become_partner': 'Devenir Partenaire',
    
    // Marketplace Enhanced
    'marketplace.hero_badge': '🛍️ Kwenda Marketplace',
    'marketplace.congo_marketplace': 'Marketplace Congo RDC',
    'marketplace.marketplace_desc': 'Découvrez les meilleurs produits du Congo avec livraison rapide dans les 3 grandes villes. Achetez local, supportez l\'économie congolaise !',
    'marketplace.search_placeholder': 'Rechercher des produits, marques, vendeurs...',
    'marketplace.browse_products': 'Parcourir les Produits',
    'marketplace.become_seller': 'Devenir Vendeur',
    'marketplace.all_products': 'Tous',
    'marketplace.electronics': 'Électronique',
    'marketplace.fashion': 'Mode',
    'marketplace.food': 'Alimentation',
    'marketplace.home': 'Maison',
    'marketplace.beauty': 'Beauté',
    'marketplace.popular_products': 'Produits Populaires',
    'marketplace.filters': 'Filtres',
    'marketplace.sort_by': 'Trier par',
    'marketplace.sort_popularity': 'Popularité',
    'marketplace.sort_price_asc': 'Prix croissant',
    'marketplace.sort_price_desc': 'Prix décroissant',
    'marketplace.sort_rating': 'Mieux notés',
    'marketplace.popular_badge': '🔥 Populaire',
    'marketplace.new_badge': '✨ Nouveau',
    'marketplace.premium_badge': '👑 Premium',
    'marketplace.discount_badge': 'Réduction',
    'marketplace.reviews_count': 'avis',
    'marketplace.add_to_cart_short': 'Ajouter',
    'marketplace.view_details': 'Voir',
    'marketplace.view_more': 'Voir Plus de Produits',
    'marketplace.trusted_sellers': 'Vendeurs de Confiance',
    'marketplace.verified_badge': 'Vérifié',
    'marketplace.sales_count': 'ventes',
    'marketplace.delivery_in_cities': 'Livraison dans 3 Villes',
    'marketplace.order_anywhere': 'Commandez depuis n\'importe où, nous livrons dans les principales villes du Congo',
    'marketplace.fast_delivery': 'Livraison rapide',
    'marketplace.secure_payment': 'Paiement sécurisé',
    'marketplace.explore_city': 'Explorer',
    'marketplace.sell_on_kwenda': 'Vendez vos Produits sur Kwenda Marketplace',
    'marketplace.seller_benefits': 'Rejoignez plus de 200 vendeurs qui font confiance à Kwenda pour développer leur business. Commission de seulement 8% avec livraison intégrée !',
    
    // Quartiers Kinshasa
    'location.gombe': 'Gombe',
    'location.kinshasa': 'Kinshasa',
    'location.lemba': 'Lemba',
    'location.ngaliema': 'Ngaliema',
    'location.matete': 'Matete',
    'location.masina': 'Masina',
    'location.ndjili': 'N\'djili',
    'location.kimbanseke': 'Kimbanseke',
    'location.kalamu': 'Kalamu',
    'location.limete': 'Limete',
    'location.kintambo': 'Kintambo',
    
    // Quartiers Lubumbashi
    'location.kenya': 'Kenya',
    'location.kampemba': 'Kampemba',
    'location.kamalondo': 'Kamalondo',
    'location.katuba': 'Katuba',
    'location.ruashi': 'Ruashi',
    'location.annexe': 'Annexe',
    
    // Quartiers Kolwezi
    'location.centre_ville': 'Centre-ville',
    'location.mutanda': 'Mutanda',
    'location.dilala': 'Dilala',
    'location.manika': 'Manika',
    
    // Payment
    'payment.mobile_money': 'Mobile Money',
    'payment.airtel': 'Airtel Money',
    'payment.mpesa': 'M-Pesa',
    'payment.orange': 'Orange Money',
    'payment.amount': 'Montant',
    'payment.phone': 'Numéro de téléphone',
    'payment.confirm': 'Confirmer le paiement',
    'payment.method': 'Méthode de paiement',
    'payment.cash': 'Espèces',
    'payment.wallet': 'Portefeuille',
    'payment.card': 'Carte',
    'payment.status.pending': 'En attente',
    'payment.status.success': 'Réussi',
    'payment.status.failed': 'Échoué',
    
    // Referral
    'referral.title': 'Système de Parrainage',
    'referral.code': 'Code de parrainage',
    'referral.invite': 'Inviter des amis',
    'referral.rewards': 'Récompenses',
    'referral.total_earned': 'Total gagné',
    'referral.share': 'Partager',
    'referral.copy_code': 'Copier le code',
    
    // Validation
    'validation.validation': 'Validation',
    'validation.status': 'Statut de validation',
    'validation.draft': 'Brouillon',
    'validation.pendingPartner': 'En attente partenaire',
    'validation.pendingAdmin': 'En attente admin',
    'validation.approved': 'Approuvé',
    'validation.rejected': 'Rejeté',
    'validation.comments': 'Commentaires',
    'validation.history': 'Historique',
    'validation.submitForValidation': 'Soumettre pour validation',
    'validation.submitted': 'Demande soumise',
    'validation.submittedDescription': 'Votre demande a été soumise avec succès',
    'validation.submitError': 'Erreur lors de la soumission',
    'validation.noRequest': 'Aucune demande trouvée',
    'validation.unknown': 'Inconnu',
    'validation.driverRequests': 'Demandes chauffeurs',
    'validation.noRequests': 'Aucune demande en attente',
    'validation.review': 'Examiner',
    'validation.reviewRequest': 'Examiner la demande',
    'validation.submittedAt': 'Soumis le',
    'validation.commentsRequired': 'Les commentaires sont obligatoires',
    'validation.commentsPlaceholder': 'Ajoutez vos commentaires de validation...',
    'validation.approve': 'Approuver',
    'validation.reject': 'Rejeter',
    'validation.success': 'Succès',
    'validation.approvedSuccess': 'Demande approuvée avec succès',
    'validation.rejectedSuccess': 'Demande rejetée avec succès',
    'validation.error': 'Erreur de validation',
    'validation.driver': 'Chauffeur',
    'validation.partner': 'Partenaire',
    'validation.admin': 'Administrateur',
    
    // Profile
    'profile.edit': 'Modifier le profil',
    'profile.name': 'Nom',
    'profile.email': 'Email',
    'profile.phone': 'Téléphone',
    'profile.address': 'Adresse',
    'profile.photo': 'Photo',
    'profile.verification': 'Vérification',
    'profile.documents': 'Documents',
    'profile.preferences': 'Préférences',
    'profile.language': 'Langue',
    'profile.notifications': 'Notifications',
    'profile.privacy': 'Confidentialité',
    
    // Home Interface
    'home.greeting.morning': 'Bonjour',
    'home.greeting.afternoon': 'Bon après-midi', 
    'home.greeting.evening': 'Bonsoir',
    'home.location.current': 'Position actuelle',
    'home.search.placeholder': 'Où allez-vous ?',
    'home.services.taxi': 'Taxi',
    'home.services.delivery': 'Livraison',
    'home.services.shopping': 'Shopping',
    'home.recent_places': 'Lieux récents',
    'home.no_recent_places': 'Aucun lieu récent',
    'home.recent_places_help': 'Commencez à rechercher des lieux pour les voir apparaître ici',
    'home.marketplace.trending': 'Tendances',
    'home.marketplace.view_all': 'Voir tout',
    'home.marketplace.popular': 'Populaire',
    'home.marketplace.discount': 'Réduction',
    'home.bottom_nav.home': 'Accueil',
    'home.bottom_nav.explore': 'Explorer',
    'home.bottom_nav.favorites': 'Favoris',
    'home.bottom_nav.activity': 'Activité',
    'home.bottom_nav.account': 'Compte',
    'home.place_type.home': 'Domicile',
    'home.place_type.work': 'Bureau',
    'home.place_type.recent': 'Récent',
    'home.notifications.unread': '3',
    
    // Activity & History
    'activity.history': 'Activité récente',
    'activity.no_bookings': 'Aucune course trouvée',
    'activity.loading': 'Chargement de l\'historique...',
    'activity.driver': 'Chauffeur',
    'activity.pickup': 'Prise en charge',
    'activity.dropoff': 'Destination',
    'activity.price': 'Prix',
    'activity.date': 'Date',
    'activity.status': 'Statut',
    'activity.rate': 'Noter',
    'activity.view_details': 'Voir détails',
    
    // Status labels
    'status.pending': 'En attente',
    'status.confirmed': 'Confirmé',
    'status.driver_assigned': 'Chauffeur assigné',
    'status.picked_up': 'Récupéré',
    'status.in_transit': 'En transit',
    'status.delivered': 'Livré',
    'status.completed': 'Terminé',
    'status.cancelled': 'Annulé',
    
    // Common
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.continue': 'Continuer',
    'common.back': 'Retour',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.confirm': 'Confirmer',
    'common.offline': 'Hors ligne',
    'common.retry': 'Réessayer',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.sort': 'Trier',
    'common.date': 'Date',
    'common.time': 'Heure',
    'common.status': 'Statut',
    'common.actions': 'Actions',
    'common.details': 'Détails',
    'common.close': 'Fermer',
    'common.select': 'Sélectionner',
    'common.upload': 'Télécharger',
    'common.download': 'Télécharger',
    'common.share': 'Partager',
    'common.copy': 'Copier',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.add': 'Ajouter',
    'common.remove': 'Retirer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.ok': 'OK',
    'common.done': 'Terminé',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.skip': 'Ignorer',
    'common.help': 'Aide',
    'common.about': 'À propos',
    'common.contact': 'Contact',
    'common.terms': 'Conditions',
    'common.privacy': 'Confidentialité',
    'common.user': 'Utilisateur',
    
    // Buttons
    'button.start_now': 'Commencer maintenant',
    'button.view_demo': 'Voir la démo',
    'button.book_now': 'Réserver maintenant',
    'button.download_app': 'Télécharger l\'App',
    'button.become_partner': 'Devenir Partenaire',
    'button.notify_me': 'Me notifier',
    'button.contact': 'Contacter',
    'button.close': 'Fermer',
    'button.refresh': 'Rafraîchir',
    'button.export': 'Exporter',
    
    // Messages & Toasts
    'message.success': 'Opération réussie',
    'message.error': 'Une erreur s\'est produite',
    'message.loading': 'Chargement en cours...',
    'message.no_data': 'Aucune donnée disponible',
    'message.try_again': 'Veuillez réessayer',
    
    // Forms
    'form.required': 'Ce champ est obligatoire',
    'form.invalid_email': 'Email invalide',
    'form.invalid_phone': 'Numéro de téléphone invalide',
    'form.password_min': 'Mot de passe trop court',
    'form.passwords_not_match': 'Les mots de passe ne correspondent pas',
    'form.submit': 'Envoyer',
    'form.reset': 'Réinitialiser',
    'form.placeholder.email': 'Entrez votre email',
    'form.placeholder.phone': 'Entrez votre numéro',
    'form.placeholder.password': 'Entrez votre mot de passe',
    'form.placeholder.name': 'Entrez votre nom',
    'form.placeholder.search': 'Rechercher...',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.transport': 'Transport',
    'nav.delivery': 'Delivery',
    'nav.marketplace': 'Marketplace',
    'nav.profile': 'Profile',
    'nav.history': 'History',
    'nav.payment': 'Payment',
    'nav.notifications': 'Notifications',
    'nav.settings': 'Settings',
    'nav.wallet': 'Wallet',
    'nav.earnings': 'Earnings',
    'nav.challenges': 'Challenges',
    'nav.support': 'Support',
    
    // Header & Navigation
    'header.services': 'Services',
    'header.advantages': 'Advantages',
    'header.contact': 'Contact',
    'header.client': 'Client',
    'header.driver': 'Driver',
    'header.admin': 'Admin',
    'header.download_app': 'Download App',
    'header.menu': 'Menu',
    
    // Hero Section
    'hero.innovation_excellence': 'Innovation & Excellence',
    'hero.kwenda_taxi': 'Kwenda Taxi',
    'hero.tagline': 'Smart transport for Kinshasa. Moto-taxi, car taxi, delivery and marketplace - all in one app adapted to DRC.',
    'hero.location': 'Kinshasa, Congo DRC',
    'hero.available_24_7': 'Available 24/7',
    'hero.start_now': 'Start Now',
    'hero.view_demo': 'View Demo',
    'hero.transport_types': 'Transport Types',
    'hero.customer_service': 'Customer Service',
    'hero.kwenda_pay': 'KwendaPay',
    'hero.made_in_rdc': '🇨🇩 Made in DRC',
    'hero.alt_text': 'Kwenda Taxi - Smart transport in Kinshasa',
    
    // Services Section
    'services.title': 'Our Services',
    'services.subtitle': 'A complete range of transport services adapted to all your needs in the Democratic Republic of Congo.',
    'services.vtc_standard': 'Standard VTC',
    'services.vtc_standard_desc': 'Comfortable and eco-friendly vehicles for your daily commutes.',
    'services.vtc_standard_price': 'From 3000 CDF',
    'services.vtc_standard_feat1': 'Recent vehicles',
    'services.vtc_standard_feat2': 'Air conditioning',
    'services.vtc_standard_feat3': 'Professional driver',
    'services.vtc_luxe': 'Luxury VTC',
    'services.vtc_luxe_desc': 'Limousines and high-end vehicles for your special events.',
    'services.vtc_luxe_price': 'From 8000 CDF',
    'services.vtc_luxe_feat1': 'Luxury vehicles',
    'services.vtc_luxe_feat2': 'Premium service',
    'services.vtc_luxe_feat3': 'Concierge',
    'services.shared_rides': 'Shared Rides',
    'services.shared_rides_desc': 'Save money by sharing your ride with other passengers.',
    'services.shared_rides_price': 'From 1500 CDF',
    'services.shared_rides_feat1': 'Reduced rates',
    'services.shared_rides_feat2': 'Eco-friendly',
    'services.shared_rides_feat3': 'Flexible booking',
    'services.moto_delivery': 'Moto Delivery',
    'services.moto_delivery_desc': 'Fast motorcycle delivery service for your packages and documents.',
    'services.moto_delivery_price': 'From 5000 CDF',
    'services.moto_delivery_feat1': 'Express delivery',
    'services.moto_delivery_feat2': 'Real-time tracking',
    'services.moto_delivery_feat3': 'Secure',
    'services.utility_vehicles': 'Utility Vehicles',
    'services.utility_vehicles_desc': 'Transport goods and moving with our utility vehicles.',
    'services.utility_vehicles_price': 'From 15000 CDF',
    'services.utility_vehicles_feat1': 'Spacious vehicles',
    'services.utility_vehicles_feat2': 'Loading assistance',
    'services.utility_vehicles_feat3': 'Insurance',
    'services.advance_booking': 'Advance Booking',
    'services.advance_booking_desc': 'Plan your trips in advance for your important appointments.',
    'services.advance_booking_price': 'No extra charge',
    'services.advance_booking_feat1': 'Time guarantee',
    'services.advance_booking_feat2': 'SMS confirmation',
    'services.advance_booking_feat3': 'Priority',
    'services.popular': '⭐ Popular',
    'services.book_now': 'Book Now',
    'services.cta_title': 'Ready to transform your transport experience?',
    'services.cta_subtitle': 'Join thousands of users who trust Kwenda for their daily commutes.',
    'services.download_app': 'Download App',
    'services.become_driver_partner': 'Become a Driver Partner',
    
    // Features Section
    'features.title_prefix': 'Why choose',
    'features.title_brand': 'Kwenda Taxi',
    'features.subtitle': 'A revolutionary transport experience adapted to the needs of the Congolese market.',
    'features.eco_fleet': 'Eco Fleet',
    'features.eco_fleet_desc': '1000 luxury vehicles respectful of the environment for clean and comfortable transport.',
    'features.smart_geolocation': 'Smart Geolocation',
    'features.smart_geolocation_desc': 'Real-time geolocation system for quick arrival and precise tracking of your trip.',
    'features.certified_drivers': 'Certified Drivers',
    'features.certified_drivers_desc': 'Professional drivers trained and verified for your safety and comfort.',
    'features.flexible_payments': 'Flexible Payments',
    'features.flexible_payments_desc': 'Mobile Money, bank cards, cash - all payment methods accepted.',
    'features.shared_rides': 'Shared Rides',
    'features.shared_rides_desc': 'Carpooling and group trips options to save money and reduce environmental impact.',
    'features.maximum_security': 'Maximum Security',
    'features.maximum_security_desc': 'Complete insurance, GPS tracking, rating system for your peace of mind.',
    'features.stats_vehicles': 'Vehicles Available',
    'features.stats_support': 'Customer Support',
    'features.stats_eco': 'Eco Vehicles',
    'features.stats_cities': 'Kinshasa & Lubumbashi',
    'features.alt_eco_car': 'Eco vehicles',
    'features.alt_mobile_app': 'Mobile application',
    'features.alt_professional_drivers': 'Professional drivers',
    
    // Footer
    'footer.services_vtc_standard': 'Standard VTC',
    'footer.services_vtc_luxe': 'Luxury VTC',
    'footer.services_shared_rides': 'Shared Rides',
    'footer.services_moto_delivery': 'Moto Delivery',
    'footer.services_utility': 'Utility Vehicles',
    'footer.company_mission': 'Our mission',
    'footer.company_team': 'Team',
    'footer.company_press': 'Press',
    'footer.company_partnerships': 'Partnerships',
    'footer.company_careers': 'Careers',
    'footer.support_contact': 'Contact',
    'footer.support_help': 'Help Center',
    'footer.support_faq': 'FAQ',
    'footer.support_privacy': 'Privacy Policy',
    'footer.support_terms': 'Terms of Use',
    'footer.app_download_title': 'Download Kwenda Taxi App',
    'footer.app_download_subtitle': 'Coming soon on iOS and Android',
    'footer.notify_ios': 'Notify me iOS',
    'footer.notify_android': 'Notify me Android',
    'footer.copyright': '© 2025 Kwenda Taxi. All rights reserved.',
    'footer.social_facebook': 'Facebook',
    'footer.social_twitter': 'Twitter',
    'footer.social_instagram': 'Instagram',
    'footer.social_linkedin': 'LinkedIn',
    
    // Delivery Interface
    'delivery.title': 'Delivery Service',
    'delivery.subtitle': 'Choose your delivery type',
    'delivery.flash': 'Flash Delivery',
    'delivery.flash_desc': 'Ultra-fast motorcycle delivery (30-60 min)',
    'delivery.flash_vehicle': 'Motorcycle',
    'delivery.flash_price': '5000 CDF + 500/km',
    'delivery.flash_feat1': 'Express delivery',
    'delivery.flash_feat2': 'Ideal for documents',
    'delivery.flash_feat3': 'Real-time tracking',
    'delivery.flex': 'Flex Delivery',
    'delivery.flex_desc': 'Standard economic delivery (2-4h)',
    'delivery.flex_vehicle': 'Car',
    'delivery.flex_price': '3000 CDF + 300/km',
    'delivery.flex_feat1': 'Affordable price',
    'delivery.flex_feat2': 'Medium packages',
    'delivery.flex_feat3': 'Reliable',
    'delivery.maxicharge': 'MaxiCharge',
    'delivery.maxicharge_desc': 'Large package delivery by truck (4-8h)',
    'delivery.maxicharge_vehicle': 'Truck',
    'delivery.maxicharge_price': '8000 CDF + 800/km',
    'delivery.maxicharge_feat1': 'Large volumes',
    'delivery.maxicharge_feat2': 'Loading assistance',
    'delivery.maxicharge_feat3': 'Insurance included',
    'delivery.step_service': 'Service',
    'delivery.step_addresses': 'Addresses',
    'delivery.step_confirmation': 'Confirmation',
    'delivery.pickup_location': 'Pickup location',
    'delivery.pickup_placeholder': 'Search pickup address...',
    'delivery.delivery_location': 'Delivery location',
    'delivery.delivery_placeholder': 'Search delivery address...',
    'delivery.package_description': 'Package description',
    'delivery.package_placeholder': 'Describe your package...',
    'delivery.recipient_name': 'Recipient name',
    'delivery.recipient_phone': 'Recipient phone',
    'delivery.special_instructions': 'Special instructions',
    'delivery.instructions_placeholder': 'Instructions for driver...',
    'delivery.next': 'Next',
    'delivery.previous': 'Previous',
    'delivery.confirm_order': 'Confirm Order',
    'delivery.cancel': 'Cancel',
    'delivery.step': 'Step',
    'delivery.of': 'of',
    'delivery.loading': 'Loading...',
    'delivery.search_locations': 'Search locations...',
    'delivery.use_current_location': 'Use my current location',
    'delivery.estimated_price': 'Estimated price',
    'delivery.total_distance': 'Total distance',
    'delivery.estimated_time': 'Estimated time',
    'delivery.order_summary': 'Order summary',
    'delivery.selected_service': 'Selected service',
    'delivery.contact_details': 'Contact details',
    'delivery.order_details': 'Order details',
    
    // Location Search
    'location.search_placeholder': 'Search a location...',
    'location.current_location': 'Current location',
    'location.no_results': 'No results found',
    'location.searching': 'Searching...',
    'location.select_location': 'Select this location',
    'location.approximate': 'Approximate position',
    'location.unavailable': 'Location unavailable',
    'location.gps_unavailable': 'GPS unavailable',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Sign Up',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.phone': 'Phone',
    'auth.forgot_password': 'Forgot Password',
    'auth.reset_password': 'Reset',
    'auth.verify_phone': 'Verify Phone',
    
    // Transport Congo RDC
    'transport.book': 'Book',
    'transport.pickup': 'Pickup Point',
    'transport.destination': 'Destination',
    'transport.vehicle': 'Vehicle',
    'transport.price': 'Price',
    'transport.time': 'Estimated Time',
    'transport.taxi_bus': 'Taxi-bus',
    'transport.moto_taxi': 'Moto-taxi',
    'transport.taxi_voiture': 'Car Taxi',
    'transport.bus_transco': 'Transco Bus',
    'transport.status.pending': 'Pending',
    'transport.status.confirmed': 'Confirmed',
    'transport.status.en_route': 'En Route',
    'transport.status.arrived': 'Arrived',
    'transport.status.completed': 'Completed',
    'transport.status.cancelled': 'Cancelled',
    'transport.driver_arriving': 'Driver Approaching',
    'transport.eta': 'Estimated Arrival',
    
    // Package types
    'package.small': 'Small',
    'package.small_desc': 'Documents, smartphone, jewelry',
    'package.small_weight': 'Up to 2kg',
    'package.medium': 'Medium',
    'package.medium_desc': 'Clothes, books, electronics',
    'package.medium_weight': '2-10kg',
    'package.large': 'Large',
    'package.large_desc': 'Appliances, furniture',
    'package.large_weight': '10-50kg',
    'package.extra_large': 'Extra Large',
    'package.extra_large_desc': 'Refrigerator, mattress',
    'package.extra_large_weight': 'Over 50kg',
    
    // Marketplace
    'marketplace.title': 'Marketplace',
    'marketplace.browse': 'Browse',
    'marketplace.chat': 'Chat',
    'marketplace.admin': 'Admin',
    'marketplace.products': 'Products',
    'marketplace.categories': 'Categories',
    'marketplace.cart': 'Cart',
    'marketplace.favorites': 'Favorites',
    'marketplace.orders': 'Orders',
    'marketplace.sell': 'Sell',
    'marketplace.buy': 'Buy',
    'marketplace.add_to_cart': 'Add to Cart',
    'marketplace.checkout': 'Checkout',
    'marketplace.price': 'Price',
    'marketplace.description': 'Description',
    'marketplace.seller': 'Seller',
    'marketplace.rating': 'Rating',
    'marketplace.reviews': 'Reviews',
    'marketplace.stock': 'Stock',
    'marketplace.category': 'Category',
    'marketplace.noConversations': 'No conversations',
    'marketplace.startChatting': 'Start chatting with sellers to see your conversations here.',
    'marketplace.all_trends': 'All trends',
    'marketplace.trending_products': 'Trending products',
    'marketplace.back_to_trends': 'Back to trends',
    'marketplace.back_to_marketplace': 'Back to marketplace',
    
    // Driver
    'driver.dashboard': 'Dashboard',
    'driver.earnings': 'Earnings',
    'driver.trips': 'Trips',
    'driver.status': 'Status',
    'driver.online': 'Online',
    'driver.offline': 'Offline',
    'driver.available': 'Available',
    'driver.busy': 'Busy',
    'driver.accept_trip': 'Accept Trip',
    'driver.decline_trip': 'Decline Trip',
    'driver.start_trip': 'Start Trip',
    'driver.complete_trip': 'Complete Trip',
    'driver.vehicle_info': 'Vehicle Info',
    'driver.license': 'License',
    'driver.rating': 'Rating',
    'driver.total_trips': 'Total Trips',
    'driver.vehicle': 'Vehicle',
    'driver.vehicleType': 'Vehicle Type',
    'driver.vehicleModel': 'Model',
    'driver.vehiclePlate': 'License Plate',
    'driver.licenseNumber': 'License',
    'driver.insuranceNumber': 'Insurance',
    
    // Wallet
    'wallet.balance': 'Balance',
    'wallet.topup': 'Top Up',
    'wallet.withdraw': 'Withdraw',
    'wallet.history': 'History',
    'wallet.transaction': 'Transaction',
    'wallet.amount': 'Amount',
    'wallet.fee': 'Fee',
    'wallet.total': 'Total',
    'wallet.pending': 'Pending',
    'wallet.completed': 'Completed',
    'wallet.failed': 'Failed',
    
    // Notifications
    'notification.new_trip': 'New trip available',
    'notification.trip_accepted': 'Trip accepted',
    'notification.driver_arrived': 'Driver arrived',
    'notification.trip_started': 'Trip started',
    'notification.trip_completed': 'Trip completed',
    'notification.payment_received': 'Payment received',
    'notification.promotion': 'Special promotion',
    'notification.system': 'System notification',
    
    // Cities
    'city.kinshasa': 'Kinshasa',
    'city.lubumbashi': 'Lubumbashi', 
    'city.kolwezi': 'Kolwezi',
    'city.abidjan': 'Abidjan',
    
    // Kinshasa Districts
    'location.gombe': 'Gombe',
    'location.kinshasa': 'Kinshasa',
    'location.lemba': 'Lemba',
    'location.ngaliema': 'Ngaliema',
    'location.matete': 'Matete',
    'location.masina': 'Masina',
    'location.ndjili': 'N\'djili',
    'location.kimbanseke': 'Kimbanseke',
    'location.kalamu': 'Kalamu',
    'location.limete': 'Limete',
    'location.kintambo': 'Kintambo',
    
    // Lubumbashi Districts
    'location.kenya': 'Kenya',
    'location.kampemba': 'Kampemba',
    'location.kamalondo': 'Kamalondo',
    'location.katuba': 'Katuba',
    'location.ruashi': 'Ruashi',
    'location.annexe': 'Annexe',
    
    // Kolwezi Districts
    'location.centre_ville': 'City Center',
    'location.mutanda': 'Mutanda',
    'location.dilala': 'Dilala',
    'location.manika': 'Manika',
    
    // Payment
    'payment.mobile_money': 'Mobile Money',
    'payment.airtel': 'Airtel Money',
    'payment.mpesa': 'M-Pesa',
    'payment.orange': 'Orange Money',
    'payment.amount': 'Amount',
    'payment.phone': 'Phone Number',
    'payment.confirm': 'Confirm Payment',
    'payment.method': 'Payment Method',
    'payment.cash': 'Cash',
    'payment.wallet': 'Wallet',
    'payment.card': 'Card',
    'payment.status.pending': 'Pending',
    'payment.status.success': 'Success',
    'payment.status.failed': 'Failed',
    
    // Referral
    'referral.title': 'Referral System',
    'referral.code': 'Referral Code',
    'referral.invite': 'Invite Friends',
    'referral.rewards': 'Rewards',
    'referral.total_earned': 'Total Earned',
    'referral.share': 'Share',
    'referral.copy_code': 'Copy Code',
    
    // Validation
    'validation.validation': 'Validation',
    'validation.status': 'Validation Status',
    'validation.draft': 'Draft',
    'validation.pendingPartner': 'Pending Partner',
    'validation.pendingAdmin': 'Pending Admin',
    'validation.approved': 'Approved',
    'validation.rejected': 'Rejected',
    'validation.comments': 'Comments',
    'validation.history': 'History',
    'validation.submitForValidation': 'Submit for Validation',
    'validation.submitted': 'Request Submitted',
    'validation.submittedDescription': 'Your request has been submitted successfully',
    'validation.submitError': 'Submission Error',
    'validation.noRequest': 'No request found',
    'validation.unknown': 'Unknown',
    'validation.driverRequests': 'Driver Requests',
    'validation.noRequests': 'No pending requests',
    'validation.review': 'Review',
    'validation.reviewRequest': 'Review Request',
    'validation.submittedAt': 'Submitted on',
    'validation.commentsRequired': 'Comments are required',
    'validation.commentsPlaceholder': 'Add your validation comments...',
    'validation.approve': 'Approve',
    'validation.reject': 'Reject',
    'validation.success': 'Success',
    'validation.approvedSuccess': 'Request approved successfully',
    'validation.rejectedSuccess': 'Request rejected successfully',
    'validation.error': 'Validation Error',
    'validation.driver': 'Driver',
    'validation.partner': 'Partner',
    'validation.admin': 'Administrator',
    
    // Profile
    'profile.edit': 'Edit Profile',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.address': 'Address',
    'profile.photo': 'Photo',
    'profile.verification': 'Verification',
    'profile.documents': 'Documents',
    'profile.preferences': 'Preferences',
    'profile.language': 'Language',
    'profile.notifications': 'Notifications',
    'profile.privacy': 'Privacy',
    
    // Home Interface
    'home.greeting.morning': 'Good morning',
    'home.greeting.afternoon': 'Good afternoon', 
    'home.greeting.evening': 'Good evening',
    'home.location.current': 'Current location',
    'home.search.placeholder': 'Where are you going?',
    'home.services.taxi': 'Taxi',
    'home.services.delivery': 'Delivery',
    'home.services.shopping': 'Shopping',
    'home.recent_places': 'Recent places',
    'home.no_recent_places': 'No recent places',
    'home.recent_places_help': 'Start searching for places to see them appear here',
    'home.marketplace.trending': 'Trending',
    'home.marketplace.view_all': 'View All',
    'home.marketplace.popular': 'Popular',
    'home.marketplace.discount': 'Discount',
    'home.bottom_nav.home': 'Home',
    'home.bottom_nav.explore': 'Explore',
    'home.bottom_nav.favorites': 'Favorites',
    'home.bottom_nav.activity': 'Activity',
    'home.bottom_nav.account': 'Account',
    'home.place_type.home': 'Home',
    'home.place_type.work': 'Work',
    'home.place_type.recent': 'Recent',
    'home.notifications.unread': '3',
    
    // Activity & History
    'activity.history': 'Recent Activity',
    'activity.no_bookings': 'No trips found',
    'activity.loading': 'Loading history...',
    'activity.driver': 'Driver',
    'activity.pickup': 'Pickup',
    'activity.dropoff': 'Dropoff',
    'activity.price': 'Price',
    'activity.date': 'Date',
    'activity.status': 'Status',
    'activity.rate': 'Rate',
    'activity.view_details': 'View Details',
    
    // Status labels
    'status.pending': 'Pending',
    'status.confirmed': 'Confirmed',
    'status.driver_assigned': 'Driver Assigned',
    'status.picked_up': 'Picked Up',
    'status.in_transit': 'In Transit',
    'status.delivered': 'Delivered',
    'status.completed': 'Completed',
    'status.cancelled': 'Cancelled',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.continue': 'Continue',
    'common.back': 'Back',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    'common.offline': 'Offline',
    'common.retry': 'Retry',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.details': 'Details',
    'common.close': 'Close',
    'common.select': 'Select',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.share': 'Share',
    'common.copy': 'Copy',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.done': 'Done',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.skip': 'Skip',
    'common.help': 'Help',
    'common.about': 'About',
    'common.contact': 'Contact',
    'common.terms': 'Terms',
    'common.privacy': 'Privacy',
    'common.user': 'User',
    
    // Buttons
    'button.start_now': 'Start Now',
    'button.view_demo': 'View Demo',
    'button.book_now': 'Book Now',
    'button.download_app': 'Download App',
    'button.become_partner': 'Become Partner',
    'button.notify_me': 'Notify Me',
    'button.contact': 'Contact',
    'button.close': 'Close',
    'button.refresh': 'Refresh',
    'button.export': 'Export',
    
    // Messages & Toasts
    'message.success': 'Operation successful',
    'message.error': 'An error occurred',
    'message.loading': 'Loading...',
    'message.no_data': 'No data available',
    'message.try_again': 'Please try again',
    
    // Forms
    'form.required': 'This field is required',
    'form.invalid_email': 'Invalid email',
    'form.invalid_phone': 'Invalid phone number',
    'form.password_min': 'Password too short',
    'form.passwords_not_match': 'Passwords do not match',
    'form.submit': 'Submit',
    'form.reset': 'Reset',
    'form.placeholder.email': 'Enter your email',
    'form.placeholder.phone': 'Enter your number',
    'form.placeholder.password': 'Enter your password',
    'form.placeholder.name': 'Enter your name',
    'form.placeholder.search': 'Search...',
  },
  ln: {
    // Navigation
    'nav.home': 'Bandako',
    'nav.transport': 'Transport',
    'nav.delivery': 'Livraison',
    'nav.marketplace': 'Zando',
    'nav.profile': 'Profil',
    'nav.history': 'Makambo ya kala',
    'nav.payment': 'Kofuta',
    'nav.notifications': 'Ba notifications',
    'nav.settings': 'Ba paramètres',
    
    // Home Interface
    'home.greeting.morning': 'Mbote ya ntongo',
    'home.greeting.afternoon': 'Mbote ya midi',
    'home.greeting.evening': 'Mbote ya mpokwa',
    'home.location.current': 'Esika ozo wana',
    'home.search.placeholder': 'Okokende wapi?',
    'home.services.taxi': 'Taxi',
    'home.services.delivery': 'Livraison',
    'home.services.shopping': 'Kosomba',
    'home.recent_places': 'Bisika ya kala',
    'home.no_recent_places': 'Bisika ya kala ezali te',
    'home.recent_places_help': 'Bandela koluka bisika mpo emona awa',
    'home.marketplace.trending': 'Oyo ezali koleka',
    'home.marketplace.view_all': 'Kotala nyonso',
    'home.marketplace.popular': 'Oyo balingi mingi',
    'home.marketplace.discount': 'Kokitisa ntalo',
    'home.bottom_nav.home': 'Bandako',
    'home.bottom_nav.explore': 'Koluka',
    'home.bottom_nav.favorites': 'Oyo nalingi',
    'home.bottom_nav.activity': 'Makambo',
    'home.bottom_nav.account': 'Compte',
    'home.place_type.home': 'Ndako',
    'home.place_type.work': 'Mosala',
    'home.place_type.recent': 'Ya kala',
    'home.notifications.unread': '3',

    // Activity & History
    'activity.history': 'Makambo ya kala',
    'activity.no_bookings': 'Mobembo ya kala ezali te',
    'activity.loading': 'Eza kocharger makambo ya kala...',
    'activity.driver': 'Motambolisi',
    'activity.pickup': 'Esika ya kokende',
    'activity.dropoff': 'Esika ya kokitisa',
    'activity.price': 'Ntalo',
    'activity.date': 'Mokolo',
    'activity.status': 'Ndenge ezali',
    'activity.rate': 'Kopesa note',
    'activity.view_details': 'Kotala malamu',

    // Delivery
    'delivery.mode.flash': 'Flash',
    'delivery.mode.cargo': 'Cargo',
    
    // Transport Congo RDC
    'transport.book': 'Kokanisa',
    'transport.pickup': 'Esika ya kokende',
    'transport.destination': 'Esika ya kokoma',
    'transport.vehicle': 'Motuka',
    'transport.price': 'Ntalo',
    'transport.time': 'Ntango ya kokende',
    'transport.taxi_bus': 'Taxi-bus',
    'transport.moto_taxi': 'Moto-taxi',
    'transport.taxi_voiture': 'Taxi motuka',
    'transport.bus_transco': 'Bus Transco',
    
    // Cities & Locations
    'city.kinshasa': 'Kinshasa',
    'city.lubumbashi': 'Lubumbashi',
    'city.kolwezi': 'Kolwezi',
    'location.gombe': 'Gombe',
    'location.kinshasa': 'Kinshasa',
    'location.lemba': 'Lemba',
    'location.ngaliema': 'Ngaliema',
    'location.matete': 'Matete',
    'location.masina': 'Masina',
    'location.ndjili': 'N\'djili',
    'location.kimbanseke': 'Kimbanseke',
    
    // Payment
    'payment.mobile_money': 'Mbongo ya téléphone',
    'payment.airtel': 'Airtel Money',
    'payment.mpesa': 'M-Pesa',
    'payment.orange': 'Orange Money',
    'payment.amount': 'Mbongo',
    'payment.phone': 'Numéro ya téléphone',
    'payment.confirm': 'Kondima kofuta',
    
    // Referral
    'referral.title': 'Système ya kopesa baninga',
    'referral.code': 'Code ya kopesa',
    'referral.invite': 'Kobenga baninga',
    'referral.rewards': 'Lifuti',
    'referral.total_earned': 'Mbongo nyonso ozongi',
    
    // Common
    'common.save': 'Kobomba',
    'common.cancel': 'Kotika',
    'common.continue': 'Kokoba',
    'common.back': 'Kozonga',
    'common.loading': 'Eza kochargé...',
    'common.error': 'Libunga',
    'common.success': 'Elongi',
    'common.confirm': 'Kondima',
    'common.offline': 'Internet ezali te',
    'common.retry': 'Komeka lisusu',
    'common.search': 'Koluka',
    'common.user': 'Mosaleli',
  },
  kg: { // Kikongo
    // Navigation
    'nav.home': 'Nzo',
    'nav.transport': 'Transport',
    'nav.delivery': 'Livraison',
    'nav.marketplace': 'Zando',
    'nav.profile': 'Profil',
    'nav.history': 'Makambu ma kala',
    'nav.payment': 'Kufuta',
    'nav.notifications': 'Bisalu',
    'nav.settings': 'Paramètres',
    
    // Home Interface
    'home.greeting.morning': 'Nsuka ya nsuka',
    'home.greeting.afternoon': 'Nsuka ya mbazi',
    'home.greeting.evening': 'Nsuka ya mpimpa',
    'home.location.current': 'Fulu yina usimbama',
    'home.search.placeholder': 'Kuna ukenda?',
    'home.services.taxi': 'Taxi',
    'home.services.delivery': 'Livraison',
    'home.services.shopping': 'Kusuma',
    'home.recent_places': 'Mafulu ma kala',
    'home.no_recent_places': 'Mafulu ma kala mafulu ko',
    'home.recent_places_help': 'Bandika kulonga mafulu mpo mona vava',
    'home.marketplace.trending': 'Oyo yina kuzola',
    'home.marketplace.view_all': 'Mona moso',
    'home.marketplace.popular': 'Oyo bantu bazeyi mingi',
    'home.marketplace.discount': 'Kukenga ntalu',
    'home.bottom_nav.home': 'Nzo',
    'home.bottom_nav.explore': 'Kulonga',
    'home.bottom_nav.favorites': 'Oyo nazoli',
    'home.bottom_nav.activity': 'Makambu',
    'home.bottom_nav.account': 'Compte',
    'home.place_type.home': 'Nzo',
    'home.place_type.work': 'Kisalu',
    'home.place_type.recent': 'Ya kala',
    'home.notifications.unread': '3',

    // Activity & History
    'activity.history': 'Makambu ma kala',
    'activity.no_bookings': 'Mayenda ma kala mafulu ko',
    'activity.loading': 'Yina ku charger makambu ma kala...',
    'activity.driver': 'Mutambulisi',
    'activity.pickup': 'Fulu ya kutuka',
    'activity.dropoff': 'Fulu ya kutula',
    'activity.price': 'Ntalu',
    'activity.date': 'Lumbu',
    'activity.status': 'Ndenge yina vuandi',
    'activity.rate': 'Kuvana note',
    'activity.view_details': 'Mona mayela',

    // Delivery
    'delivery.mode.flash': 'Flash',
    'delivery.mode.cargo': 'Cargo',
    
    // Transport Congo RDC
    'transport.book': 'Kukanisa',
    'transport.pickup': 'Fulu ya kutuka',
    'transport.destination': 'Fulu ya kukenda',
    'transport.vehicle': 'Motuka',
    'transport.price': 'Ntalu',
    'transport.time': 'Thangu ya kukenda',
    'transport.taxi_bus': 'Taxi-bus',
    'transport.moto_taxi': 'Moto-taxi',
    'transport.taxi_voiture': 'Taxi motuka',
    'transport.bus_transco': 'Bus Transco',
    
    // Cities & Locations
    'city.kinshasa': 'Kinshasa',
    'city.lubumbashi': 'Lubumbashi',
    'city.kolwezi': 'Kolwezi',
    'location.gombe': 'Gombe',
    'location.kinshasa': 'Kinshasa',
    'location.lemba': 'Lemba',
    'location.ngaliema': 'Ngaliema',
    'location.matete': 'Matete',
    'location.masina': 'Masina',
    'location.ndjili': 'N\'djili',
    'location.kimbanseke': 'Kimbanseke',
    
    // Payment
    'payment.mobile_money': 'Nkutu za telephone',
    'payment.airtel': 'Airtel Money',
    'payment.mpesa': 'M-Pesa',
    'payment.orange': 'Orange Money',
    'payment.amount': 'Nkutu',
    'payment.phone': 'Numero ya telephone',
    'payment.confirm': 'Kundima kufuta',
    
    // Common
    'common.save': 'Kubika',
    'common.cancel': 'Kutika',
    'common.continue': 'Kukoba',
    'common.back': 'Kuvutuka',
    'common.loading': 'Yina ku charge...',
    'common.error': 'Nkama',
    'common.success': 'Malonga',
    'common.confirm': 'Kundima',
    'common.offline': 'Internet yafulu ko',
    'common.retry': 'Kusolula diaka',
    'common.search': 'Kulonga',
    'common.user': 'Nkento',
  },
  lua: { // Tshiluba
    // Navigation
    'nav.home': 'Muetu',
    'nav.transport': 'Transport',
    'nav.delivery': 'Livraison',
    'nav.marketplace': 'Mubanda',
    'nav.profile': 'Profil',
    'nav.history': 'Bintu bia kala',
    'nav.payment': 'Kulipa',
    'nav.notifications': 'Makambu',
    'nav.settings': 'Paramètres',
    
    // Home Interface
    'home.greeting.morning': 'Wa muana muyanda',
    'home.greeting.afternoon': 'Wa diba',
    'home.greeting.evening': 'Wa manshi',
    'home.location.current': 'Pahali panu udi',
    'home.search.placeholder': 'Oya kuya kudi?',
    'home.services.taxi': 'Taxi',
    'home.services.delivery': 'Livraison',
    'home.services.shopping': 'Kusuma',
    'home.recent_places': 'Mahali ma kala',
    'home.no_recent_places': 'Mahali ma kala mabileko',
    'home.recent_places_help': 'Tandisha kulolesha mahali mpo mona apa',
    'home.marketplace.trending': 'Bintu bilenga',
    'home.marketplace.view_all': 'Bona byonso',
    'home.marketplace.popular': 'Bintu bantu bayanda',
    'home.marketplace.discount': 'Kukenga bei',
    'home.bottom_nav.home': 'Muetu',
    'home.bottom_nav.explore': 'Kulolesha',
    'home.bottom_nav.favorites': 'Bintu ndiyanda',
    'home.bottom_nav.activity': 'Bintu',
    'home.bottom_nav.account': 'Compte',
    'home.place_type.home': 'Muetu',
    'home.place_type.work': 'Mulimu',
    'home.place_type.recent': 'Wa kala',
    'home.notifications.unread': '3',

    // Activity & History
    'activity.history': 'Bintu bia kala',
    'activity.no_bookings': 'Mayendo ma kala mabileko',
    'activity.loading': 'Tukucharge bintu bia kala...',
    'activity.driver': 'Mutambulisha',
    'activity.pickup': 'Pahali pakutanga',
    'activity.dropoff': 'Pahali pakutula',
    'activity.price': 'Bei',
    'activity.date': 'Lumingu',
    'activity.status': 'Cishi',
    'activity.rate': 'Kuapa note',
    'activity.view_details': 'Bona makambu',

    // Delivery
    'delivery.mode.flash': 'Flash',
    'delivery.mode.cargo': 'Cargo',
    
    // Transport Congo RDC
    'transport.book': 'Kubanda',
    'transport.pickup': 'Mahali pakutanga',
    'transport.destination': 'Mahali pakufika',
    'transport.vehicle': 'Motuka',
    'transport.price': 'Bei',
    'transport.time': 'Nako ya kuya',
    'transport.taxi_bus': 'Taxi-bus',
    'transport.moto_taxi': 'Moto-taxi',
    'transport.taxi_voiture': 'Taxi motuka',
    'transport.bus_transco': 'Bus Transco',
    
    // Cities & Locations
    'city.kinshasa': 'Kinshasa',
    'city.lubumbashi': 'Lubumbashi',
    'city.kolwezi': 'Kolwezi',
    'location.gombe': 'Gombe',
    'location.kinshasa': 'Kinshasa',
    'location.lemba': 'Lemba',
    'location.ngaliema': 'Ngaliema',
    'location.matete': 'Matete',
    'location.masina': 'Masina',
    'location.ndjili': 'N\'djili',
    'location.kimbanseke': 'Kimbanseke',
    
    // Payment
    'payment.mobile_money': 'Mbongo ya telephone',
    'payment.airtel': 'Airtel Money',
    'payment.mpesa': 'M-Pesa',
    'payment.orange': 'Orange Money',
    'payment.amount': 'Mbongo',
    'payment.phone': 'Numero ya telephone',
    'payment.confirm': 'Kutambula kulipa',
    
    // Common
    'common.save': 'Kubika',
    'common.cancel': 'Kuleka',
    'common.continue': 'Kuendelea',
    'common.back': 'Kubuya',
    'common.loading': 'Nkucharge...',
    'common.error': 'Nshimu',
    'common.success': 'Malonga',
    'common.confirm': 'Kutambula',
    'common.offline': 'Internet ibi',
    'common.retry': 'Kusolola',
    'common.search': 'Kulolesha',
    'common.user': 'Muntu',
  },
  sw: { // Swahili
    // Navigation
    'nav.home': 'Nyumbani',
    'nav.transport': 'Usafiri',
    'nav.delivery': 'Utoaji',
    'nav.marketplace': 'Soko',
    'nav.profile': 'Profili',
    'nav.history': 'Historia',
    'nav.payment': 'Malipo',
    'nav.notifications': 'Arifa',
    'nav.settings': 'Mipangilio',
    
    // Home Interface
    'home.greeting.morning': 'Habari za asubuhi',
    'home.greeting.afternoon': 'Habari za mchana',
    'home.greeting.evening': 'Habari za jioni',
    'home.location.current': 'Mahali upo sasa',
    'home.search.placeholder': 'Unaenda wapi?',
    'home.services.taxi': 'Taxi',
    'home.services.delivery': 'Utoaji',
    'home.services.shopping': 'Ununuzi',
    'home.recent_places': 'Maeneo ya hivi karibuni',
    'home.no_recent_places': 'Hakuna maeneo ya hivi karibuni',
    'home.recent_places_help': 'Anza kutafuta maeneo ili yaonekane hapa',
    'home.marketplace.trending': 'Kinachojazwa',
    'home.marketplace.view_all': 'Ona Vyote',
    'home.marketplace.popular': 'Maarufu',
    'home.marketplace.discount': 'Punguzo',
    'home.bottom_nav.home': 'Nyumbani',
    'home.bottom_nav.explore': 'Gundua',
    'home.bottom_nav.favorites': 'Vipendwa',
    'home.bottom_nav.activity': 'Shughuli',
    'home.bottom_nav.account': 'Akaunti',
    'home.place_type.home': 'Nyumbani',
    'home.place_type.work': 'Kazini',
    'home.place_type.recent': 'Hivi karibuni',
    'home.notifications.unread': '3',

    // Activity & History
    'activity.history': 'Shughuli za hivi karibuni',
    'activity.no_bookings': 'Hakuna safari zilizopatikana',
    'activity.loading': 'Inapakia historia...',
    'activity.driver': 'Dereva',
    'activity.pickup': 'Kuchukua',
    'activity.dropoff': 'Kuangusha',
    'activity.price': 'Bei',
    'activity.date': 'Tarehe',
    'activity.status': 'Hali',
    'activity.rate': 'Tathmini',
    'activity.view_details': 'Ona Maelezo',

    // Delivery
    'delivery.mode.flash': 'Flash',
    'delivery.mode.cargo': 'Cargo',
    
    // Transport Congo RDC
    'transport.book': 'Kuweka',
    'transport.pickup': 'Mahali pa kuchukua',
    'transport.destination': 'Unakoenda',
    'transport.vehicle': 'Gari',
    'transport.price': 'Bei',
    'transport.time': 'Muda wa kufikia',
    'transport.taxi_bus': 'Basi-taxi',
    'transport.moto_taxi': 'Piki-piki',
    'transport.taxi_voiture': 'Taxi gari',
    'transport.bus_transco': 'Basi Transco',
    
    // Cities & Locations
    'city.kinshasa': 'Kinshasa',
    'city.lubumbashi': 'Lubumbashi',
    'city.kolwezi': 'Kolwezi',
    'location.gombe': 'Gombe',
    'location.kinshasa': 'Kinshasa',
    'location.lemba': 'Lemba',
    'location.ngaliema': 'Ngaliema',
    'location.matete': 'Matete',
    'location.masina': 'Masina',
    'location.ndjili': 'N\'djili',
    'location.kimbanseke': 'Kimbanseke',
    
    // Payment
    'payment.mobile_money': 'Pesa za simu',
    'payment.airtel': 'Airtel Money',
    'payment.mpesa': 'M-Pesa',
    'payment.orange': 'Orange Money',
    'payment.amount': 'Kiasi',
    'payment.phone': 'Nambari ya simu',
    'payment.confirm': 'Thibitisha malipo',
    
    // Common
    'common.save': 'Hifadhi',
    'common.cancel': 'Ghairi',
    'common.continue': 'Endelea',
    'common.back': 'Rudi',
    'common.loading': 'Inapakia...',
    'common.error': 'Kosa',
    'common.success': 'Mafanikio',
    'common.confirm': 'Thibitisha',
    'common.offline': 'Bila mtandao',
    'common.retry': 'Jaribu tena',
    'common.search': 'Tafuta',
    'common.user': 'Mtumiaji',

    // Validation
    'validation.validation': 'Uthibitisho',
    'validation.status': 'Hali ya uthibitisho',
    'validation.draft': 'Rasimu',
    'validation.pendingPartner': 'Inasubiri mshirika',
    'validation.pendingAdmin': 'Inasubiri msimamizi',
    'validation.approved': 'Imeidhinishwa',
    'validation.rejected': 'Imekataliwa',
    'validation.comments': 'Maoni',
    'validation.history': 'Historia',
    'validation.submitForValidation': 'Wasilisha kwa uthibitisho',
    'validation.submitted': 'Ombi limewasilishwa',
    'validation.submittedDescription': 'Ombi lako limewasilishwa kwa mafanikio',
    'validation.submitError': 'Hitilafu katika kuwasilisha',
    'validation.noRequest': 'Hakuna ombi lililopatikana',
    'validation.unknown': 'Haijulikani',
    'validation.driverRequests': 'Maombi ya madereva',
    'validation.noRequests': 'Hakuna maombi yanayosubiri',
    'validation.review': 'Kagua',
    'validation.reviewRequest': 'Kagua ombi',
    'validation.submittedAt': 'Imewasilishwa mnamo',
    'validation.commentsRequired': 'Maoni yanahitajika',
    'validation.commentsPlaceholder': 'Ongeza maoni yako ya uthibitisho...',
    'validation.approve': 'Idhinisha',
    'validation.reject': 'Kataa',
    'validation.success': 'Mafanikio',
    'validation.approvedSuccess': 'Ombi limeidhinishwa kwa mafanikio',
    'validation.rejectedSuccess': 'Ombi limekataliwa kwa mafanikio',
    'validation.error': 'Hitilafu ya uthibitisho',
    'validation.driver': 'Dereva',
    'validation.partner': 'Mshirika',
    'validation.admin': 'Msimamizi',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('kwenda-language');
    return (saved as Language) || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('kwenda-language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations.fr[key] || key;
  };

  const formatCurrency = (amount: number, currency: 'CDF' | 'USD' = 'CDF'): string => {
    if (currency === 'CDF') {
      return new Intl.NumberFormat('fr-CD', {
        minimumFractionDigits: 0,
        maximumFractionDigits: 0
      }).format(amount) + ' CDF';
    } else {
      return new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD'
      }).format(amount);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, formatCurrency }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};