import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'fr' | 'en' | 'ln' | 'kg' | 'lua' | 'sw';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  formatCurrency: (amount: number, currency?: 'CDF' | 'USD') => string;
}

const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.transport': 'Transport',
    'nav.delivery': 'Livraison',
    'nav.marketplace': 'Marketplace',
    'nav.profile': 'Profil',
    'nav.history': 'Historique',
    'nav.payment': 'Paiement',
    'nav.notifications': 'Notifications',
    'nav.settings': 'Paramètres',
    'nav.wallet': 'Portefeuille',
    'nav.earnings': 'Gains',
    'nav.challenges': 'Défis',
    'nav.support': 'Support',
    
    // Auth
    'auth.login': 'Se connecter',
    'auth.register': 'S\'inscrire',
    'auth.logout': 'Se déconnecter',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.phone': 'Téléphone',
    'auth.forgot_password': 'Mot de passe oublié',
    'auth.reset_password': 'Réinitialiser',
    'auth.verify_phone': 'Vérifier le téléphone',
    
    // Transport Congo RDC
    'transport.book': 'Réserver',
    'transport.pickup': 'Point de départ',
    'transport.destination': 'Destination',
    'transport.vehicle': 'Véhicule',
    'transport.price': 'Prix',
    'transport.time': 'Temps estimé',
    'transport.taxi_bus': 'Taxi-bus',
    'transport.moto_taxi': 'Moto-taxi',
    'transport.taxi_voiture': 'Taxi voiture',
    'transport.bus_transco': 'Bus Transco',
    'transport.status.pending': 'En attente',
    'transport.status.confirmed': 'Confirmé',
    'transport.status.en_route': 'En route',
    'transport.status.arrived': 'Arrivé',
    'transport.status.completed': 'Terminé',
    'transport.status.cancelled': 'Annulé',
    'transport.driver_arriving': 'Chauffeur en approche',
    'transport.eta': 'Arrivée estimée',
    
    // Delivery
    'delivery.flash': 'Livraison Flash',
    'delivery.cargo': 'Livraison Cargo',
    'delivery.package_type': 'Type de colis',
    'delivery.weight': 'Poids',
    'delivery.dimensions': 'Dimensions',
    'delivery.fragile': 'Fragile',
    'delivery.urgent': 'Urgent',
    'delivery.instructions': 'Instructions',
    'delivery.recipient_name': 'Nom du destinataire',
    'delivery.recipient_phone': 'Téléphone destinataire',
    'delivery.delivery_time': 'Heure de livraison',
    'delivery.status.pending': 'En attente',
    'delivery.status.picked_up': 'Récupéré',
    'delivery.status.in_transit': 'En transit',
    'delivery.status.delivered': 'Livré',
    'delivery.status.cancelled': 'Annulé',
    
    // Marketplace
    'marketplace.title': 'Marketplace',
    'marketplace.browse': 'Explorer',
    'marketplace.chat': 'Chat',
    'marketplace.admin': 'Admin',
    'marketplace.products': 'Produits',
    'marketplace.categories': 'Catégories',
    'marketplace.cart': 'Panier',
    'marketplace.favorites': 'Favoris',
    'marketplace.orders': 'Commandes',
    'marketplace.sell': 'Vendre',
    'marketplace.buy': 'Acheter',
    'marketplace.add_to_cart': 'Ajouter au panier',
    'marketplace.checkout': 'Commander',
    'marketplace.price': 'Prix',
    'marketplace.description': 'Description',
    'marketplace.seller': 'Vendeur',
    'marketplace.rating': 'Note',
    'marketplace.reviews': 'Avis',
    'marketplace.stock': 'Stock',
    'marketplace.category': 'Catégorie',
    'marketplace.noConversations': 'Aucune conversation',
    'marketplace.startChatting': 'Commencez à discuter avec les vendeurs pour voir vos conversations ici.',
    
    // Driver
    'driver.dashboard': 'Tableau de bord',
    'driver.earnings': 'Gains',
    'driver.trips': 'Courses',
    'driver.status': 'Statut',
    'driver.online': 'En ligne',
    'driver.offline': 'Hors ligne',
    'driver.available': 'Disponible',
    'driver.busy': 'Occupé',
    'driver.accept_trip': 'Accepter la course',
    'driver.decline_trip': 'Refuser la course',
    'driver.start_trip': 'Commencer la course',
    'driver.complete_trip': 'Terminer la course',
    'driver.vehicle_info': 'Infos véhicule',
    'driver.license': 'Permis',
    'driver.rating': 'Note',
    'driver.total_trips': 'Total courses',
    
    // Wallet
    'wallet.balance': 'Solde',
    'wallet.topup': 'Recharger',
    'wallet.withdraw': 'Retirer',
    'wallet.history': 'Historique',
    'wallet.transaction': 'Transaction',
    'wallet.amount': 'Montant',
    'wallet.fee': 'Frais',
    'wallet.total': 'Total',
    'wallet.pending': 'En attente',
    'wallet.completed': 'Terminé',
    'wallet.failed': 'Échoué',
    
    // Notifications
    'notification.new_trip': 'Nouvelle course disponible',
    'notification.trip_accepted': 'Course acceptée',
    'notification.driver_arrived': 'Chauffeur arrivé',
    'notification.trip_started': 'Course commencée',
    'notification.trip_completed': 'Course terminée',
    'notification.payment_received': 'Paiement reçu',
    'notification.promotion': 'Promotion spéciale',
    'notification.system': 'Notification système',
    
    // Villes principales
    'city.kinshasa': 'Kinshasa',
    'city.lubumbashi': 'Lubumbashi', 
    'city.kolwezi': 'Kolwezi',
    
    // Quartiers Kinshasa
    'location.gombe': 'Gombe',
    'location.kinshasa': 'Kinshasa',
    'location.lemba': 'Lemba',
    'location.ngaliema': 'Ngaliema',
    'location.matete': 'Matete',
    'location.masina': 'Masina',
    'location.ndjili': 'N\'djili',
    'location.kimbanseke': 'Kimbanseke',
    'location.kalamu': 'Kalamu',
    'location.limete': 'Limete',
    'location.kintambo': 'Kintambo',
    
    // Quartiers Lubumbashi
    'location.kenya': 'Kenya',
    'location.kampemba': 'Kampemba',
    'location.kamalondo': 'Kamalondo',
    'location.katuba': 'Katuba',
    'location.ruashi': 'Ruashi',
    'location.annexe': 'Annexe',
    
    // Quartiers Kolwezi
    'location.centre_ville': 'Centre-ville',
    'location.mutanda': 'Mutanda',
    'location.dilala': 'Dilala',
    'location.manika': 'Manika',
    
    // Payment
    'payment.mobile_money': 'Mobile Money',
    'payment.airtel': 'Airtel Money',
    'payment.mpesa': 'M-Pesa',
    'payment.orange': 'Orange Money',
    'payment.amount': 'Montant',
    'payment.phone': 'Numéro de téléphone',
    'payment.confirm': 'Confirmer le paiement',
    'payment.method': 'Méthode de paiement',
    'payment.cash': 'Espèces',
    'payment.wallet': 'Portefeuille',
    'payment.card': 'Carte',
    'payment.status.pending': 'En attente',
    'payment.status.success': 'Réussi',
    'payment.status.failed': 'Échoué',
    
    // Referral
    'referral.title': 'Système de Parrainage',
    'referral.code': 'Code de parrainage',
    'referral.invite': 'Inviter des amis',
    'referral.rewards': 'Récompenses',
    'referral.total_earned': 'Total gagné',
    'referral.share': 'Partager',
    'referral.copy_code': 'Copier le code',

    // Marketplace tendances
    'marketplace.all_trends': 'Toutes les tendances',
    'marketplace.trending_products': 'Produits tendances',
    'marketplace.back_to_trends': 'Retour aux tendances',
    'marketplace.back_to_marketplace': 'Retour au marketplace',

    // Validation
    'validation.validation': 'Validation',
    'validation.status': 'Statut de validation',
    'validation.draft': 'Brouillon',
    'validation.pendingPartner': 'En attente partenaire',
    'validation.pendingAdmin': 'En attente admin',
    'validation.approved': 'Approuvé',
    'validation.rejected': 'Rejeté',
    'validation.comments': 'Commentaires',
    'validation.history': 'Historique',
    'validation.submitForValidation': 'Soumettre pour validation',
    'validation.submitted': 'Demande soumise',
    'validation.submittedDescription': 'Votre demande a été soumise avec succès',
    'validation.submitError': 'Erreur lors de la soumission',
    'validation.noRequest': 'Aucune demande trouvée',
    'validation.unknown': 'Inconnu',
    'validation.driverRequests': 'Demandes chauffeurs',
    'validation.noRequests': 'Aucune demande en attente',
    'validation.review': 'Examiner',
    'validation.reviewRequest': 'Examiner la demande',
    'validation.submittedAt': 'Soumis le',
    'validation.commentsRequired': 'Les commentaires sont obligatoires',
    'validation.commentsPlaceholder': 'Ajoutez vos commentaires de validation...',
    'validation.approve': 'Approuver',
    'validation.reject': 'Rejeter',
    'validation.success': 'Succès',
    'validation.approvedSuccess': 'Demande approuvée avec succès',
    'validation.rejectedSuccess': 'Demande rejetée avec succès',
    'validation.error': 'Erreur de validation',
    'validation.driver': 'Chauffeur',
    'validation.partner': 'Partenaire',
    'validation.admin': 'Administrateur',

    // Driver
    'driver.vehicle': 'Véhicule',
    'driver.vehicleType': 'Type de véhicule',
    'driver.vehicleModel': 'Modèle',
    'driver.vehiclePlate': 'Plaque',
    'driver.licenseNumber': 'Permis',
    'driver.insuranceNumber': 'Assurance',
    
    // Profile
    'profile.edit': 'Modifier le profil',
    'profile.name': 'Nom',
    'profile.email': 'Email',
    'profile.phone': 'Téléphone',
    'profile.address': 'Adresse',
    'profile.photo': 'Photo',
    'profile.verification': 'Vérification',
    'profile.documents': 'Documents',
    'profile.preferences': 'Préférences',
    'profile.language': 'Langue',
    'profile.notifications': 'Notifications',
    'profile.privacy': 'Confidentialité',
    
    // Home Interface
    'home.greeting.morning': 'Bonjour',
    'home.greeting.afternoon': 'Bon après-midi', 
    'home.greeting.evening': 'Bonsoir',
    'home.location.current': 'Position actuelle',
    'home.search.placeholder': 'Où allez-vous ?',
    'home.services.taxi': 'Taxi',
    'home.services.delivery': 'Livraison',
    'home.services.shopping': 'Shopping',
    'home.recent_places': 'Lieux récents',
    'home.no_recent_places': 'Aucun lieu récent',
    'home.recent_places_help': 'Commencez à rechercher des lieux pour les voir apparaître ici',
    'home.marketplace.trending': 'Tendances',
    'home.marketplace.view_all': 'Voir tout',
    'home.marketplace.popular': 'Populaire',
    'home.marketplace.discount': 'Réduction',
    'home.bottom_nav.home': 'Accueil',
    'home.bottom_nav.explore': 'Explorer',
    'home.bottom_nav.favorites': 'Favoris',
    'home.bottom_nav.activity': 'Activité',
    'home.bottom_nav.account': 'Compte',
    'home.place_type.home': 'Domicile',
    'home.place_type.work': 'Bureau',
    'home.place_type.recent': 'Récent',
    'home.notifications.unread': '3',

    // Activity & History
    'activity.history': 'Activité récente',
    'activity.no_bookings': 'Aucune course trouvée',
    'activity.loading': 'Chargement de l\'historique...',
    'activity.driver': 'Chauffeur',
    'activity.pickup': 'Prise en charge',
    'activity.dropoff': 'Destination',
    'activity.price': 'Prix',
    'activity.date': 'Date',
    'activity.status': 'Statut',
    'activity.rate': 'Noter',
    'activity.view_details': 'Voir détails',

    // Delivery
    'delivery.mode.flash': 'Flash',
    'delivery.mode.cargo': 'Cargo',

    // Common
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.continue': 'Continuer',
    'common.back': 'Retour',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.confirm': 'Confirmer',
    'common.offline': 'Hors ligne',
    'common.retry': 'Réessayer',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.sort': 'Trier',
    'common.date': 'Date',
    'common.time': 'Heure',
    'common.status': 'Statut',
    'common.actions': 'Actions',
    'common.details': 'Détails',
    'common.close': 'Fermer',
    'common.select': 'Sélectionner',
    'common.upload': 'Télécharger',
    'common.download': 'Télécharger',
    'common.share': 'Partager',
    'common.copy': 'Copier',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.add': 'Ajouter',
    'common.remove': 'Retirer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.ok': 'OK',
    'common.done': 'Terminé',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.skip': 'Ignorer',
    'common.help': 'Aide',
    'common.about': 'À propos',
    'common.contact': 'Contact',
    'common.terms': 'Conditions',
    'common.privacy': 'Confidentialité',
    'common.user': 'Utilisateur',
    'location.approximate': 'Position approximative',
    'location.unavailable': 'Localisation indisponible',
    'location.gps_unavailable': 'GPS indisponible',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.transport': 'Transport',
    'nav.delivery': 'Delivery',
    'nav.marketplace': 'Marketplace',
    'nav.profile': 'Profile',
    'nav.history': 'History',
    'nav.payment': 'Payment',
    'nav.notifications': 'Notifications',
    'nav.settings': 'Settings',
    'nav.wallet': 'Wallet',
    'nav.earnings': 'Earnings',
    'nav.challenges': 'Challenges',
    'nav.support': 'Support',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Sign Up',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.phone': 'Phone',
    'auth.forgot_password': 'Forgot Password',
    'auth.reset_password': 'Reset',
    'auth.verify_phone': 'Verify Phone',
    
    // Transport Congo RDC
    'transport.book': 'Book',
    'transport.pickup': 'Pickup Point',
    'transport.destination': 'Destination',
    'transport.vehicle': 'Vehicle',
    'transport.price': 'Price',
    'transport.time': 'Estimated Time',
    'transport.taxi_bus': 'Taxi-bus',
    'transport.moto_taxi': 'Moto-taxi',
    'transport.taxi_voiture': 'Car Taxi',
    'transport.bus_transco': 'Transco Bus',
    'transport.status.pending': 'Pending',
    'transport.status.confirmed': 'Confirmed',
    'transport.status.en_route': 'En Route',
    'transport.status.arrived': 'Arrived',
    'transport.status.completed': 'Completed',
    'transport.status.cancelled': 'Cancelled',
    'transport.driver_arriving': 'Driver Approaching',
    'transport.eta': 'Estimated Arrival',
    
    // Delivery
    'delivery.flash': 'Flash Delivery',
    'delivery.cargo': 'Cargo Delivery',
    'delivery.package_type': 'Package Type',
    'delivery.weight': 'Weight',
    'delivery.dimensions': 'Dimensions',
    'delivery.fragile': 'Fragile',
    'delivery.urgent': 'Urgent',
    'delivery.instructions': 'Instructions',
    'delivery.recipient_name': 'Recipient Name',
    'delivery.recipient_phone': 'Recipient Phone',
    'delivery.delivery_time': 'Delivery Time',
    'delivery.status.pending': 'Pending',
    'delivery.status.picked_up': 'Picked Up',
    'delivery.status.in_transit': 'In Transit',
    'delivery.status.delivered': 'Delivered',
    'delivery.status.cancelled': 'Cancelled',
    
    // Marketplace
    'marketplace.products': 'Products',
    'marketplace.categories': 'Categories',
    'marketplace.cart': 'Cart',
    'marketplace.favorites': 'Favorites',
    'marketplace.orders': 'Orders',
    'marketplace.sell': 'Sell',
    'marketplace.buy': 'Buy',
    'marketplace.add_to_cart': 'Add to Cart',
    'marketplace.checkout': 'Checkout',
    'marketplace.price': 'Price',
    'marketplace.description': 'Description',
    'marketplace.seller': 'Seller',
    'marketplace.rating': 'Rating',
    'marketplace.reviews': 'Reviews',
    'marketplace.stock': 'Stock',
    'marketplace.category': 'Category',
    
    // Driver
    'driver.dashboard': 'Dashboard',
    'driver.earnings': 'Earnings',
    'driver.trips': 'Trips',
    'driver.status': 'Status',
    'driver.online': 'Online',
    'driver.offline': 'Offline',
    'driver.available': 'Available',
    'driver.busy': 'Busy',
    'driver.accept_trip': 'Accept Trip',
    'driver.decline_trip': 'Decline Trip',
    'driver.start_trip': 'Start Trip',
    'driver.complete_trip': 'Complete Trip',
    'driver.vehicle_info': 'Vehicle Info',
    'driver.license': 'License',
    'driver.rating': 'Rating',
    'driver.total_trips': 'Total Trips',
    
    // Wallet
    'wallet.balance': 'Balance',
    'wallet.topup': 'Top Up',
    'wallet.withdraw': 'Withdraw',
    'wallet.history': 'History',
    'wallet.transaction': 'Transaction',
    'wallet.amount': 'Amount',
    'wallet.fee': 'Fee',
    'wallet.total': 'Total',
    'wallet.pending': 'Pending',
    'wallet.completed': 'Completed',
    'wallet.failed': 'Failed',
    
    // Notifications
    'notification.new_trip': 'New trip available',
    'notification.trip_accepted': 'Trip accepted',
    'notification.driver_arrived': 'Driver arrived',
    'notification.trip_started': 'Trip started',
    'notification.trip_completed': 'Trip completed',
    'notification.payment_received': 'Payment received',
    'notification.promotion': 'Special promotion',
    'notification.system': 'System notification',
    
    // Cities
    'city.kinshasa': 'Kinshasa',
    'city.lubumbashi': 'Lubumbashi', 
    'city.kolwezi': 'Kolwezi',
    
    // Kinshasa Districts
    'location.gombe': 'Gombe',
    'location.kinshasa': 'Kinshasa',
    'location.lemba': 'Lemba',
    'location.ngaliema': 'Ngaliema',
    'location.matete': 'Matete',
    'location.masina': 'Masina',
    'location.ndjili': 'N\'djili',
    'location.kimbanseke': 'Kimbanseke',
    'location.kalamu': 'Kalamu',
    'location.limete': 'Limete',
    'location.kintambo': 'Kintambo',
    
    // Lubumbashi Districts
    'location.kenya': 'Kenya',
    'location.kampemba': 'Kampemba',
    'location.kamalondo': 'Kamalondo',
    'location.katuba': 'Katuba',
    'location.ruashi': 'Ruashi',
    'location.annexe': 'Annexe',
    
    // Kolwezi Districts
    'location.centre_ville': 'Downtown',
    'location.mutanda': 'Mutanda',
    'location.dilala': 'Dilala',
    'location.manika': 'Manika',
    
    // Payment
    'payment.mobile_money': 'Mobile Money',
    'payment.airtel': 'Airtel Money',
    'payment.mpesa': 'M-Pesa',
    'payment.orange': 'Orange Money',
    'payment.amount': 'Amount',
    'payment.phone': 'Phone Number',
    'payment.confirm': 'Confirm Payment',
    'payment.method': 'Payment Method',
    'payment.cash': 'Cash',
    'payment.wallet': 'Wallet',
    'payment.card': 'Card',
    'payment.status.pending': 'Pending',
    'payment.status.success': 'Success',
    'payment.status.failed': 'Failed',
    
    // Referral
    'referral.title': 'Referral System',
    'referral.code': 'Referral Code',
    'referral.invite': 'Invite Friends',
    'referral.rewards': 'Rewards',
    'referral.total_earned': 'Total Earned',
    'referral.share': 'Share',
    'referral.copy_code': 'Copy Code',
    
    // Home Interface
    'home.greeting.morning': 'Good morning',
    'home.greeting.afternoon': 'Good afternoon',
    'home.greeting.evening': 'Good evening',
    'home.location.current': 'Current location',
    'home.search.placeholder': 'Where are you going?',
    'home.services.taxi': 'Taxi',
    'home.services.delivery': 'Delivery',
    'home.services.shopping': 'Shopping',
    'home.recent_places': 'Recent Places',
    'home.no_recent_places': 'No recent places',
    'home.recent_places_help': 'Start searching for places to see them appear here',
    'home.marketplace.trending': 'Trending',
    'home.marketplace.view_all': 'View All',
    'home.marketplace.popular': 'Popular',
    'home.marketplace.discount': 'Discount',
    'home.bottom_nav.home': 'Home',
    'home.bottom_nav.explore': 'Explore',
    'home.bottom_nav.favorites': 'Favorites',
    'home.bottom_nav.activity': 'Activity',
    'home.bottom_nav.account': 'Account',
    'home.place_type.home': 'Home',
    'home.place_type.work': 'Work',
    'home.place_type.recent': 'Recent',
    'home.notifications.unread': '3',

    // Activity & History
    'activity.history': 'Recent Activity',
    'activity.no_bookings': 'No trips found',
    'activity.loading': 'Loading history...',
    'activity.driver': 'Driver',
    'activity.pickup': 'Pickup',
    'activity.dropoff': 'Dropoff',
    'activity.price': 'Price',
    'activity.date': 'Date',
    'activity.status': 'Status',
    'activity.rate': 'Rate',
    'activity.view_details': 'View Details',

    // Delivery
    'delivery.mode.flash': 'Flash',
    'delivery.mode.cargo': 'Cargo',

    // Profile
    'profile.edit': 'Edit Profile',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.address': 'Address',
    'profile.photo': 'Photo',
    'profile.verification': 'Verification',
    'profile.documents': 'Documents',
    'profile.preferences': 'Preferences',
    'profile.language': 'Language',
    'profile.notifications': 'Notifications',
    'profile.privacy': 'Privacy',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.continue': 'Continue',
    'common.back': 'Back',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    'common.offline': 'Offline',
    'common.retry': 'Retry',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.details': 'Details',
    'common.close': 'Close',
    'common.select': 'Select',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.share': 'Share',
    'common.copy': 'Copy',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.done': 'Done',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.skip': 'Skip',
    'common.help': 'Help',
    'common.about': 'About',
    'common.contact': 'Contact',
    'common.terms': 'Terms',
    'common.privacy': 'Privacy',
    'common.user': 'User',
    'location.approximate': 'Approximate location',
    'location.unavailable': 'Location unavailable',
    'location.gps_unavailable': 'GPS unavailable',
  },
  ln: {
    // Navigation
    'nav.home': 'Bandako',
    'nav.transport': 'Transport',
    'nav.delivery': 'Livraison',
    'nav.marketplace': 'Zando',
    'nav.profile': 'Profil',
    'nav.history': 'Makambo ya kala',
    'nav.payment': 'Kofuta',
    'nav.notifications': 'Ba notifications',
    'nav.settings': 'Ba paramètres',
    
    // Home Interface
    'home.greeting.morning': 'Mbote ya ntongo',
    'home.greeting.afternoon': 'Mbote ya midi',
    'home.greeting.evening': 'Mbote ya mpokwa',
    'home.location.current': 'Esika ozo wana',
    'home.search.placeholder': 'Okokende wapi?',
    'home.services.taxi': 'Taxi',
    'home.services.delivery': 'Livraison',
    'home.services.shopping': 'Kosomba',
    'home.recent_places': 'Bisika ya kala',
    'home.no_recent_places': 'Bisika ya kala ezali te',
    'home.recent_places_help': 'Bandela koluka bisika mpo emona awa',
    'home.marketplace.trending': 'Oyo ezali koleka',
    'home.marketplace.view_all': 'Kotala nyonso',
    'home.marketplace.popular': 'Oyo balingi mingi',
    'home.marketplace.discount': 'Kokitisa ntalo',
    'home.bottom_nav.home': 'Bandako',
    'home.bottom_nav.explore': 'Koluka',
    'home.bottom_nav.favorites': 'Oyo nalingi',
    'home.bottom_nav.activity': 'Makambo',
    'home.bottom_nav.account': 'Compte',
    'home.place_type.home': 'Ndako',
    'home.place_type.work': 'Mosala',
    'home.place_type.recent': 'Ya kala',
    'home.notifications.unread': '3',

    // Activity & History
    'activity.history': 'Makambo ya kala',
    'activity.no_bookings': 'Mobembo ya kala ezali te',
    'activity.loading': 'Eza kocharger makambo ya kala...',
    'activity.driver': 'Motambolisi',
    'activity.pickup': 'Esika ya kokende',
    'activity.dropoff': 'Esika ya kokitisa',
    'activity.price': 'Ntalo',
    'activity.date': 'Mokolo',
    'activity.status': 'Ndenge ezali',
    'activity.rate': 'Kopesa note',
    'activity.view_details': 'Kotala malamu',

    // Delivery
    'delivery.mode.flash': 'Flash',
    'delivery.mode.cargo': 'Cargo',
    
    // Transport Congo RDC
    'transport.book': 'Kokanisa',
    'transport.pickup': 'Esika ya kokende',
    'transport.destination': 'Esika ya kokoma',
    'transport.vehicle': 'Motuka',
    'transport.price': 'Ntalo',
    'transport.time': 'Ntango ya kokende',
    'transport.taxi_bus': 'Taxi-bus',
    'transport.moto_taxi': 'Moto-taxi',
    'transport.taxi_voiture': 'Taxi motuka',
    'transport.bus_transco': 'Bus Transco',
    
    // Cities & Locations
    'city.kinshasa': 'Kinshasa',
    'city.lubumbashi': 'Lubumbashi',
    'city.kolwezi': 'Kolwezi',
    'location.gombe': 'Gombe',
    'location.kinshasa': 'Kinshasa',
    'location.lemba': 'Lemba',
    'location.ngaliema': 'Ngaliema',
    'location.matete': 'Matete',
    'location.masina': 'Masina',
    'location.ndjili': 'N\'djili',
    'location.kimbanseke': 'Kimbanseke',
    
    // Payment
    'payment.mobile_money': 'Mbongo ya téléphone',
    'payment.airtel': 'Airtel Money',
    'payment.mpesa': 'M-Pesa',
    'payment.orange': 'Orange Money',
    'payment.amount': 'Mbongo',
    'payment.phone': 'Numéro ya téléphone',
    'payment.confirm': 'Kondima kofuta',
    
    // Referral
    'referral.title': 'Système ya kopesa baninga',
    'referral.code': 'Code ya kopesa',
    'referral.invite': 'Kobenga baninga',
    'referral.rewards': 'Lifuti',
    'referral.total_earned': 'Mbongo nyonso ozongi',
    
    // Common
    'common.save': 'Kobomba',
    'common.cancel': 'Kotika',
    'common.continue': 'Kokoba',
    'common.back': 'Kozonga',
    'common.loading': 'Eza kochargé...',
    'common.error': 'Libunga',
    'common.success': 'Elongi',
    'common.confirm': 'Kondima',
    'common.offline': 'Internet ezali te',
    'common.retry': 'Komeka lisusu',
    'common.search': 'Koluka',
    'common.user': 'Mosaleli',
  },
  kg: { // Kikongo
    // Navigation
    'nav.home': 'Nzo',
    'nav.transport': 'Transport',
    'nav.delivery': 'Livraison',
    'nav.marketplace': 'Zando',
    'nav.profile': 'Profil',
    'nav.history': 'Makambu ma kala',
    'nav.payment': 'Kufuta',
    'nav.notifications': 'Bisalu',
    'nav.settings': 'Paramètres',
    
    // Home Interface
    'home.greeting.morning': 'Nsuka ya nsuka',
    'home.greeting.afternoon': 'Nsuka ya mbazi',
    'home.greeting.evening': 'Nsuka ya mpimpa',
    'home.location.current': 'Fulu yina usimbama',
    'home.search.placeholder': 'Kuna ukenda?',
    'home.services.taxi': 'Taxi',
    'home.services.delivery': 'Livraison',
    'home.services.shopping': 'Kusuma',
    'home.recent_places': 'Mafulu ma kala',
    'home.no_recent_places': 'Mafulu ma kala mafulu ko',
    'home.recent_places_help': 'Bandika kulonga mafulu mpo mona vava',
    'home.marketplace.trending': 'Oyo yina kuzola',
    'home.marketplace.view_all': 'Mona moso',
    'home.marketplace.popular': 'Oyo bantu bazeyi mingi',
    'home.marketplace.discount': 'Kukenga ntalu',
    'home.bottom_nav.home': 'Nzo',
    'home.bottom_nav.explore': 'Kulonga',
    'home.bottom_nav.favorites': 'Oyo nazoli',
    'home.bottom_nav.activity': 'Makambu',
    'home.bottom_nav.account': 'Compte',
    'home.place_type.home': 'Nzo',
    'home.place_type.work': 'Kisalu',
    'home.place_type.recent': 'Ya kala',
    'home.notifications.unread': '3',

    // Activity & History
    'activity.history': 'Makambu ma kala',
    'activity.no_bookings': 'Mayenda ma kala mafulu ko',
    'activity.loading': 'Yina ku charger makambu ma kala...',
    'activity.driver': 'Mutambulisi',
    'activity.pickup': 'Fulu ya kutuka',
    'activity.dropoff': 'Fulu ya kutula',
    'activity.price': 'Ntalu',
    'activity.date': 'Lumbu',
    'activity.status': 'Ndenge yina vuandi',
    'activity.rate': 'Kuvana note',
    'activity.view_details': 'Mona mayela',

    // Delivery
    'delivery.mode.flash': 'Flash',
    'delivery.mode.cargo': 'Cargo',
    
    // Transport Congo RDC
    'transport.book': 'Kukanisa',
    'transport.pickup': 'Fulu ya kutuka',
    'transport.destination': 'Fulu ya kukenda',
    'transport.vehicle': 'Motuka',
    'transport.price': 'Ntalu',
    'transport.time': 'Thangu ya kukenda',
    'transport.taxi_bus': 'Taxi-bus',
    'transport.moto_taxi': 'Moto-taxi',
    'transport.taxi_voiture': 'Taxi motuka',
    'transport.bus_transco': 'Bus Transco',
    
    // Cities & Locations
    'city.kinshasa': 'Kinshasa',
    'city.lubumbashi': 'Lubumbashi',
    'city.kolwezi': 'Kolwezi',
    'location.gombe': 'Gombe',
    'location.kinshasa': 'Kinshasa',
    'location.lemba': 'Lemba',
    'location.ngaliema': 'Ngaliema',
    'location.matete': 'Matete',
    'location.masina': 'Masina',
    'location.ndjili': 'N\'djili',
    'location.kimbanseke': 'Kimbanseke',
    
    // Payment
    'payment.mobile_money': 'Nkutu za telephone',
    'payment.airtel': 'Airtel Money',
    'payment.mpesa': 'M-Pesa',
    'payment.orange': 'Orange Money',
    'payment.amount': 'Nkutu',
    'payment.phone': 'Numero ya telephone',
    'payment.confirm': 'Kundima kufuta',
    
    // Common
    'common.save': 'Kubika',
    'common.cancel': 'Kutika',
    'common.continue': 'Kukoba',
    'common.back': 'Kuvutuka',
    'common.loading': 'Yina ku charge...',
    'common.error': 'Nkama',
    'common.success': 'Malonga',
    'common.confirm': 'Kundima',
    'common.offline': 'Internet yafulu ko',
    'common.retry': 'Kusolula diaka',
    'common.search': 'Kulonga',
    'common.user': 'Nkento',
  },
  lua: { // Tshiluba
    // Navigation
    'nav.home': 'Muetu',
    'nav.transport': 'Transport',
    'nav.delivery': 'Livraison',
    'nav.marketplace': 'Mubanda',
    'nav.profile': 'Profil',
    'nav.history': 'Bintu bia kala',
    'nav.payment': 'Kulipa',
    'nav.notifications': 'Makambu',
    'nav.settings': 'Paramètres',
    
    // Home Interface
    'home.greeting.morning': 'Wa muana muyanda',
    'home.greeting.afternoon': 'Wa diba',
    'home.greeting.evening': 'Wa manshi',
    'home.location.current': 'Pahali panu udi',
    'home.search.placeholder': 'Oya kuya kudi?',
    'home.services.taxi': 'Taxi',
    'home.services.delivery': 'Livraison',
    'home.services.shopping': 'Kusuma',
    'home.recent_places': 'Mahali ma kala',
    'home.no_recent_places': 'Mahali ma kala mabileko',
    'home.recent_places_help': 'Tandisha kulolesha mahali mpo mona apa',
    'home.marketplace.trending': 'Bintu bilenga',
    'home.marketplace.view_all': 'Bona byonso',
    'home.marketplace.popular': 'Bintu bantu bayanda',
    'home.marketplace.discount': 'Kukenga bei',
    'home.bottom_nav.home': 'Muetu',
    'home.bottom_nav.explore': 'Kulolesha',
    'home.bottom_nav.favorites': 'Bintu ndiyanda',
    'home.bottom_nav.activity': 'Bintu',
    'home.bottom_nav.account': 'Compte',
    'home.place_type.home': 'Muetu',
    'home.place_type.work': 'Mulimu',
    'home.place_type.recent': 'Wa kala',
    'home.notifications.unread': '3',

    // Activity & History
    'activity.history': 'Bintu bia kala',
    'activity.no_bookings': 'Mayendo ma kala mabileko',
    'activity.loading': 'Tukucharge bintu bia kala...',
    'activity.driver': 'Mutambulisha',
    'activity.pickup': 'Pahali pakutanga',
    'activity.dropoff': 'Pahali pakutula',
    'activity.price': 'Bei',
    'activity.date': 'Lumingu',
    'activity.status': 'Cishi',
    'activity.rate': 'Kuapa note',
    'activity.view_details': 'Bona makambu',

    // Delivery
    'delivery.mode.flash': 'Flash',
    'delivery.mode.cargo': 'Cargo',
    
    // Transport Congo RDC
    'transport.book': 'Kubanda',
    'transport.pickup': 'Mahali pakutanga',
    'transport.destination': 'Mahali pakufika',
    'transport.vehicle': 'Motuka',
    'transport.price': 'Bei',
    'transport.time': 'Nako ya kuya',
    'transport.taxi_bus': 'Taxi-bus',
    'transport.moto_taxi': 'Moto-taxi',
    'transport.taxi_voiture': 'Taxi motuka',
    'transport.bus_transco': 'Bus Transco',
    
    // Cities & Locations
    'city.kinshasa': 'Kinshasa',
    'city.lubumbashi': 'Lubumbashi',
    'city.kolwezi': 'Kolwezi',
    'location.gombe': 'Gombe',
    'location.kinshasa': 'Kinshasa',
    'location.lemba': 'Lemba',
    'location.ngaliema': 'Ngaliema',
    'location.matete': 'Matete',
    'location.masina': 'Masina',
    'location.ndjili': 'N\'djili',
    'location.kimbanseke': 'Kimbanseke',
    
    // Payment
    'payment.mobile_money': 'Mbongo ya telephone',
    'payment.airtel': 'Airtel Money',
    'payment.mpesa': 'M-Pesa',
    'payment.orange': 'Orange Money',
    'payment.amount': 'Mbongo',
    'payment.phone': 'Numero ya telephone',
    'payment.confirm': 'Kutambula kulipa',
    
    // Common
    'common.save': 'Kubika',
    'common.cancel': 'Kuleka',
    'common.continue': 'Kuendelea',
    'common.back': 'Kubuya',
    'common.loading': 'Nkucharge...',
    'common.error': 'Nshimu',
    'common.success': 'Malonga',
    'common.confirm': 'Kutambula',
    'common.offline': 'Internet ibi',
    'common.retry': 'Kusolola',
    'common.search': 'Kulolesha',
    'common.user': 'Muntu',
  },
  sw: { // Swahili
    // Navigation
    'nav.home': 'Nyumbani',
    'nav.transport': 'Usafiri',
    'nav.delivery': 'Utoaji',
    'nav.marketplace': 'Soko',
    'nav.profile': 'Profili',
    'nav.history': 'Historia',
    'nav.payment': 'Malipo',
    'nav.notifications': 'Arifa',
    'nav.settings': 'Mipangilio',
    
    // Home Interface
    'home.greeting.morning': 'Habari za asubuhi',
    'home.greeting.afternoon': 'Habari za mchana',
    'home.greeting.evening': 'Habari za jioni',
    'home.location.current': 'Mahali upo sasa',
    'home.search.placeholder': 'Unaenda wapi?',
    'home.services.taxi': 'Taxi',
    'home.services.delivery': 'Utoaji',
    'home.services.shopping': 'Ununuzi',
    'home.recent_places': 'Maeneo ya hivi karibuni',
    'home.no_recent_places': 'Hakuna maeneo ya hivi karibuni',
    'home.recent_places_help': 'Anza kutafuta maeneo ili yaonekane hapa',
    'home.marketplace.trending': 'Kinachojazwa',
    'home.marketplace.view_all': 'Ona Vyote',
    'home.marketplace.popular': 'Maarufu',
    'home.marketplace.discount': 'Punguzo',
    'home.bottom_nav.home': 'Nyumbani',
    'home.bottom_nav.explore': 'Gundua',
    'home.bottom_nav.favorites': 'Vipendwa',
    'home.bottom_nav.activity': 'Shughuli',
    'home.bottom_nav.account': 'Akaunti',
    'home.place_type.home': 'Nyumbani',
    'home.place_type.work': 'Kazini',
    'home.place_type.recent': 'Hivi karibuni',
    'home.notifications.unread': '3',

    // Activity & History
    'activity.history': 'Shughuli za hivi karibuni',
    'activity.no_bookings': 'Hakuna safari zilizopatikana',
    'activity.loading': 'Inapakia historia...',
    'activity.driver': 'Dereva',
    'activity.pickup': 'Kuchukua',
    'activity.dropoff': 'Kuangusha',
    'activity.price': 'Bei',
    'activity.date': 'Tarehe',
    'activity.status': 'Hali',
    'activity.rate': 'Tathmini',
    'activity.view_details': 'Ona Maelezo',

    // Delivery
    'delivery.mode.flash': 'Flash',
    'delivery.mode.cargo': 'Cargo',
    
    // Transport Congo RDC
    'transport.book': 'Kuweka',
    'transport.pickup': 'Mahali pa kuchukua',
    'transport.destination': 'Unakoenda',
    'transport.vehicle': 'Gari',
    'transport.price': 'Bei',
    'transport.time': 'Muda wa kufikia',
    'transport.taxi_bus': 'Basi-taxi',
    'transport.moto_taxi': 'Piki-piki',
    'transport.taxi_voiture': 'Taxi gari',
    'transport.bus_transco': 'Basi Transco',
    
    // Cities & Locations
    'city.kinshasa': 'Kinshasa',
    'city.lubumbashi': 'Lubumbashi',
    'city.kolwezi': 'Kolwezi',
    'location.gombe': 'Gombe',
    'location.kinshasa': 'Kinshasa',
    'location.lemba': 'Lemba',
    'location.ngaliema': 'Ngaliema',
    'location.matete': 'Matete',
    'location.masina': 'Masina',
    'location.ndjili': 'N\'djili',
    'location.kimbanseke': 'Kimbanseke',
    
    // Payment
    'payment.mobile_money': 'Pesa za simu',
    'payment.airtel': 'Airtel Money',
    'payment.mpesa': 'M-Pesa',
    'payment.orange': 'Orange Money',
    'payment.amount': 'Kiasi',
    'payment.phone': 'Nambari ya simu',
    'payment.confirm': 'Thibitisha malipo',
    
    // Common
    'common.save': 'Hifadhi',
    'common.cancel': 'Ghairi',
    'common.continue': 'Endelea',
    'common.back': 'Rudi',
    'common.loading': 'Inapakia...',
    'common.error': 'Kosa',
    'common.success': 'Mafanikio',
    'common.confirm': 'Thibitisha',
    'common.offline': 'Bila mtandao',
    'common.retry': 'Jaribu tena',
    'common.search': 'Tafuta',
    'common.user': 'Mtumiaji',

    // Validation
    'validation.validation': 'Uthibitisho',
    'validation.status': 'Hali ya uthibitisho',
    'validation.draft': 'Rasimu',
    'validation.pendingPartner': 'Inasubiri mshirika',
    'validation.pendingAdmin': 'Inasubiri msimamizi',
    'validation.approved': 'Imeidhinishwa',
    'validation.rejected': 'Imekataliwa',
    'validation.comments': 'Maoni',
    'validation.history': 'Historia',
    'validation.submitForValidation': 'Wasilisha kwa uthibitisho',
    'validation.submitted': 'Ombi limewasilishwa',
    'validation.submittedDescription': 'Ombi lako limewasilishwa kwa mafanikio',
    'validation.submitError': 'Hitilafu katika kuwasilisha',
    'validation.noRequest': 'Hakuna ombi lililopatikana',
    'validation.unknown': 'Haijulikani',
    'validation.driverRequests': 'Maombi ya madereva',
    'validation.noRequests': 'Hakuna maombi yanayosubiri',
    'validation.review': 'Kagua',
    'validation.reviewRequest': 'Kagua ombi',
    'validation.submittedAt': 'Imewasilishwa mnamo',
    'validation.commentsRequired': 'Maoni yanahitajika',
    'validation.commentsPlaceholder': 'Ongeza maoni yako ya uthibitisho...',
    'validation.approve': 'Idhinisha',
    'validation.reject': 'Kataa',
    'validation.success': 'Mafanikio',
    'validation.approvedSuccess': 'Ombi limeidhinishwa kwa mafanikio',
    'validation.rejectedSuccess': 'Ombi limekataliwa kwa mafanikio',
    'validation.error': 'Hitilafu ya uthibitisho',
    'validation.driver': 'Dereva',
    'validation.partner': 'Mshirika',
    'validation.admin': 'Msimamizi',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('kwenda-language');
    return (saved as Language) || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('kwenda-language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations.fr[key] || key;
  };

  const formatCurrency = (amount: number, currency: 'CDF' | 'USD' = 'CDF'): string => {
    if (currency === 'CDF') {
      return new Intl.NumberFormat('fr-CD', {
        minimumFractionDigits: 0,
        maximumFractionDigits: 0
      }).format(amount) + ' CDF';
    } else {
      return new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD'
      }).format(amount);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, formatCurrency }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};