import React, { createContext, useContext, useState, ReactNode } from 'react';
import { logMissingTranslations } from '@/utils/translationValidator';

export type Language = 'fr' | 'en' | 'kg' | 'lua' | 'sw';

// TRADUCTIONS COMPLÈTES - SYSTÈME MULTILINGUE COMPLET
export const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.services': 'Services',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'nav.login': 'Connexion',
    'nav.signup': 'Inscription',
    'nav.client': 'Client',
    'nav.driver': 'Chauffeur',
    'nav.admin': 'Admin',
    'nav.download_app': 'Télécharger App',
    
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.save': 'Enregistrer',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.view_all': 'Voir tout',
    'common.add': 'Ajouter',
    'common.remove': 'Retirer',
    'common.close': 'Fermer',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    
    // Auth
    'auth.login': 'Connexion',
    'auth.register': 'Inscription',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.continue': 'Continuer',
    'auth.logout': 'Déconnexion',
    'auth.forgot_password': 'Mot de passe oublié',
    'auth.reset_password': 'Réinitialiser le mot de passe',
    'auth.confirm_password': 'Confirmer le mot de passe',
    'auth.create_account': 'Créer un compte',
    
    // Role Selection
    'role.client': 'Client',
    'role.driver': 'Chauffeur',
    'role.partner': 'Partenaire', 
    'role.admin': 'Administrateur',
    'role.select': 'Choisir un rôle',
    'role.client_desc': 'Commandez des courses et livraisons',
    'role.driver_desc': 'Devenez chauffeur partenaire',
    'role.partner_desc': 'Gérez votre flotte de véhicules',
    
    // Home/Recent Places
    'home.recent_places': 'Lieux récents',
    'home.no_recent_places': 'Aucun lieu récent trouvé',
    'home.recent_places_help': 'Vos dernières destinations apparaîtront ici',
    'home.add_current_location': 'Ajouter ma position',
    'home.use_current_location': 'Utiliser ma position actuelle',
    'home.set_as_home': 'Définir comme domicile',
    'home.set_as_work': 'Définir comme bureau',
    'home.home_label': 'Domicile',
    'home.work_label': 'Bureau',
    'home.remove_place': 'Supprimer ce lieu',
    'home.search.placeholder': 'Où voulez-vous aller ?',
    'home.services.taxi': 'Transport',
    'home.services.delivery': 'Livraison',
    'home.services.shopping': 'Shopping',
    'home.services.rental': 'Location',
    'home.services.lottery': 'Tombola',
    
    // Toast messages
    'toast.place_removed': 'Lieu supprimé',
    'toast.place_removed_desc': 'Le lieu a été retiré de vos lieux récents',
    'toast.location_added': 'Position ajoutée',
    'toast.location_added_desc': 'Votre position actuelle a été ajoutée aux lieux récents',
    'toast.location_error': 'Erreur',
    'toast.location_error_desc': 'Impossible d\'obtenir votre position actuelle',
    'toast.home_set': 'Domicile défini',
    'toast.home_set_desc': '{0} est maintenant votre domicile',
    'toast.work_set': 'Bureau défini',
    'toast.work_set_desc': '{0} est maintenant votre bureau',
    
    // Hero Section
    'hero.title': 'Transport et Livraison en RDC',
    'hero.subtitle': 'Votre solution complète de mobilité urbaine',
    'hero.description': 'Des courses VTC aux livraisons express, découvrez Kwenda - l\'application qui révolutionne le transport en République Démocratique du Congo.',
    'hero.cta_start': 'Commencer maintenant',
    'hero.cta_demo': 'Voir la démo',
    'hero.stats.cities': 'Villes actives',
    'hero.stats.available': 'Disponible 24h/7j',
    'hero.stats.payment': 'Paiement sécurisé',
    'hero.stats.support': 'Support client',
    'hero.kwenda_taxi': 'Kwenda Taxi',
    'hero.made_in_rdc': 'Fait en RDC',
    'hero.innovation_excellence': 'Innovation & Excellence',
    'hero.tagline': 'Votre partenaire mobilité en Afrique',
    'hero.start_now': 'Commencer maintenant',
    'hero.view_demo': 'Voir la démo',
    'hero.transport_types': 'Types de transport',
    'hero.customer_service': 'Service client',
    'hero.available_24_7': 'Disponible 24h/7j',
    'hero.kwenda_pay': 'KwendaPay',
    'hero.location': 'Kinshasa, Lubumbashi, Kolwezi',
    'hero.alt_text': 'Service de transport Kwenda Taxi en RDC',
    
    // Services
    'services.title': 'Nos Services',
    'services.subtitle': 'Solutions complètes pour tous vos besoins de mobilité',
    'services.vtc.title': 'VTC & Transport',
    'services.vtc.description': 'Courses privées et partagées',
    'services.delivery.title': 'Livraison Express',
    'services.delivery.description': 'Livraisons rapides et sécurisées',
    'services.marketplace.title': 'Marketplace',
    'services.marketplace.description': 'Boutique en ligne intégrée',
    'services.rental.title': 'Location de véhicules',
    'services.rental.description': 'Louez des véhicules facilement',
    'services.vtc_standard': 'VTC Standard',
    'services.vtc_standard_desc': 'Voitures confortables pour vos déplacements quotidiens',
    'services.vtc_standard_price': 'À partir de 2000 CDF',
    'services.vtc_standard_feat1': 'Véhicules climatisés',
    'services.vtc_standard_feat2': 'Chauffeurs professionnels',
    'services.vtc_standard_feat3': 'Tarifs transparents',
    'services.vtc_luxe': 'VTC Luxe',
    'services.vtc_luxe_desc': 'Véhicules haut de gamme pour un confort exceptionnel',
    'services.vtc_luxe_price': 'À partir de 4000 CDF',
    'services.vtc_luxe_feat1': 'Véhicules premium',
    'services.vtc_luxe_feat2': 'Service VIP',
    'services.vtc_luxe_feat3': 'Eau offerte',
    'services.shared_rides': 'Courses Partagées',
    'services.shared_rides_desc': 'Partagez votre trajet et réduisez vos coûts',
    'services.shared_rides_price': 'À partir de 1000 CDF',
    'services.shared_rides_feat1': 'Économique',
    'services.shared_rides_feat2': 'Écologique',
    'services.shared_rides_feat3': 'Social',
    'services.moto_delivery': 'Livraison Moto',
    'services.moto_delivery_desc': 'Livraisons express par moto-taxi',
    'services.moto_delivery_price': 'À partir de 1500 CDF',
    'services.moto_delivery_feat1': 'Livraison en 30min',
    'services.moto_delivery_feat2': 'Évite les embouteillages',
    'services.moto_delivery_feat3': 'Suivi temps réel',
    'services.utility_vehicles': 'Véhicules Utilitaires',
    'services.utility_vehicles_desc': 'Camionnettes pour vos gros colis',
    'services.utility_vehicles_price': 'À partir de 5000 CDF',
    'services.utility_vehicles_feat1': 'Grande capacité',
    'services.utility_vehicles_feat2': 'Chargement assisté',
    'services.utility_vehicles_feat3': 'Déménagements',
    'services.advance_booking': 'Réservation Avancée',
    'services.advance_booking_desc': 'Planifiez vos trajets à l\'avance',
    'services.advance_booking_price': 'Tarif standard + 500 CDF',
    'services.advance_booking_feat1': 'Planification flexible',
    'services.advance_booking_feat2': 'Garantie de disponibilité',
    'services.advance_booking_feat3': 'Rappel automatique',
    'services.popular': 'Populaire',
    'services.book_now': 'Réserver maintenant',
    'services.cta_title': 'Prêt à commencer ?',
    'services.cta_subtitle': 'Téléchargez l\'application ou devenez chauffeur partenaire',
    'services.download_app': 'Télécharger l\'App',
    'services.become_driver_partner': 'Devenir Chauffeur',
    
    // Features
    'features.title': 'Fonctionnalités Avancées',
    'features.subtitle': 'Une expérience utilisateur exceptionnelle',
    'features.title_prefix': 'Pourquoi choisir',
    'features.title_brand': 'Kwenda',
    'features.realtime.title': 'Suivi en temps réel',
    'features.realtime.description': 'Suivez vos courses et livraisons en direct',
    'features.payment.title': 'Paiements sécurisés',
    'features.payment.description': 'Multiple options de paiement local',
    'features.multilingual.title': 'Multilingue',
    'features.multilingual.description': 'Interface en français et langues locales',
    'features.support.title': 'Support 24/7',
    'features.support.description': 'Assistance client disponible en permanence',
    'features.stats_cities': '4+ Villes',
    'features.maximum_security': 'Sécurité maximale',
    'features.maximum_security_desc': 'Protection totale de vos données personnelles et de vos transactions',
    'features.stats_support': 'Support 24/7',
    'features.stats_vehicles': 'Véhicules',
    'features.stats_eco': 'Écologique',
    'features.eco_fleet': 'Flotte Écologique',
    'features.eco_fleet_desc': 'Véhicules respectueux de l\'environnement pour un transport durable',
    'features.alt_eco_car': 'Voiture écologique',
    'features.smart_geolocation': 'Géolocalisation Intelligente',
    'features.smart_geolocation_desc': 'Localisation précise et rapide pour des trajets optimisés',
    'features.alt_mobile_app': 'Application mobile',
    'features.certified_drivers': 'Chauffeurs Certifiés',
    'features.certified_drivers_desc': 'Conducteurs professionnels vérifiés et formés',
    'features.alt_professional_drivers': 'Chauffeurs professionnels',
    'features.flexible_payments': 'Paiements Flexibles',
    'features.flexible_payments_desc': 'Plusieurs options de paiement adaptées à l\'Afrique',
    'features.shared_rides': 'Courses Partagées',
    'features.shared_rides_desc': 'Économisez en partageant vos trajets avec d\'autres passagers',
    
    // Support
    'support.title': 'Support Client',
    'support.subtitle': 'Nous sommes là pour vous aider',
    'support.contact': 'Nous contacter',
    'support.faq': 'FAQ',
    'support.help': 'Centre d\'aide',
    'support.contact_us': 'Nous contacter',
    'support.phone': 'Téléphone',
    'support.phone_desc': 'Appelez-nous directement',
    'support.contact_phone': '+243 970 123 456',
    'support.availability_phone': 'Disponible 24h/7j',
    'support.email': 'Email',
    'support.email_desc': 'Envoyez-nous un message',
    'support.contact_email': 'support@kwenda.cd',
    'support.availability_email': 'Réponse sous 2h',
    'support.chat': 'Chat en direct',
    'support.chat_desc': 'Discutez avec un agent',
    'support.contact_chat': 'Démarrer une conversation',
    'support.availability_chat': 'En ligne maintenant',
    'support.create_ticket': 'Créer un ticket',
    'support.category_required': 'Catégorie requise',
    'support.select_category': 'Sélectionner une catégorie',
    'support.priority': 'Priorité',
    'support.priority_low': 'Faible',
    'support.priority_medium': 'Moyenne',
    'support.priority_high': 'Élevée',
    'support.priority_urgent': 'Urgente',
    'support.subject': 'Sujet',
    'support.subject_required': 'Sujet requis',
    'support.subject_placeholder': 'Décrivez brièvement votre problème',
    'support.description': 'Description',
    'support.description_required': 'Description requise',
    'support.description_placeholder': 'Décrivez votre problème en détail...',
    'support.send_ticket': 'Envoyer le ticket',
    'support.ticket_sent': 'Ticket envoyé',
    'support.ticket_sent_desc': 'Votre demande a été transmise avec succès',
    'support.available_soon': 'Bientôt disponible',
    'support.status_open': 'Ouvert',
    'support.status_in_progress': 'En cours',
    'support.status_resolved': 'Résolu',
    'support.status_closed': 'Fermé',
    'support.categories.general': 'Général',
    'support.categories.technical': 'Technique',
    'support.categories.billing': 'Facturation',
    'support.categories.account': 'Compte',
    
    // Escrow/Secure Vault - Français
    'escrow.title': 'Coffre-fort Sécurisé',
    'escrow.subtitle': 'Vos paiements sont protégés jusqu\'à confirmation de livraison',
    'escrow.back_home': 'Retour à l\'accueil',
    'escrow.no_transactions': 'Aucune transaction sécurisée',
    'escrow.description': 'Vos paiements sont protégés',
    'escrow.balance': 'Solde disponible',
    'escrow.consultation_balance': 'Disponible pour retrait',
    'escrow.secure_transactions': 'Transactions protégées',
    'escrow.pending_confirmation': 'En attente de confirmation',
    'escrow.all_tabs': 'Toutes',
    'escrow.secured_tabs': 'Sécurisées',
    'escrow.released_tabs': 'Libérées',
    'escrow.pending_tabs': 'En attente',
    'escrow.status_held': 'Sécurisé',
    'escrow.status_completed': 'Libéré',
    'escrow.status_disputed': 'Litige',
    'escrow.status_refunded': 'Remboursé',
    'escrow.status_timeout': 'Expiré',
    'escrow.delivery_confirmed': 'Livraison confirmée',
    'escrow.delivery_confirmed_desc': 'Les fonds ont été libérés avec succès',
    'escrow.error_title': 'Erreur',
    'escrow.error_load_vault': 'Impossible de charger les données du coffre',
    'escrow.error_confirmation': 'Erreur lors de la confirmation',
    'escrow.confirm_delivery': 'Confirmer la réception',
    'escrow.release_funds': 'Libérer les fonds',
    'escrow.vault_transaction_id': 'Transaction #',
    'escrow.transaction_role_buyer': 'Acheteur',
    'escrow.transaction_role_seller': 'Vendeur',
    'escrow.transaction_role_driver': 'Livreur',
    'escrow.secured_amount': 'Montant sécurisé',
    'escrow.seller_earnings': 'Votre gain',
    'escrow.delivery_fee': 'Frais livraison',
    'escrow.view_details': 'Détails',
    'escrow.funds_released_on': 'Fonds libérés le',
    'escrow.auto_release_on': 'Libération automatique le',
    'escrow.expires_soon': 'Expire bientôt',
    
    // System
    'system.loading': 'Chargement...',
    'system.error': 'Erreur',
    'system.success': 'Succès',
    'system.error_occurred': 'Une erreur s\'est produite',
    'system.try_again': 'Réessayer',
    'system.no_data': 'Aucune donnée disponible',
    
    // Payment
    'payment.method': 'Paiement mobile',
    'payment.secure': 'Paiement sécurisé',
    'payment.options': 'Options de paiement',
    
    // Marketplace Basic
    'marketplace.new_badge': 'Nouveau',
    'marketplace.trending': 'Tendance',
    
    // Lottery
    'lottery.free_lottery': 'Loterie gratuite',
    'lottery.win_credits': 'Gagnez des crédits',
    'lottery.daily_draw': 'Tirage quotidien',

    // Client Navigation
    'client.nav.home': 'Accueil',
    'client.nav.activity': 'Activité', 
    'client.nav.account': 'Compte',

    // User Profile
    'profile.loading': 'Chargement du profil...',
    'profile.edit_name': 'Modifier le nom',
    'profile.edit_phone': 'Modifier le téléphone',
    'profile.history': 'Historique',
    'profile.addresses': 'Mes adresses',
    'profile.support': 'Assistance',
    'profile.settings': 'Paramètres',
    'profile.logout': 'Se déconnecter',
    'profile.logout_confirm': 'Confirmer la déconnexion',
    'profile.save': 'Enregistrer',
    'profile.cancel': 'Annuler',
    'profile.enter_name': 'Entrez votre nom',
    'profile.enter_phone': 'Entrez votre téléphone',

    // Transport
    'transport.destination': 'Destination',
    'transport.vehicle_type': 'Type de véhicule',
    'transport.confirm_booking': 'Confirmer la réservation',
    'transport.position_detected': 'Position détectée',
    'transport.geolocation_failed': 'Géolocalisation échouée',
    'transport.pickup_location': 'Lieu de départ',
    'transport.book_ride': 'Réserver une course',
    'transport.searching_driver': 'Recherche de chauffeur en cours...',
    'transport.driver_found': 'Chauffeur trouvé',
    'transport.cancel_ride': 'Annuler la course',
    'transport.ride_in_progress': 'Course en cours',
    'transport.taxi_standard': 'Taxi Standard',
    'transport.taxi_standard_desc': 'Service de taxi classique, confortable et abordable',
    'transport.taxi_premium': 'Taxi Premium',
    'transport.taxi_premium_desc': 'Service de taxi haut de gamme avec véhicules de luxe',
    'transport.moto_taxi_desc': 'Transport rapide par moto, idéal pour éviter les embouteillages',
    'transport.where_from': 'D\'où partez-vous ?',

    // Delivery
    'delivery.destination': 'Point de livraison',
    'delivery.service_type': 'Type de service',
    'delivery.confirmation': 'Confirmation',
    'delivery.where_deliver': 'Où devons-nous livrer votre colis ?',
    'delivery.package_type': 'Type de colis',
    'delivery.estimated_price': 'Prix estimé',
    'delivery.pickup_location': 'Point de collecte',
    'delivery.express_delivery': 'Livraison Express',
    'delivery.fast_reliable': 'Service de livraison rapide et fiable',
    'delivery.where_pickup': 'Où récupérer le colis ?',
    'delivery.where_delivery': 'Où livrer le colis ?',
    'delivery.contact_info': 'Informations de contact',
    'delivery.pickup_address': 'Adresse de collecte',

    // Driver Navigation
    'driver.rides': 'Courses',
    'driver.deliveries': 'Livraisons',

    // Transport additional keys
    'transport.enter_locations': 'Veuillez saisir les lieux de départ et d\'arrivée',
    'transport.booking_error': 'Erreur lors de la création de la réservation',

    // Activity History
    'activity.title': 'Historique des courses',
    'activity.loading': 'Chargement de l\'historique...',
    'activity.no_rides': 'Aucune course trouvée',
    'activity.driver': 'Chauffeur',
    'activity.completed': 'Terminé',
    'activity.pending': 'En attente',
    'activity.today': 'Aujourd\'hui',
    'activity.yesterday': 'Hier',
    'activity.price_undefined': 'Prix non défini',

    // Marketplace Client
    'marketplace.my_activities': 'Mes Activités',
    'marketplace.my_purchases': 'Mes Achats', 
    'marketplace.my_sales': 'Mes Ventes',
    'marketplace.quantity': 'Quantité',
    'marketplace.phone': 'Téléphone',
    'marketplace.add_to_cart': 'Ajouter au panier',
    'marketplace.product_added': 'Produit ajouté',
    'marketplace.product_added_desc': '{0} a été ajouté au panier',
    'marketplace.location_required': 'Localisation requise',
    'marketplace.location_required_desc': 'Activez la géolocalisation pour calculer la livraison',
    'marketplace.orders_created': 'Commandes créées',
    'marketplace.orders_created_desc': 'Vos commandes ont été transmises aux vendeurs',
    'marketplace.your_position': 'Votre position',
    'marketplace.products_count': 'produits',
    'marketplace.featured': 'Sélection',
    'marketplace.popular': 'Populaires',
    'marketplace.nearby': 'Près de vous',
    'marketplace.error_load': 'Impossible de charger les produits',
    'marketplace.unknown_seller': 'Vendeur inconnu',

    // Profile Messages
    'profile.updated': 'Profil mis à jour',
    'profile.updated_desc': 'Vos informations ont été mises à jour avec succès',
    'profile.name_updated': 'Nom mis à jour',
    'profile.name_updated_desc': 'Votre nom a été mis à jour avec succès',
    'profile.phone_updated': 'Téléphone mis à jour',
    'profile.phone_updated_desc': 'Votre numéro de téléphone a été mis à jour avec succès',
    'profile.logout_success': 'Déconnexion réussie',
    'profile.logout_success_desc': 'Vous avez été déconnecté avec succès',
    'profile.error_update': 'Impossible de mettre à jour le profil',
    'profile.error_update_name': 'Impossible de mettre à jour le nom',
    'profile.error_update_phone': 'Impossible de mettre à jour le téléphone',
    'profile.error_logout': 'Impossible de se déconnecter',

    // FAQ Section
    'faq.cancel_trip': 'Comment annuler un trajet ?',
    'faq.cancel_trip_answer': 'Vous pouvez annuler votre trajet directement depuis l\'application dans la section "Mes courses". Un remboursement sera effectué selon nos conditions.',
    'faq.payment': 'Modes de paiement',
    'faq.payment_answer': 'Nous acceptons plusieurs modes de paiement : mobile money (Orange Money, M-Pesa), cartes bancaires et paiement en espèces.',
    'faq.lost_item': 'Objet perdu ou oublié',
    'faq.lost_item_answer': 'Contactez notre support client immédiatement via le chat ou par téléphone. Nous vous mettrons en relation avec le chauffeur pour récupérer vos affaires.',
    'faq.become_driver': 'Devenir chauffeur partenaire',
    'faq.become_driver_answer': 'Pour devenir chauffeur Kwenda, inscrivez-vous via l\'application, soumettez vos documents (permis, assurance, contrôle technique) et passez la validation.',
    'faq.data_security': 'Sécurité des données',
    'faq.data_security_answer': 'Vos données sont protégées par cryptage SSL et conformes aux normes internationales. Nous ne partageons jamais vos informations personnelles.'
  },
  
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view_all': 'View All',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.continue': 'Continue',
    'auth.logout': 'Logout',
    'auth.forgot_password': 'Forgot Password',
    'auth.reset_password': 'Reset Password',
    'auth.confirm_password': 'Confirm Password',
    'auth.create_account': 'Create Account',
    
    // Role Selection
    'role.client': 'Client',
    'role.driver': 'Driver',
    'role.partner': 'Partner',
    'role.admin': 'Administrator',
    'role.select': 'Select Role',
    'role.client_desc': 'Order rides and deliveries',
    'role.driver_desc': 'Become a partner driver',
    'role.partner_desc': 'Manage your vehicle fleet',
    
    // Home/Recent Places
    'home.recent_places': 'Recent Places',
    'home.no_recent_places': 'No recent places found',
    'home.recent_places_help': 'Your recent destinations will appear here',
    'home.add_current_location': 'Add My Location',
    'home.use_current_location': 'Use my current location',
    'home.set_as_home': 'Set as Home',
    'home.set_as_work': 'Set as Work',
    'home.home_label': 'Home',
    'home.work_label': 'Work',
    'home.remove_place': 'Remove this place',
    'home.search.placeholder': 'Where do you want to go?',
    'home.services.taxi': 'Transport',
    'home.services.delivery': 'Delivery',
    'home.services.shopping': 'Shopping',
    'home.services.rental': 'Rental',
    'home.services.lottery': 'Lottery',
    
    // Toast messages
    'toast.place_removed': 'Place Removed',
    'toast.place_removed_desc': 'The place has been removed from your recent places',
    'toast.location_added': 'Location Added',
    'toast.location_added_desc': 'Your current location has been added to recent places',
    'toast.location_error': 'Error',
    'toast.location_error_desc': 'Unable to get your current location',
    'toast.home_set': 'Home Set',
    'toast.home_set_desc': '{0} is now your home',
    'toast.work_set': 'Work Set',
    'toast.work_set_desc': '{0} is now your work',
    
    // Hero Section
    'hero.title': 'Transport and Delivery in DRC',
    'hero.subtitle': 'Your complete urban mobility solution',
    'hero.description': 'From VTC rides to express deliveries, discover Kwenda - the app revolutionizing transport in the Democratic Republic of Congo.',
    'hero.cta_start': 'Get Started',
    'hero.cta_demo': 'View Demo',
    'hero.stats.cities': 'Active Cities',
    'hero.stats.available': 'Available 24/7',
    'hero.stats.payment': 'Secure Payment',
    'hero.stats.support': 'Customer Support',
    'hero.kwenda_taxi': 'Kwenda Taxi',
    'hero.made_in_rdc': 'Made in DRC',
    'hero.innovation_excellence': 'Innovation & Excellence',
    'hero.tagline': 'Your mobility partner in Africa',
    'hero.start_now': 'Get Started',
    'hero.view_demo': 'View Demo',
    'hero.transport_types': 'Transport Types',
    'hero.customer_service': 'Customer Service',
    'hero.available_24_7': 'Available 24/7',
    'hero.kwenda_pay': 'KwendaPay',
    'hero.location': 'Kinshasa, Lubumbashi, Kolwezi',
    'hero.alt_text': 'Kwenda Taxi transport service in DRC',
    
    // Services
    'services.title': 'Our Services',
    'services.subtitle': 'Complete solutions for all your mobility needs',
    'services.vtc.title': 'VTC & Transport',
    'services.vtc.description': 'Private and shared rides',
    'services.delivery.title': 'Express Delivery',
    'services.delivery.description': 'Fast and secure deliveries',
    'services.marketplace.title': 'Marketplace',
    'services.marketplace.description': 'Integrated online store',
    'services.rental.title': 'Vehicle Rental',
    'services.rental.description': 'Rent vehicles easily',
    'services.vtc_standard': 'Standard VTC',
    'services.vtc_standard_desc': 'Comfortable cars for your daily trips',
    'services.vtc_standard_price': 'From 2000 CDF',
    'services.vtc_standard_feat1': 'Air-conditioned vehicles',
    'services.vtc_standard_feat2': 'Professional drivers',
    'services.vtc_standard_feat3': 'Transparent pricing',
    'services.vtc_luxe': 'Luxury VTC',
    'services.vtc_luxe_desc': 'Premium vehicles for exceptional comfort',
    'services.vtc_luxe_price': 'From 4000 CDF',
    'services.vtc_luxe_feat1': 'Premium vehicles',
    'services.vtc_luxe_feat2': 'VIP service',
    'services.vtc_luxe_feat3': 'Complimentary water',
    'services.shared_rides': 'Shared Rides',
    'services.shared_rides_desc': 'Share your ride and reduce costs',
    'services.shared_rides_price': 'From 1000 CDF',
    'services.shared_rides_feat1': 'Economical',
    'services.shared_rides_feat2': 'Eco-friendly',
    'services.shared_rides_feat3': 'Social',
    'services.moto_delivery': 'Motorcycle Delivery',
    'services.moto_delivery_desc': 'Express delivery by motorcycle taxi',
    'services.moto_delivery_price': 'From 1500 CDF',
    'services.moto_delivery_feat1': '30min delivery',
    'services.moto_delivery_feat2': 'Avoids traffic',
    'services.moto_delivery_feat3': 'Real-time tracking',
    'services.utility_vehicles': 'Utility Vehicles',
    'services.utility_vehicles_desc': 'Pickup trucks for large packages',
    'services.utility_vehicles_price': 'From 5000 CDF',
    'services.utility_vehicles_feat1': 'Large capacity',
    'services.utility_vehicles_feat2': 'Loading assistance',
    'services.utility_vehicles_feat3': 'Moving services',
    'services.advance_booking': 'Advance Booking',
    'services.advance_booking_desc': 'Plan your trips in advance',
    'services.advance_booking_price': 'Standard rate + 500 CDF',
    'services.advance_booking_feat1': 'Flexible planning',
    'services.advance_booking_feat2': 'Guaranteed availability',
    'services.advance_booking_feat3': 'Automatic reminder',
    'services.popular': 'Popular',
    'services.book_now': 'Book now',
    'services.cta_title': 'Ready to get started?',
    'services.cta_subtitle': 'Download the app or become a driver partner',
    'services.download_app': 'Download App',
    'services.become_driver_partner': 'Become a Driver',
    
    // Features
    'features.title': 'Advanced Features',
    'features.subtitle': 'An exceptional user experience',
    'features.title_prefix': 'Why choose',
    'features.title_brand': 'Kwenda',
    'features.realtime.title': 'Real-time Tracking',
    'features.realtime.description': 'Track your rides and deliveries live',
    'features.payment.title': 'Secure Payments',
    'features.payment.description': 'Multiple local payment options',
    'features.multilingual.title': 'Multilingual',
    'features.multilingual.description': 'Interface in French and local languages',
    'features.support.title': '24/7 Support',
    'features.support.description': 'Customer assistance available around the clock',
    'features.stats_cities': '4+ Cities',
    'features.maximum_security': 'Maximum Security',
    'features.maximum_security_desc': 'Complete protection of your personal data and transactions',
    'features.stats_support': '24/7 Support',
    'features.stats_vehicles': 'Vehicles',
    'features.stats_eco': 'Eco-friendly',
    'features.eco_fleet': 'Eco-Friendly Fleet',
    'features.eco_fleet_desc': 'Environmentally friendly vehicles for sustainable transport',
    'features.alt_eco_car': 'Eco-friendly car',
    'features.smart_geolocation': 'Smart Geolocation',
    'features.smart_geolocation_desc': 'Precise and fast location for optimized routes',
    'features.alt_mobile_app': 'Mobile application',
    'features.certified_drivers': 'Certified Drivers',
    'features.certified_drivers_desc': 'Verified and trained professional drivers',
    'features.alt_professional_drivers': 'Professional drivers',
    'features.flexible_payments': 'Flexible Payments',
    'features.flexible_payments_desc': 'Multiple payment options adapted for Africa',
    'features.shared_rides': 'Shared Rides',
    'features.shared_rides_desc': 'Save money by sharing rides with other passengers',
    
    // Support
    'support.title': 'Customer Support',
    'support.subtitle': 'We are here to help you',
    'support.contact': 'Contact Us',
    'support.faq': 'FAQ',
    'support.help': 'Help Center',
    'support.contact_us': 'Contact Us',
    'support.phone': 'Phone',
    'support.phone_desc': 'Call us directly',
    'support.contact_phone': '+243 970 123 456',
    'support.availability_phone': 'Available 24/7',
    'support.email': 'Email',
    'support.email_desc': 'Send us a message',
    'support.contact_email': 'support@kwenda.cd',
    'support.availability_email': 'Response within 2h',
    'support.chat': 'Live Chat',
    'support.chat_desc': 'Chat with an agent',
    'support.contact_chat': 'Start a conversation',
    'support.availability_chat': 'Online now',
    'support.create_ticket': 'Create Ticket',
    'support.category_required': 'Category required',
    'support.select_category': 'Select a category',
    'support.priority': 'Priority',
    'support.priority_low': 'Low',
    'support.priority_medium': 'Medium',
    'support.priority_high': 'High',
    'support.priority_urgent': 'Urgent',
    'support.subject': 'Subject',
    'support.subject_required': 'Subject required',
    'support.subject_placeholder': 'Briefly describe your issue',
    'support.description': 'Description',
    'support.description_required': 'Description required',
    'support.description_placeholder': 'Describe your issue in detail...',
    'support.send_ticket': 'Send Ticket',
    'support.ticket_sent': 'Ticket Sent',
    'support.ticket_sent_desc': 'Your request has been submitted successfully',
    'support.available_soon': 'Available Soon',
    'support.status_open': 'Open',
    'support.status_in_progress': 'In Progress',
    'support.status_resolved': 'Resolved',
    'support.status_closed': 'Closed',
    'support.categories.general': 'General',
    'support.categories.technical': 'Technical',
    'support.categories.billing': 'Billing',
    'support.categories.account': 'Account',
    
    // Escrow/Secure Vault - English
    'escrow.title': 'Secure Vault',
    'escrow.subtitle': 'Your payments are protected until delivery confirmation',
    'escrow.back_home': 'Back to home',
    'escrow.no_transactions': 'No secure transactions',
    'escrow.description': 'Your payments are protected',
    'escrow.balance': 'Available balance',
    'escrow.consultation_balance': 'Available for withdrawal',
    'escrow.secure_transactions': 'Protected transactions',
    'escrow.pending_confirmation': 'Pending confirmation',
    'escrow.all_tabs': 'All',
    'escrow.secured_tabs': 'Secured',
    'escrow.released_tabs': 'Released',
    'escrow.pending_tabs': 'Pending',
    'escrow.status_held': 'Secured',
    'escrow.status_completed': 'Released',
    'escrow.status_disputed': 'Disputed',
    'escrow.status_refunded': 'Refunded',
    'escrow.status_timeout': 'Expired',
    'escrow.delivery_confirmed': 'Delivery confirmed',
    'escrow.delivery_confirmed_desc': 'Funds have been released successfully',
    'escrow.error_title': 'Error',
    'escrow.error_load_vault': 'Unable to load vault data',
    'escrow.error_confirmation': 'Error during confirmation',
    'escrow.confirm_delivery': 'Confirm receipt',
    'escrow.release_funds': 'Release funds',
    'escrow.vault_transaction_id': 'Transaction #',
    'escrow.transaction_role_buyer': 'Buyer',
    'escrow.transaction_role_seller': 'Seller',
    'escrow.transaction_role_driver': 'Driver',
    'escrow.secured_amount': 'Secured amount',
    'escrow.seller_earnings': 'Your earnings',
    'escrow.delivery_fee': 'Delivery fee',
    'escrow.view_details': 'Details',
    'escrow.funds_released_on': 'Funds released on',
    'escrow.auto_release_on': 'Auto release on',
    'escrow.expires_soon': 'Expires soon',
    
    // System
    'system.loading': 'Loading...',
    'system.error': 'Error',
    'system.success': 'Success',
    'system.error_occurred': 'An error occurred',
    'system.try_again': 'Try again',
    'system.no_data': 'No data available',
    
    // Payment
    'payment.method': 'Mobile Payment',
    'payment.secure': 'Secure Payment',
    'payment.options': 'Payment Options',
    
    // Marketplace Basic
    'marketplace.new_badge': 'New',
    'marketplace.trending': 'Trending',
    
    // Lottery
    'lottery.free_lottery': 'Free Lottery',
    'lottery.win_credits': 'Win Credits',
    'lottery.daily_draw': 'Daily Draw',

    // Client Navigation
    'client.nav.home': 'Home',
    'client.nav.activity': 'Activity',
    'client.nav.account': 'Account',

    // User Profile
    'profile.loading': 'Loading profile...',
    'profile.edit_name': 'Edit name',
    'profile.edit_phone': 'Edit phone',
    'profile.history': 'History',
    'profile.addresses': 'My addresses',
    'profile.support': 'Support',
    'profile.settings': 'Settings',
    'profile.logout': 'Logout',
    'profile.logout_confirm': 'Confirm logout',
    'profile.save': 'Save',
    'profile.cancel': 'Cancel',
    'profile.enter_name': 'Enter your name',
    'profile.enter_phone': 'Enter your phone',

    // Transport
    'transport.destination': 'Destination',
    'transport.vehicle_type': 'Vehicle type',
    'transport.confirm_booking': 'Confirm booking',
    'transport.position_detected': 'Position detected',
    'transport.geolocation_failed': 'Geolocation failed',
    'transport.pickup_location': 'Pickup location',
    'transport.book_ride': 'Book a ride',
    'transport.searching_driver': 'Searching for driver...',
    'transport.driver_found': 'Driver found',
    'transport.cancel_ride': 'Cancel ride',
    'transport.ride_in_progress': 'Ride in progress',

    // Delivery
    'delivery.destination': 'Delivery location',
    'delivery.service_type': 'Service type',
    'delivery.confirmation': 'Confirmation',
    'delivery.where_deliver': 'Where should we deliver your package?',
    'delivery.package_type': 'Package type',
    'delivery.estimated_price': 'Estimated price',
    'delivery.pickup_location': 'Pickup location',
    'delivery.express_delivery': 'Express Delivery',
    'delivery.fast_reliable': 'Fast and reliable delivery service',
    'delivery.where_pickup': 'Where to pickup the package?',
    'delivery.where_delivery': 'Where to deliver the package?',
    'delivery.contact_info': 'Contact information',

    // Driver Navigation
    'driver.rides': 'Rides',
    'driver.deliveries': 'Deliveries',

    // Transport additional keys
    'transport.enter_locations': 'Please enter pickup and destination locations',
    'transport.booking_error': 'Error creating booking',

    // Activity History
    'activity.title': 'Ride History',
    'activity.loading': 'Loading history...',
    'activity.no_rides': 'No rides found',
    'activity.driver': 'Driver',
    'activity.completed': 'Completed',
    'activity.pending': 'Pending',
    'activity.today': 'Today',
    'activity.yesterday': 'Yesterday',
    'activity.price_undefined': 'Price undefined',

    // Marketplace Client
    'marketplace.my_activities': 'My Activities',
    'marketplace.my_purchases': 'My Purchases',
    'marketplace.my_sales': 'My Sales',
    'marketplace.quantity': 'Quantity',
    'marketplace.phone': 'Phone',
    'marketplace.add_to_cart': 'Add to cart',
    'marketplace.product_added': 'Product added',
    'marketplace.product_added_desc': '{0} has been added to cart',
    'marketplace.location_required': 'Location required',
    'marketplace.location_required_desc': 'Enable geolocation to calculate delivery',
    'marketplace.orders_created': 'Orders created',
    'marketplace.orders_created_desc': 'Your orders have been sent to sellers',
    'marketplace.your_position': 'Your position',
    'marketplace.products_count': 'products',
    'marketplace.featured': 'Featured',
    'marketplace.popular': 'Popular',
    'marketplace.nearby': 'Nearby',
    'marketplace.error_load': 'Failed to load products',
    'marketplace.unknown_seller': 'Unknown seller',

    // Profile Messages
    'profile.updated': 'Profile updated',
    'profile.updated_desc': 'Your information has been updated successfully',
    'profile.name_updated': 'Name updated',
    'profile.name_updated_desc': 'Your name has been updated successfully',
    'profile.phone_updated': 'Phone updated',
    'profile.phone_updated_desc': 'Your phone number has been updated successfully',
    'profile.logout_success': 'Logout successful',
    'profile.logout_success_desc': 'You have been logged out successfully',
    'profile.error_update': 'Failed to update profile',
    'profile.error_update_name': 'Failed to update name',
    'profile.error_update_phone': 'Failed to update phone',
    'profile.error_logout': 'Failed to logout'
  },
  
  kg: {
    // Navigation - Kikongo
    'nav.home': 'Nzo',
    'nav.services': 'Kisalu',
    'nav.about': 'Mukuatuetu',
    'nav.contact': 'Tubakana',
    'nav.login': 'Kota',
    'nav.signup': 'Sumina',
    
    // Common - Kikongo
    'common.loading': 'Yina ku kanga...',
    'common.error': 'Nkama',
    'common.success': 'Malonga',
    'common.cancel': 'Lemba',
    'common.confirm': 'Ndinga',
    'common.save': 'Bika',
    'common.edit': 'Yambula',
    'common.delete': 'Boma',
    'common.view_all': 'Tala yonso',
    'common.add': 'Bakisa',
    'common.remove': 'Longola',
    'common.close': 'Kanga',
    'common.back': 'Vuanda',
    'common.next': 'Kuesi',
    'common.previous': 'Kuna',
    
    // Auth
    'auth.login': 'Kota',
    'auth.register': 'Sumina',
    'auth.email': 'Email',
    'auth.password': 'Code ya lukutuka',
    'auth.continue': 'Kwenda',
    'auth.logout': 'Fuluka',
    
    // Role Selection
    'role.client': 'Nkuenda',
    'role.driver': 'Mvuzi',
    'role.partner': 'Nkundi',
    'role.admin': 'Ntuadisi',
    'role.select': 'Songa',
    'role.client_desc': 'Vova mabuela ye mavanga',
    'role.driver_desc': 'Kala mvuzi ya nkundi',
    'role.partner_desc': 'Salela bavuzi beno',
    
    // Support
    'support.title': 'Sadila ya ba clients',
    'support.subtitle': 'Beto tuena fika mu kusadila beno',
    'support.contact': 'Tubakana',
    'support.phone': 'Telefone',
    'support.email': 'Email',
    'support.chat': 'Mono mongo',
    'support.create_ticket': 'Sala ticket',
    'support.subject': 'Makambu',
    'support.description': 'Malongi',
    'support.send_ticket': 'Tuma ticket',
    'support.available_soon': 'Kenda ye mingi ko',
    'escrow.title': 'Coffre ya mbanza',
    'escrow.no_transactions': 'Transaction ya mbanza yafulu ko',
    'system.loading': 'Yina ku kanga...',
    'system.error': 'Nkama',
    'system.success': 'Malonga',

    // Client Navigation
    'client.nav.home': 'Nzo',
    'client.nav.activity': 'Kisalu',
    'client.nav.account': 'Kôntu'
  },
  
  lua: {
    // Navigation - Tshiluba  
    'nav.home': 'Muetu',
    'nav.services': 'Bisalu',
    'nav.about': 'Mukuatuetu',
    'nav.contact': 'Kutusungila',
    'nav.login': 'Kukota',
    'nav.signup': 'Kusumina',
    
    // Common - Tshiluba
    'common.loading': 'Kuntala...',
    'common.error': 'Nshimu',
    'common.success': 'Malonga',
    'common.cancel': 'Kulemba',
    'common.confirm': 'Kuñingisha',
    'common.save': 'Kubika',
    'common.edit': 'Kusongola',
    'common.delete': 'Kuñola',
    'common.view_all': 'Kumona bionso',
    'common.add': 'Kubakisha',
    'common.remove': 'Kulongola',
    'common.close': 'Kukanga',
    'common.back': 'Kuvuanda',
    'common.next': 'Kudiata',
    'common.previous': 'Kuna',
    
    // Auth
    'auth.login': 'Kukota',
    'auth.register': 'Kusumina',
    'auth.email': 'Email',
    'auth.password': 'Code ya lukutuka',
    'auth.continue': 'Kuenda nayi',
    'auth.logout': 'Kufuluka',
    
    // Role Selection
    'role.client': 'Nkaji',
    'role.driver': 'Mvuzi',
    'role.partner': 'Nkundi',
    'role.admin': 'Ntuadisi',
    'role.select': 'Kusonga',
    'role.client_desc': 'Kuvova mabuela ne mavanga',
    'role.driver_desc': 'Kukala mvuzi wa nkundi',
    'role.partner_desc': 'Kusala bavuzi banu',
    
    // Support
    'support.title': 'Kusadila ba clients',
    'support.subtitle': 'Twena apa mukusadila',
    'support.contact': 'Kutusungila',
    'support.phone': 'Telefone',
    'support.email': 'Email',
    'support.chat': 'Kusolola',
    'support.create_ticket': 'Kusala ticket',
    'support.subject': 'Makambu',
    'support.description': 'Malongi',
    'support.send_ticket': 'Kutuma ticket',
    'support.available_soon': 'Kufika ye dikoloba',
    'escrow.title': 'Coffre ya mbanza ya KwendaPay',
    'escrow.no_transactions': 'Transaction ya mbanza yafulu ko',
    'system.loading': 'Kuntala...',
    'system.error': 'Nshimu',
    'system.success': 'Malonga',

    // Client Navigation
    'client.nav.home': 'Muetu',
    'client.nav.activity': 'Bisalu',
    'client.nav.account': 'Kôntu'
  },
  
  sw: {
    // Navigation - Kiswahili
    'nav.home': 'Nyumbani',
    'nav.services': 'Huduma',
    'nav.about': 'Kuhusu',
    'nav.contact': 'Mawasiliano',
    'nav.login': 'Ingia',
    'nav.signup': 'Jisajili',
    
    // Common - Kiswahili
    'common.loading': 'Inapakia...',
    'common.error': 'Kosa',
    'common.success': 'Imefanikiwa',
    'common.cancel': 'Ghairi',
    'common.confirm': 'Thibitisha',
    'common.save': 'Hifadhi',
    'common.edit': 'Hariri',
    'common.delete': 'Futa',
    'common.view_all': 'Ona zote',
    'common.add': 'Ongeza',
    'common.remove': 'Ondoa',
    'common.close': 'Funga',
    'common.back': 'Rudi',
    'common.next': 'Ifuatayo',
    'common.previous': 'Iliyopita',
    
    // Auth
    'auth.login': 'Ingia',
    'auth.register': 'Jisajili',
    'auth.email': 'Barua pepe',
    'auth.password': 'Nywila',
    'auth.continue': 'Endelea',
    'auth.logout': 'Toka',
    'auth.forgot_password': 'Umesahau nywila',
    'auth.reset_password': 'Anza upya nywila',
    'auth.confirm_password': 'Thibitisha nywila',
    'auth.create_account': 'Fungua akaunti',
    
    // Role Selection
    'role.client': 'Mteja',
    'role.driver': 'Dereva',
    'role.partner': 'Mshirika', 
    'role.admin': 'Msimamizi',
    'role.select': 'Chagua jukumu',
    'role.client_desc': 'Agiza safari na mizigo',
    'role.driver_desc': 'Kuwa dereva mshirika',
    'role.partner_desc': 'Simamia gari zako',
    
    // Home/Recent Places
    'home.recent_places': 'Maeneo ya hivi karibuni',
    'home.no_recent_places': 'Hakuna mahali pa hivi karibuni',
    'home.recent_places_help': 'Maeneo yako ya hivi karibuni yataonekana hapa',
    'home.add_current_location': 'Ongeza mahali pangu',
    'home.use_current_location': 'Tumia mahali pangu sasa',
    'home.set_as_home': 'Weka kama nyumbani',
    'home.set_as_work': 'Weka kama kazini',
    'home.home_label': 'Nyumbani',
    'home.work_label': 'Kazini',
    'home.remove_place': 'Ondoa mahali hapa',
    'home.search.placeholder': 'Unataka kwenda wapi?',
    'home.services.taxi': 'Usafiri',
    'home.services.delivery': 'Uwasilishaji',
    'home.services.shopping': 'Ununuzi',
    'home.services.rental': 'Ukodishaji',
    'home.services.lottery': 'Bahati nasibu',
    
    // Toast messages
    'toast.place_removed': 'Mahali pameondolewa',
    'toast.place_removed_desc': 'Mahali pameondolewa kwenye maeneo yako ya hivi karibuni',
    'toast.location_added': 'Mahali pameongezwa',
    'toast.location_added_desc': 'Mahali pako pa sasa pameongezwa kwenye maeneo ya hivi karibuni',
    'toast.location_error': 'Kosa',
    'toast.location_error_desc': 'Imeshindwa kupata mahali pako pa sasa',
    'toast.home_set': 'Nyumbani imewekwa',
    'toast.home_set_desc': '{0} sasa ni nyumbani kwako',
    'toast.work_set': 'Kazini imewekwa',
    'toast.work_set_desc': '{0} sasa ni kazini kwako',
    
    // Hero Section
    'hero.title': 'Usafiri na Uwasilishaji DRC',
    'hero.subtitle': 'Suluhisho lako kamili la uhamishaji wa mijini',
    'hero.description': 'Kutoka safari za VTC hadi uwasilishaji wa haraka, gundua Kwenda - programu inayobadilisha usafiri katika Jamhuri ya Kidemokrasia ya Kongo.',
    'hero.cta_start': 'Anza sasa',
    'hero.cta_demo': 'Ona onyesho',
    'hero.stats.cities': 'Miji hai',
    'hero.stats.available': 'Inapatikana 24/7',
    'hero.stats.payment': 'Malipo salama',
    'hero.stats.support': 'Huduma kwa wateja',
    'hero.kwenda_taxi': 'Kwenda Taxi',
    'hero.made_in_rdc': 'Imetengenezwa DRC',
    'hero.innovation_excellence': 'Uvumbuzi na Ubora',
    'hero.tagline': 'Mshirika wako wa uhamishaji Afrika',
    'hero.start_now': 'Anza sasa',
    'hero.view_demo': 'Ona onyesho',
    'hero.transport_types': 'Aina za usafiri',
    'hero.customer_service': 'Huduma kwa wateja',
    'hero.available_24_7': 'Inapatikana 24/7',
    'hero.kwenda_pay': 'KwendaPay',
    'hero.location': 'Kinshasa, Lubumbashi, Kolwezi',
    'hero.alt_text': 'Huduma ya usafiri Kwenda Taxi DRC',
    
    // Services
    'services.title': 'Huduma Zetu',
    'services.subtitle': 'Suluhisho kamili kwa mahitaji yako yote ya uhamishaji',
    'services.vtc.title': 'VTC na Usafiri',
    'services.vtc.description': 'Safari za kibinafsi na za pamoja',
    'services.delivery.title': 'Uwasilishaji wa Haraka',
    'services.delivery.description': 'Uwasilishaji wa haraka na salama',
    'services.marketplace.title': 'Soko la Kielektroniki',
    'services.marketplace.description': 'Duka la mtandaoni lililoungwa mkono',
    'services.rental.title': 'Ukodishaji wa Magari',
    'services.rental.description': 'Kodisha magari kwa urahisi',
    'services.vtc_standard': 'VTC ya Kawaida',
    'services.vtc_standard_desc': 'Magari mazuri kwa safari zako za kila siku',
    'services.vtc_standard_price': 'Kuanzia 2000 CDF',
    'services.vtc_standard_feat1': 'Magari yenye baridi',
    'services.vtc_standard_feat2': 'Madereva wa kitaaluma',
    'services.vtc_standard_feat3': 'Bei wazi',
    'services.vtc_luxe': 'VTC ya Kifahari',
    'services.vtc_luxe_desc': 'Magari ya hali ya juu kwa ustarehe wa kipekee',
    'services.vtc_luxe_price': 'Kuanzia 4000 CDF',
    'services.vtc_luxe_feat1': 'Magari ya kifahari',
    'services.vtc_luxe_feat2': 'Huduma ya VIP',
    'services.vtc_luxe_feat3': 'Maji ya bure',
    'services.shared_rides': 'Safari za Pamoja',
    'services.shared_rides_desc': 'Shiriki safari yako na kupunguza gharama',
    'services.shared_rides_price': 'Kuanzia 1000 CDF',
    'services.shared_rides_feat1': 'Kiuchumi',
    'services.shared_rides_feat2': 'Mazingira mazuri',
    'services.shared_rides_feat3': 'Kijamii',
    'services.moto_delivery': 'Uwasilishaji wa Pikipiki',
    'services.moto_delivery_desc': 'Uwasilishaji wa haraka kwa pikipiki',
    'services.moto_delivery_price': 'Kuanzia 1500 CDF',
    'services.moto_delivery_feat1': 'Uwasilishaji dakika 30',
    'services.moto_delivery_feat2': 'Huepuka msongamano',
    'services.moto_delivery_feat3': 'Ufuatiliaji wa muda halisi',
    'services.utility_vehicles': 'Magari ya Mizigo',
    'services.utility_vehicles_desc': 'Malori kwa vifurushi vikubwa',
    'services.utility_vehicles_price': 'Kuanzia 5000 CDF',
    'services.utility_vehicles_feat1': 'Uwezo mkubwa',
    'services.utility_vehicles_feat2': 'Msaada wa kupakia',
    'services.utility_vehicles_feat3': 'Huduma za kuhamisha',
    'services.advance_booking': 'Uhifadhi wa Mapema',
    'services.advance_booking_desc': 'Panga safari zako mapema',
    'services.advance_booking_price': 'Bei ya kawaida + 500 CDF',
    'services.advance_booking_feat1': 'Kupanga kwa urahisi',
    'services.advance_booking_feat2': 'Uhakika wa upatikanaji',
    'services.advance_booking_feat3': 'Ukumbusho otomatiki',
    'services.popular': 'Maarufu',
    'services.book_now': 'Agiza sasa',
    'services.cta_title': 'Uko tayari kuanza?',
    'services.cta_subtitle': 'Pakua programu au kuwa mshirika dereva',
    'services.download_app': 'Pakua Programu',
    'services.become_driver_partner': 'Kuwa Dereva',
    
    // Features
    'features.title': 'Vipengele vya Juu',
    'features.subtitle': 'Uzoefu wa mtumiaji wa kipekee',
    'features.title_prefix': 'Kwa nini chagua',
    'features.title_brand': 'Kwenda',
    'features.realtime.title': 'Ufuatiliaji wa wakati halisi',
    'features.realtime.description': 'Fuatilia safari na mizigo yako moja kwa moja',
    'features.payment.title': 'Malipo salama',
    'features.payment.description': 'Chaguo nyingi za malipo za ndani',
    'features.multilingual.title': 'Lugha nyingi',
    'features.multilingual.description': 'Kiolesura kwa Kifaransa na lugha za ndani',
    'features.support.title': 'Msaada 24/7',
    'features.support.description': 'Msaada wa wateja unapatikana daima',
    'features.stats_cities': 'Miji 4+',
    'features.maximum_security': 'Usalama wa Juu',
    'features.maximum_security_desc': 'Ulinzi kamili wa data yako ya kibinafsi na miamala',
    'features.stats_support': 'Msaada 24/7',
    'features.stats_vehicles': 'Magari',
    'features.stats_eco': 'Mazingira mazuri',
    'features.eco_fleet': 'Gari za Mazingira Mazuri',
    'features.eco_fleet_desc': 'Magari yanayohifadhi mazingira kwa usafiri endelevu',
    'features.alt_eco_car': 'Gari la mazingira mazuri',
    'features.smart_geolocation': 'Eneo Mahiri',
    'features.smart_geolocation_desc': 'Utambuzi sahihi na wa haraka kwa njia bora',
    'features.alt_mobile_app': 'Programu ya simu',
    'features.certified_drivers': 'Madereva Wenye Cheti',
    'features.certified_drivers_desc': 'Madereva wa kitaaluma waliothibitishwa na kufundishwa',
    'features.alt_professional_drivers': 'Madereva wa kitaaluma',
    'features.flexible_payments': 'Malipo ya Kubadilika',
    'features.flexible_payments_desc': 'Chaguo nyingi za malipo zilizobinafsishwa kwa Afrika',
    'features.shared_rides': 'Safari za Pamoja',
    'features.shared_rides_desc': 'Okoa pesa kwa kushiriki safari na abiria wengine',
    
    // Support
    'support.title': 'Msaada wa Wateja',
    'support.subtitle': 'Tuko hapa kukusaidia',
    'support.contact': 'Wasiliana nasi',
    'support.faq': 'Maswali Yanayoulizwa Mara kwa Mara',
    'support.help': 'Kituo cha Msaada',
    'support.contact_us': 'Wasiliana nasi',
    'support.phone': 'Simu',
    'support.phone_desc': 'Tupigie moja kwa moja',
    'support.contact_phone': '+243 970 123 456',
    'support.availability_phone': 'Inapatikana 24/7',
    'support.email': 'Barua pepe',
    'support.email_desc': 'Tutumie ujumbe',
    'support.contact_email': 'support@kwenda.cd',
    'support.availability_email': 'Jibu ndani ya masaa 2',
    'support.chat': 'Mazungumzo ya moja kwa moja',
    'support.chat_desc': 'Zungumza na wakala',
    'support.contact_chat': 'Anza mazungumzo',
    'support.availability_chat': 'Mtandaoni sasa',
    'support.create_ticket': 'Tengeneza tiketi',
    'support.category_required': 'Jamii inahitajika',
    'support.select_category': 'Chagua jamii',
    'support.priority': 'Kipaumbele',
    'support.priority_low': 'Chini',
    'support.priority_medium': 'Kati',
    'support.priority_high': 'Juu',
    'support.priority_urgent': 'Dharura',
    'support.subject': 'Mada',
    'support.subject_required': 'Mada inahitajika',
    'support.subject_placeholder': 'Elezea tatizo lako kwa ufupi',
    'support.description': 'Maelezo',
    'support.description_required': 'Maelezo yanahitajika',
    'support.description_placeholder': 'Elezea tatizo lako kwa undani...',
    'support.send_ticket': 'Tuma tiketi',
    'support.ticket_sent': 'Tiketi imetumwa',
    'support.ticket_sent_desc': 'Ombi lako limepokelewa kwa mafanikio',
    'support.available_soon': 'Itapatikana hivi karibuni',
    'support.status_open': 'Imefunguliwa',
    'support.status_in_progress': 'Inaendelea',
    'support.status_resolved': 'Imetatuliwa',
    'support.status_closed': 'Imefungwa',
    'support.categories.general': 'Jumla',
    'support.categories.technical': 'Kiufundi',
    'support.categories.billing': 'Bili',
    'support.categories.account': 'Akaunti',
    
    // Escrow/Secure Vault
    'escrow.title': 'Coffre-fort Sécurisé',
    'escrow.subtitle': 'Malipo yako yamelindwa mpaka uthibitisho wa uwasilishaji',
    'escrow.back_home': 'Rudi nyumbani',
    'escrow.no_transactions': 'Hakuna muamala wa salama',
    'escrow.description': 'Malipo yako yamelindwa',
    'escrow.balance': 'Salio lililopatikana',
    'escrow.consultation_balance': 'Linapatikana kwa utoaji',
    'escrow.secure_transactions': 'Miamala iliyolindwa',
    'escrow.pending_confirmation': 'Inasubiri uthibitisho',
    'escrow.all_tabs': 'Zote',
    'escrow.secured_tabs': 'Zilizolindwa',
    'escrow.released_tabs': 'Zilizoachiliwa',
    'escrow.pending_tabs': 'Zinazosubiri',
    'escrow.status_held': 'Imelindwa',
    'escrow.status_completed': 'Imeachiliwa',
    'escrow.status_disputed': 'Ugomvi',
    'escrow.status_refunded': 'Imerudishwa',
    'escrow.status_timeout': 'Muda umekwisha',
    'escrow.delivery_confirmed': 'Uwasilishaji umethibitishwa',
    'escrow.delivery_confirmed_desc': 'Fedha zimeachiliwa kwa mafanikio',
    'escrow.error_title': 'Kosa',
    'escrow.error_load_vault': 'Imeshindwa kupakia data ya coffre',
    'escrow.error_confirmation': 'Kosa wakati wa uthibitisho',
    'escrow.confirm_delivery': 'Thibitisha upokezi',
    'escrow.release_funds': 'Achilia fedha',
    'escrow.vault_transaction_id': 'Muamala #',
    'escrow.transaction_role_buyer': 'Mnunuzi',
    'escrow.transaction_role_seller': 'Muuza',
    'escrow.transaction_role_driver': 'Mleta',
    'escrow.secured_amount': 'Kiasi kilicholindwa',
    'escrow.seller_earnings': 'Faida yako',
    'escrow.delivery_fee': 'Ada ya uwasilishaji',
    'escrow.view_details': 'Maelezo',
    'escrow.funds_released_on': 'Fedha zilizoachiliwa',
    'escrow.auto_release_on': 'Kuachilia otomatiki',
    'escrow.expires_soon': 'Inaisha hivi karibuni',
    
    // System
    'system.loading': 'Inapakia...',
    'system.error': 'Kosa',
    'system.success': 'Imefanikiwa',
    'system.error_occurred': 'Kosa limetokea',
    'system.try_again': 'Jaribu tena',
    'system.no_data': 'Hakuna data inayopatikana',
    'system.network_error': 'Kosa la mtandao',
    'system.server_error': 'Kosa la seva',
    'system.maintenance': 'Matengenezo',
    'system.update_required': 'Usasishaji unahitajika',
    'system.app_version': 'Toleo la programu',
    'system.last_updated': 'Imesasishwa mwisho',
    
    // Payment
    'payment.method': 'Pesa za simu',
    'payment.secure': 'Malipo salama',
    'payment.options': 'Chaguo za malipo',
    'payment.mobile_money': 'Pesa za simu',
    'payment.bank_transfer': 'Uhamishaji wa benki',
    'payment.card_payment': 'Malipo ya kadi',
    'payment.cash_payment': 'Malipo ya taslimu',
    'payment.airtel_money': 'Airtel Money',
    'payment.orange_money': 'Orange Money',
    'payment.mpesa': 'M-Pesa',
    'payment.ecocash': 'EcoCash',
    'payment.pending': 'Inasubiri',
    'payment.processing': 'Inachakatwa',
    'payment.successful': 'Malipo yamefanikiwa',
    'payment.failed': 'Malipo yameshindwa',
    'payment.cancelled': 'Malipo yameghairiwa',
    'payment.refunded': 'Pesa zimerudishwa',
    'payment.expired': 'Muda umekwisha',
    'payment.amount': 'Kiasi',
    'payment.currency': 'Sarafu',
    'payment.exchange_rate': 'Kiwango cha ubadilishaji',
    'payment.service_fee': 'Ada ya huduma',
    'payment.total_amount': 'Kiasi cha jumla',
    'payment.reference': 'Rejea',
    'payment.confirmation_code': 'Msimbo wa uthibitisho',
    
    // Marketplace Basic
    'marketplace.new_badge': 'Mpya',
    'marketplace.trending': 'Mzuri',
    'marketplace.title': 'Soko la Kielektroniki',
    'marketplace.browse_products': 'Vinjari Bidhaa',
    'marketplace.featured': 'Zilizochanikiwa',
    'marketplace.popular': 'Zinazopendwa',
    'marketplace.nearby': 'Karibu Nawe',
    'marketplace.categories': 'Aina za Bidhaa',
    'marketplace.search_products': 'Tafuta Bidhaa',
    'marketplace.product_details': 'Maelezo ya Bidhaa',
    'marketplace.seller_info': 'Habari za Muuza',
    'marketplace.product_reviews': 'Mapitio ya Bidhaa',
    'marketplace.add_to_cart': 'Weka kwenye Kikapu',
    'marketplace.buy_now': 'Nunua Sasa',
    'marketplace.add_to_wishlist': 'Ongeza kwenye Orodha ya Matamanio',
    'marketplace.share_product': 'Shiriki Bidhaa',
    'marketplace.contact_seller': 'Wasiliana na Muuza',
    'marketplace.view_shop': 'Ona Duka',
    'marketplace.quantity': 'Idadi',
    'marketplace.price': 'Bei',
    'marketplace.discount': 'Punguzo',
    'marketplace.original_price': 'Bei ya Asili',
    'marketplace.final_price': 'Bei ya Mwisho',
    'marketplace.shipping_cost': 'Gharama ya Usafirishaji',
    'marketplace.availability': 'Upatikanaji',
    'marketplace.in_stock': 'Iko Hifadhini',
    'marketplace.out_of_stock': 'Haikupatikani',
    'marketplace.limited_stock': 'Hifadhi Ndogo',
    'marketplace.cart': 'Kikapu',
    'marketplace.cart_items': 'Vitu vya Kikapu',
    'marketplace.cart_total': 'Jumla ya Kikapu',
    'marketplace.checkout': 'Maliza Ununuzi',
    'marketplace.remove_item': 'Ondoa Kitu',
    'marketplace.update_quantity': 'Sasisha Idadi',
    'marketplace.empty_cart': 'Kikapu Tupu',
    'marketplace.continue_shopping': 'Endelea na Ununuzi',
    'marketplace.order_summary': 'Muhtasari wa Agizo',
    'marketplace.order_total': 'Jumla ya Agizo',
    'marketplace.order_placed': 'Agizo Limeagizwa',
    'marketplace.order_confirmed': 'Agizo Limethibitishwa',
    'marketplace.order_shipped': 'Agizo Limetumwa',
    'marketplace.order_delivered': 'Agizo Limefikishwa',
    'marketplace.order_cancelled': 'Agizo Limeghairiwa',
    'marketplace.seller': 'Muuza',
    'marketplace.seller_rating': 'Ukadiriaji wa Muuza',
    'marketplace.seller_reviews': 'Mapitio ya Muuza',
    'marketplace.verified_seller': 'Muuza Aliyethibitishwa',
    'marketplace.new_seller': 'Muuza Mpya',
    'marketplace.top_seller': 'Muuza Bora',
    'marketplace.ratings': 'Ukadiriaji',
    'marketplace.review': 'Pitio',
    'marketplace.write_review': 'Andika Pitio',
    'marketplace.rate_product': 'Kadiri Bidhaa',
    'marketplace.helpful_review': 'Pitio la Kusaidia',
    'marketplace.verified_purchase': 'Ununuzi Uliothibitishwa',
    'marketplace.my_activities': 'Shughuli Zangu',
    'marketplace.my_purchases': 'Ununuzi Wangu',
    'marketplace.my_sales': 'Mauzo Yangu',
    'marketplace.phone': 'Simu',
    'marketplace.product_added': 'Bidhaa imeongezwa',
    'marketplace.product_added_desc': '{0} imeongezwa kwenye kikapu',
    'marketplace.location_required': 'Eneo linahitajika',
    'marketplace.location_required_desc': 'Washa eneo ili kuhesabu uwasilishaji',
    'marketplace.orders_created': 'Maagizo yametengenezwa',
    'marketplace.orders_created_desc': 'Maagizo yako yametumwa kwa wauzaji',
    'marketplace.your_position': 'Eneo lako',
    'marketplace.products_count': 'bidhaa',
    'marketplace.error_load': 'Imeshindwa kupakia bidhaa',
    'marketplace.unknown_seller': 'Muuza asiyejulikana',
    
    // Lottery
    'lottery.free_lottery': 'Bahati nasibu ya bure',
    'lottery.win_credits': 'Shinda krediti',
    'lottery.daily_draw': 'Mchezo wa kila siku',
    'lottery.title': 'Bahati Nasibu',
    'lottery.weekly_draw': 'Mchezo wa kila wiki',
    'lottery.monthly_draw': 'Mchezo wa kila mwezi',
    'lottery.your_tickets': 'Tiketi zako',
    'lottery.available_tickets': 'Tiketi zinazopatikana',
    'lottery.free_tickets': 'Tiketi za bure',
    'lottery.purchased_tickets': 'Tiketi zilizounuliwa',
    'lottery.winning_numbers': 'Nambari za ushindi',
    'lottery.prizes': 'Zawadi',
    'lottery.winners': 'Washindi',
    'lottery.jackpot': 'Zawadi kubwa',
    'lottery.play_now': 'Cheza sasa',
    'lottery.check_results': 'Angalia matokeo',
    'lottery.claim_prize': 'Dai zawadi',
    'lottery.next_draw': 'Mchezo ujao',
    'lottery.draw_time': 'Wakati wa mchezo',

    // Client Navigation
    'client.nav.home': 'Nyumbani',
    'client.nav.activity': 'Shughuli', 
    'client.nav.account': 'Akaunti',

    // User Profile
    'profile.loading': 'Inapakia profaili...',
    'profile.edit_name': 'Hariri jina',
    'profile.edit_phone': 'Hariri simu',
    'profile.history': 'Historia',
    'profile.addresses': 'Anwani zangu',
    'profile.support': 'Msaada',
    'profile.settings': 'Mipangilio',
    'profile.logout': 'Toka',
    'profile.logout_confirm': 'Thibitisha kutoka',
    'profile.save': 'Hifadhi',
    'profile.cancel': 'Ghairi',
    'profile.enter_name': 'Ingiza jina lako',
    'profile.enter_phone': 'Ingiza simu yako',
    'profile.title': 'Profaili Yangu',
    'profile.personal_info': 'Habari za Kibinafsi',
    'profile.contact_details': 'Habari za Mawasiliano',
    'profile.preferences': 'Mapendeleo',
    'profile.security_settings': 'Mipangilio ya Usalama',
    'profile.notification_settings': 'Mipangilio ya Arifa',
    'profile.privacy_settings': 'Mipangilio ya Faragha',
    'profile.full_name': 'Jina Kamili',
    'profile.first_name': 'Jina la Kwanza',
    'profile.last_name': 'Jina la Mwisho',
    'profile.date_of_birth': 'Tarehe ya Kuzaliwa',
    'profile.gender': 'Jinsia',
    'profile.nationality': 'Utaifa',
    'profile.identity_number': 'Nambari ya Kitambulisho',
    'profile.profile_picture': 'Picha ya Profaili',
    'profile.phone_number': 'Nambari ya Simu',
    'profile.email_address': 'Anwani ya Barua Pepe',
    'profile.home_address': 'Anwani ya Nyumbani',
    'profile.work_address': 'Anwani ya Kazini',
    'profile.emergency_contact': 'Mawasiliano ya Dharura',
    'profile.change_password': 'Badilisha Nywila',
    'profile.two_factor_auth': 'Uthibitisho wa Hatua Mbili',
    'profile.login_history': 'Historia ya Kuingia',
    'profile.active_sessions': 'Vipindi Hai',
    'profile.delete_account': 'Futa Akaunti',
    'profile.deactivate_account': 'Zima Akaunti',
    'profile.ride_history': 'Historia ya Safari',
    'profile.delivery_history': 'Historia ya Mizigo',
    'profile.purchase_history': 'Historia ya Ununuzi',
    'profile.payment_history': 'Historia ya Malipo',
    'profile.transaction_history': 'Historia ya Miamala',
    'profile.earnings': 'Mapato',
    'profile.total_earnings': 'Mapato ya Jumla',
    'profile.monthly_earnings': 'Mapato ya Mwezi',
    'profile.weekly_earnings': 'Mapato ya Wiki',
    'profile.daily_earnings': 'Mapato ya Siku',
    'profile.completed_trips': 'Safari Zilizokamilika',
    'profile.ratings_received': 'Ukadiriaji Uliopokelewa',
    'profile.customer_feedback': 'Maoni ya Wateja',
    'profile.updated': 'Profaili imesasishwa',
    'profile.updated_desc': 'Habari zako zimesasishwa kwa mafanikio',
    'profile.name_updated': 'Jina limesasishwa',
    'profile.name_updated_desc': 'Jina lako limesasishwa kwa mafanikio',
    'profile.phone_updated': 'Simu imesasishwa',
    'profile.phone_updated_desc': 'Nambari yako ya simu imesasishwa kwa mafanikio',
    'profile.logout_success': 'Umetoka kwa mafanikio',
    'profile.logout_success_desc': 'Umetoka kwa mafanikio',
    'profile.error_update': 'Imeshindwa kusasisha profaili',
    'profile.error_update_name': 'Imeshindwa kusasisha jina',
    'profile.error_update_phone': 'Imeshindwa kusasisha simu',
    'profile.error_logout': 'Imeshindwa kutoka',

    // Activity History
    'activity.title': 'Historia ya Safari',
    'activity.loading': 'Inapakia historia...',
    'activity.no_rides': 'Hakuna safari iliyopatikana',
    'activity.driver': 'Dereva',
    'activity.completed': 'Imekamilika',
    'activity.pending': 'Inasubiri',
    'activity.today': 'Leo',
    'activity.yesterday': 'Jana',
    'activity.price_undefined': 'Bei haijafafanuliwa',
    
    // TRANSPORT & VTC (100+ keys)
    'transport.title': 'Usafiri',
    'transport.book_ride': 'Agiza Safari',
    'transport.book_now': 'Agiza Sasa',
    'transport.cancel_ride': 'Ghairi Safari',
    'transport.pickup_location': 'Mahali pa Kupanda',
    'transport.destination': 'Unakoenda',
    'transport.estimated_price': 'Bei ya Mkadirifu',
    'transport.estimated_time': 'Muda wa Mkadirifu',
    'transport.driver_arriving': 'Dereva Anakuja',
    'transport.driver_arrived': 'Dereva Amefika',
    'transport.trip_started': 'Safari Imeanza',
    'transport.trip_completed': 'Safari Imekamilika',
    'transport.rate_trip': 'Kadiri Safari',
    'transport.payment_confirmed': 'Malipo Yamethibitishwa',
    'transport.moto_taxi': 'Boda boda',
    'transport.taxi_voiture': 'Teksi ya Gari',
    'transport.taxi_bus': 'Matatu',
    'transport.bus_transco': 'Basi la Umma',
    'transport.private_car': 'Gari la Kibinafsi',
    'transport.shared_taxi': 'Teksi ya Pamoja',
    'transport.status.pending': 'Inasubiri',
    'transport.status.searching': 'Inatafuta dereva...',
    'transport.status.found': 'Dereva amepatikana',
    'transport.status.accepted': 'Imekubaliwa',
    'transport.status.arriving': 'Dereva anakuja',
    'transport.status.arrived': 'Dereva amefika',
    'transport.status.in_transit': 'Njiani',
    'transport.status.completed': 'Safiri imekamilika',
    'transport.status.cancelled': 'Imeghairiwa',
    'transport.status.driver_assigned': 'Dereva amepangiwa',
    'transport.driver_name': 'Jina la Dereva',
    'transport.vehicle_info': 'Habari za Gari',
    'transport.license_plate': 'Nambari ya Gari',
    'transport.contact_driver': 'Wasiliana na Dereva',
    'transport.driver_rating': 'Ukadiriaji wa Dereva',
    'transport.driver_experience': 'Uzoefu wa Dereva',
    'transport.trip_details': 'Maelezo ya Safari',
    'transport.trip_duration': 'Muda wa Safari',
    'transport.trip_distance': 'Umbali wa Safari',
    'transport.trip_route': 'Njia ya Safari',
    'transport.start_time': 'Wakati wa Kuanza',
    'transport.end_time': 'Wakati wa Kuisha',
    'transport.waiting_time': 'Muda wa Kusubiri',
    'transport.base_fare': 'Bei ya Msingi',
    'transport.distance_fare': 'Bei ya Umbali',
    'transport.time_fare': 'Bei ya Muda',
    'transport.surge_pricing': 'Bei ya Msongamano',
    'transport.total_fare': 'Bei ya Jumla',
    'transport.payment_due': 'Malipo Yanayohitajika',
    'transport.fare_breakdown': 'Mgawanyo wa Bei',
    
    // DELIVERY & PARCELS (80+ keys)
    'delivery.title': 'Uwasilishaji',
    'delivery.new_delivery': 'Uwasilishaji Mpya',
    'delivery.create_order': 'Tengeneza Agizo',
    'delivery.track_package': 'Fuatilia Kitu',
    'delivery.delivery_completed': 'Uwasilishaji Umekamilika',
    'delivery.proof_delivery': 'Uthibitisho wa Uwasilishaji',
    'delivery.mode.flash': 'Haraka',
    'delivery.mode.flex': 'Kawaida',
    'delivery.mode.maxicharge': 'Mizigo Mikubwa',
    'delivery.mode.cargo': 'Mizigo',
    'delivery.mode.express': 'Upesi',
    'delivery.mode.standard': 'Standard',
    'delivery.mode.same_day': 'Siku Ile Ile',
    'delivery.mode.next_day': 'Siku Ifuatayo',
    'delivery.express_delivery': 'Ufikiaji wa Haraka',
    'delivery.fast_reliable': 'Huduma ya ufikiaji wa haraka na ya kuaminika',
    'delivery.where_pickup': 'Wapi kuchukua kitu?',
    'delivery.where_delivery': 'Wapi kufikisha kitu?',
    'delivery.contact_info': 'Maelezo ya mawasiliano',
    'delivery.confirmation': 'Uthibitisho',
    'delivery.vehicle_type': 'Aina ya gari',
    'delivery.confirm_booking': 'Thibitisha uhifadhi',
    'delivery.position_detected': 'Mahali pamegundulika',
    'delivery.geolocation_failed': 'Kutambua mahali kumeshindwa',
    'delivery.book_ride': 'Weka safari',
    'delivery.searching_driver': 'Kutafuta dereva...',
    'delivery.driver_found': 'Dereva amepatikana',
    'delivery.cancel_ride': 'Ghairi safari',
    'delivery.ride_in_progress': 'Safari inaendelea',

    // Driver Navigation
    'driver.rides': 'Safari',
    'driver.deliveries': 'Ufikiaji',
    'delivery.package_details': 'Maelezo ya Kitu',
    'delivery.package_type': 'Aina ya Kitu',
    'delivery.package_weight': 'Uzito wa Kitu',
    'delivery.package_size': 'Ukubwa wa Kitu',
    'delivery.package_value': 'Thamani ya Kitu',
    'delivery.fragile_item': 'Kitu Chenye Kuvunjika',
    'delivery.special_instructions': 'Maelekezo Maalum',
    'delivery.recipient_info': 'Habari za Mpokeaji',
    'delivery.recipient_name': 'Jina la Mpokeaji',
    'delivery.recipient_phone': 'Simu ya Mpokeaji',
    'delivery.delivery_address': 'Anwani ya Uwasilishaji',
    'delivery.delivery_instructions': 'Maelekezo ya Ufikiaji',
    'delivery.preferred_time': 'Wakati Unaopendwa',
    'delivery.status.pending': 'Inasubiri',
    'delivery.status.confirmed': 'Imethibitishwa',
    'delivery.status.assigned': 'Dereva amepangiwa',
    'delivery.status.collected': 'Kitu kimechukuliwa',
    'delivery.status.in_transit': 'Njiani',
    'delivery.status.out_for_delivery': 'Nje kwa uwasilishaji',
    'delivery.status.delivered': 'Kimefikishwa',
    'delivery.status.failed': 'Kimeshindwa',
    'delivery.status.returned': 'Kimerudishwa',
    'delivery.base_price': 'Bei ya Msingi',
    'delivery.distance_fee': 'Ada ya Umbali',
    'delivery.weight_fee': 'Ada ya Uzito',
    'delivery.express_fee': 'Ada ya Haraka',
    'delivery.total_cost': 'Gharama ya Jumla',
    'delivery.estimated_cost': 'Gharama ya Mkadirifu',
    
    // WALLET & KWENDA PAY SYSTEM (50+ keys)
    'wallet.title': 'KwendaPay',
    'wallet.balance': 'Salio',
    'wallet.available_balance': 'Salio Linalopatiakana',
    'wallet.pending_balance': 'Salio Linasubiri',
    'wallet.total_balance': 'Salio la Jumla',
    'wallet.top_up': 'Ongeza Pesa',
    'wallet.withdraw': 'Toa Pesa',
    'wallet.send_money': 'Tuma Pesa',
    'wallet.receive_money': 'Pokea Pesa',
    'wallet.transaction_history': 'Historia ya Miamala',
    'payment.type.ride': 'Malipo ya Safari',
    'payment.type.delivery': 'Malipo ya Uwasilishaji',
    'payment.type.marketplace': 'Malipo ya Soko',
    'payment.type.wallet_topup': 'Kuongeza Kwenye Wallet',
    'payment.type.withdrawal': 'Kutoa Pesa',
    'payment.type.refund': 'Kurudishia Pesa',
    'payment.type.commission': 'Kodi',
    
    // NOTIFICATIONS & ALERTS (40+ keys)
    'notifications.title': 'Arifa',
    'notifications.all': 'Arifa Zote',
    'notifications.unread': 'Hazijasomwa',
    'notifications.read': 'Zimesomwa',
    'notifications.mark_read': 'Weka kama umesoma',
    'notifications.mark_unread': 'Weka kama hujasoma',
    'notifications.clear_all': 'Futa zote',
    'notifications.delete': 'Futa',
    'notifications.settings': 'Mipangilio ya Arifa',
    'notifications.ride_assigned': 'Safari imepangiwa',
    'notifications.driver_arrived': 'Dereva amefika',
    'notifications.trip_started': 'Safari imeanza',
    'notifications.trip_completed': 'Safari imekamilika',
    'notifications.payment_received': 'Malipo yamepokelewa',
    'notifications.delivery_update': 'Habari za mizigo',
    'notifications.package_delivered': 'Kitu kimefikishwa',
    'notifications.order_confirmed': 'Agizo limethibitishwa',
    'notifications.promotion': 'Ofa maalum',
    'notifications.system_update': 'Usasishaji wa mfumo',
    'notifications.maintenance': 'Matengenezo',
    'notifications.security_alert': 'Tahadhari ya usalama',
    'notifications.enable_push': 'Washa arifa za kusukuma',
    'notifications.enable_email': 'Washa arifa za barua pepe',
    'notifications.enable_sms': 'Washa arifa za SMS',
    'notifications.ride_notifications': 'Arifa za safari',
    'notifications.delivery_notifications': 'Arifa za uwasilishaji',
    'notifications.payment_notifications': 'Arifa za malipo',
    'notifications.marketing_notifications': 'Arifa za uuzaji',
    'notifications.system_notifications': 'Arifa za mfumo',
    
    // ADVANCED FEATURES (50+ keys)
    'geolocation.title': 'Eneo',
    'geolocation.current_location': 'Eneo lako sasa',
    'geolocation.saved_places': 'Maeneo yaliyohifadhiwa',
    'geolocation.add_place': 'Ongeza mahali',
    'geolocation.edit_place': 'Hariri mahali',
    'geolocation.delete_place': 'Futa mahali',
    'geolocation.home': 'Nyumbani',
    'geolocation.work': 'Kazini',
    'geolocation.favorites': 'Mapendeleo',
    'geolocation.recent': 'Ya hivi karibuni',
    'geolocation.nearby': 'Karibu',
    'geolocation.search_location': 'Tafuta eneo',
    'geolocation.location_access': 'Ufikiaji wa eneo',
    'geolocation.enable_location': 'Washa eneo',
    'geolocation.location_permission': 'Ruhusa ya eneo',
    'chat.title': 'Mazungumzo',
    'chat.new_message': 'Ujumbe mpya',
    'chat.send_message': 'Tuma ujumbe',
    'chat.type_message': 'Andika ujumbe...',
    'chat.online': 'Mtandaoni',
    'chat.offline': 'Nje ya mtandao',
    'chat.typing': 'Anaandika...',
    'chat.delivered': 'Umefikishwa',
    'chat.read': 'Umesomwa',
    'chat.support_chat': 'Mazungumzo ya msaada',
    'chat.driver_chat': 'Mazungumzo na dereva',
    'chat.seller_chat': 'Mazungumzo na muuza',
    
    // ADMIN INTERFACE & ANALYTICS (40+ keys)
    'admin.title': 'Uongozi',
    'admin.dashboard': 'Dashibodi',
    'admin.analytics': 'Uchanganuzi',
    'admin.reports': 'Ripoti',
    'admin.users_management': 'Uongozi wa Watumiaji',
    'admin.drivers_management': 'Uongozi wa Madereva',
    'admin.partners_management': 'Uongozi wa Washirika',
    'admin.vehicle_management': 'Uongozi wa Magari',
    'admin.financial_reports': 'Ripoti za Kifedha',
    'admin.operational_reports': 'Ripoti za Uendeshaji',
    'admin.system_settings': 'Mipangilio ya Mfumo',
    'admin.service_zones': 'Maeneo ya Huduma',
    'admin.pricing_rules': 'Kanuni za Bei',
    'admin.surge_pricing': 'Bei ya Msongamano',
    'admin.promotions': 'Matangazo',
    'admin.discount_codes': 'Misimbo ya Punguzo',
    'admin.maintenance_mode': 'Hali ya Matengenezo',
    'admin.system_updates': 'Usasishaji wa Mfumo',
    'admin.total_users': 'Watumiaji wa Jumla',
    'admin.active_drivers': 'Madereva Hai',
    'admin.daily_rides': 'Safari za Kila Siku',
    'admin.revenue': 'Mapato',
    'admin.popular_routes': 'Njia za Umaarufu',
    'admin.peak_hours': 'Masaa ya Kilele',
    'admin.user_satisfaction': 'Kuridhika kwa Watumiaji',
    'admin.performance_metrics': 'Vipimo vya Utendaji',
    'admin.daily_report': 'Ripoti ya Kila Siku',
    'admin.weekly_report': 'Ripoti ya Kila Wiki',
    'admin.monthly_report': 'Ripoti ya Kila Mwezi',
    'admin.financial_summary': 'Muhtasari wa Kifedha',
    'admin.driver_performance': 'Utendaji wa Madereva',
    'admin.customer_feedback': 'Maoni ya Wateja',
    'admin.export_data': 'Hamisha Data',
    'admin.generate_report': 'Tengeneza Ripoti',
    
    // ERROR MESSAGES
    'error.invalid_input': 'Ingizo si sahihi',
    'error.required_field': 'Uga huu unahitajika',
    'error.invalid_email': 'Barua pepe si sahihi',
    'error.invalid_phone': 'Nambari ya simu si sahihi',
    'error.password_too_short': 'Nywila ni fupi sana',
    'error.passwords_mismatch': 'Nywila hazilingani',
    'error.account_not_found': 'Akaunti haijapatikana',
    'error.login_failed': 'Kuingia kumeshindwa',
    'error.registration_failed': 'Usajili umeshindwa',
    'error.permission_denied': 'Ruhusa imekataliwa',
    'error.insufficient_balance': 'Salio haitoshi',
    'error.payment_failed': 'Malipo yameshindwa',
    'error.order_failed': 'Agizo limeshindwa',
    'error.delivery_failed': 'Uwasilishaji umeshindwa',
    'error.location_unavailable': 'Eneo halitapatikani',
    'error.driver_unavailable': 'Dereva hatapatikani',
    'error.service_unavailable': 'Huduma haitapatikani'
  }
};

interface LanguageContextType {
  currentLanguage: Language;
  language: Language; // Alias for compatibility
  setLanguage: (language: Language) => void;
  t: (key: string, params?: Record<string, any>) => string;
  formatCurrency: (amount: number, currency?: string) => string; // Added for compatibility
  availableLanguages: { code: Language; name: string; flag: string }[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('fr');

  const t = (key: string, params?: Record<string, any>): string => {
    const translation = translations[currentLanguage]?.[key] || translations.fr[key];
    
    // Système anti-régression : Détecter les clés manquantes
    if (!translation) {
      if (process.env.NODE_ENV === 'development') {
        console.warn(`🚨 MISSING TRANSLATION: "${key}" in language "${currentLanguage}"`);
        return `[MISSING: ${key}]`; // Affichage visible pour les développeurs
      }
      return key; // Fallback en production
    }
    
    if (params) {
      return translation.replace(/\{(\d+)\}/g, (match, index) => {
        return params[index] || match;
      });
    }
    
    return translation;
  };

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
    localStorage.setItem('kwenda-language', language);
  };

  const formatCurrency = (amount: number, currency = 'CDF'): string => {
    return `${amount.toLocaleString()} ${currency}`;
  };

  const availableLanguages = [
    { code: 'fr' as Language, name: 'Français', flag: '🇫🇷' },
    { code: 'en' as Language, name: 'English', flag: '🇺🇸' },
    { code: 'kg' as Language, name: 'Kikongo', flag: '🇨🇩' },
    { code: 'lua' as Language, name: 'Tshiluba', flag: '🇨🇩' },
    { code: 'sw' as Language, name: 'Kiswahili', flag: '🇹🇿' }
  ];

  React.useEffect(() => {
    const savedLanguage = localStorage.getItem('kwenda-language') as Language;
    if (savedLanguage && ['fr', 'en', 'kg', 'lua', 'sw'].includes(savedLanguage)) {
      setCurrentLanguage(savedLanguage);
    }
    
    // Validation automatique des traductions en mode développement
    logMissingTranslations();
  }, []);

  return (
    <LanguageContext.Provider value={{
      currentLanguage,
      language: currentLanguage, // Alias for compatibility
      setLanguage,
      t,
      formatCurrency,
      availableLanguages
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};