
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { supabaseCircuitBreaker } from '@/lib/circuitBreaker';

const SUPABASE_URL = "https://wddlktajnhwhyquwcdgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkZGxrdGFqbmh3aHlxdXdjZGdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDA1NjUsImV4cCI6MjA2OTcxNjU2NX0.rViBegpawtg1sFwafH_fczlB0oeA8E6V3MtDELcSIiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const baseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// ✅ PHASE 9: Export direct du client sans circuit breaker pour éviter les conflits
// Le circuit breaker interfère avec le query builder pattern de Supabase
export const supabase = baseClient;

// Attach to window for legacy components referencing window.supabase
if (typeof window !== 'undefined') {
  (window as any).supabase = supabase;
}
