
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { supabaseCircuitBreaker } from '@/lib/circuitBreaker';

const SUPABASE_URL = "https://wddlktajnhwhyquwcdgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkZGxrdGFqbmh3aHlxdXdjZGdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDA1NjUsImV4cCI6MjA2OTcxNjU2NX0.rViBegpawtg1sFwafH_fczlB0oeA8E6V3MtDELcSIiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const baseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// ✅ PHASE 9: Wrapper avec Circuit Breaker pour protection
export const supabase = new Proxy(baseClient, {
  get(target, prop) {
    const original = (target as any)[prop];
    
    // Protéger les appels critiques avec circuit breaker
    if (prop === 'from' || prop === 'rpc') {
      return (...args: any[]) => {
        const builder = original.apply(target, args);
        
        // Wrapper les méthodes de query
        return new Proxy(builder, {
          get(builderTarget, builderProp) {
            const builderOriginal = (builderTarget as any)[builderProp];
            
            if (typeof builderOriginal === 'function' && 
                ['select', 'insert', 'update', 'delete', 'upsert'].includes(builderProp as string)) {
              return async (...queryArgs: any[]) => {
                return supabaseCircuitBreaker.execute(() => 
                  builderOriginal.apply(builderTarget, queryArgs)
                );
              };
            }
            
            return builderOriginal;
          }
        });
      };
    }
    
    return original;
  }
});

// Attach to window for legacy components referencing window.supabase
if (typeof window !== 'undefined') {
  (window as any).supabase = supabase;
}
