
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { supabaseCircuitBreaker } from '@/lib/circuitBreaker';
import { logger } from '@/utils/logger';

const SUPABASE_URL = "https://wddlktajnhwhyquwcdgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkZGxrdGFqbmh3aHlxdXdjZGdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDA1NjUsImV4cCI6MjA2OTcxNjU2NX0.rViBegpawtg1sFwafH_fczlB0oeA8E6V3MtDELcSIiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const baseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce' // Plus sécurisé et rapide
  },
  global: {
    headers: {
      'X-Client-Info': 'kwenda-vtc/1.0.0'
    },
    fetch: async (url, options = {}) => {
      // BYPASS circuit breaker pour l'authentification
      const isAuthRequest = url.includes('/auth/v1/token') || 
                           url.includes('/auth/v1/signup') ||
                           url.includes('/auth/v1/recover') ||
                           url.includes('/auth/v1/user');
      
      const executeFetch = async () => {
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 20000); // 20s au lieu de 10s
        
        try {
          const response = await fetch(url, {
            ...options,
            signal: controller.signal,
            credentials: 'same-origin'
          });
          clearTimeout(timeoutId);
          
          if (!response.ok && response.status >= 500) {
            logger.warn(`⚠️ Supabase server error ${response.status}: ${url}`);
          }
          
          return response;
        } catch (error) {
          clearTimeout(timeoutId);
          logger.error('❌ Supabase fetch error:', error);
          throw error;
        }
      };
      
      // Si authentification, bypasser le circuit breaker
      if (isAuthRequest) {
        logger.info('🔓 Auth request - bypassing circuit breaker');
        return executeFetch();
      }
      
      // Sinon, utiliser le circuit breaker
      return supabaseCircuitBreaker.execute(executeFetch);
    }
  },
  db: {
    schema: 'public'
  },
  realtime: {
    params: {
      eventsPerSecond: 2 // Throttle realtime updates
    }
  }
});

// ✅ PHASE 9: Export direct du client sans circuit breaker pour éviter les conflits
// Le circuit breaker interfère avec le query builder pattern de Supabase
export const supabase = baseClient;

// Attach to window for legacy components referencing window.supabase
if (typeof window !== 'undefined') {
  (window as any).supabase = supabase;
}
